### ISSUE TITLE
Invalid parameter nodemanager_secure_listener on Wls_adminserver

### ISSUE THREAD

**Issue by bradmcnaughton** [biemond/biemond-orawls#100]
Hi Edwin,

Since the change on 19/12 (Support for nodemanager without any security/plain) I see this error when we try to build the domain.
I'm running puppet locally (puppet apply --debug --trace /etc/puppetlabs/puppet/environments/dev/manifests/site.pp) and I've restarted the puppet agent since upgrading the module to the latest.

Is this change dependent on anything externally on the system? I see that the lib/puppet/provider/wls_adminserver/wls_adminserver.rb is much more complex than the other providers which just have the simple.rb.

We also upgraded our Puppet Master and Agents from 3.2 to 3.7 at the end of December.

Runtime environment: puppet_version=3.7.3 (Puppet Enterprise 3.7.1), ruby_version=1.9.3, run_mode=user, default_encoding=UTF-8

If it helps I can provide the full log and the site.pp/YAML.

Thanks for any ideas.
Brad

Debug: File[nodemanager.properties ux nodemanager]: Adding default for backup
Debug: Exec[startNodemanager nodemanager]: Adding default for logoutput
Error: Invalid parameter nodemanager_secure_listener on Wls_adminserver[uat_admin:AdminServer] at /mnt/puppet-data/puppet-environments/dev/modules/orawls/manifests/control.pp:61 on node uat-soa-pl1.omw.example.com.au
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/resource.rb:499:in `validate_parameter'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/parser/resource.rb:261:in `block in validate'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/parser/resource.rb:260:in `each'
..snip...
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util/command_line.rb:92:in `execute'
/opt/puppet/bin/puppet:8:in `<main>'
Wrapped exception:
Invalid parameter nodemanager_secure_listener
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/resource.rb:499:in `validate_parameter'
...snip....
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util/command_line.rb:92:in `execute'
/opt/puppet/bin/puppet:8:in `<main>'
Error: Invalid parameter nodemanager_secure_listener on Wls_adminserver[uat_admin:AdminServer] at /mnt/puppet-data/puppet-environments/dev/modules/orawls/manifests/control.pp:61 on node uat-soa-pl1.omw.example.com.au
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/resource.rb:499:in `validate_parameter'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/parser/resource.rb:261:in `block in validate'
...

**Comment by biemond** [comment]
his Brad,

This should work and the default is secure so this should work for you. But I know puppet is doing a lot caching so can you restart all pe services on the master and client vm's . Next do a puppet run on the master first , puppet agent --test, plus same on the clients . This will detect  all the differences.

Yeah wls adminserver is a puppet type and not easy type one. And is doing all the server control actions and supports subscribe with refresh only.

Hope this helps

**Comment by bradmcnaughton** [comment]
Hi Edwin,
I wasn't able to resolve it with a restart. I ended up dropping the control.pp and changing to the wls_adminserver resource instead. That woks fine.
Anyway, this seems most likely to be environment related so I'll close it. Thanks for your advice!

**Comment by biemond** [comment]
Hi Brad

I also had those errors when I used the same manifests name like opatch in the oradb and the orawls module. Somehow the module namespace is ignored in the catalog phase.

or there can be 2 version of orawls on the puppet module path , even with a different name like orawls.old

but wls_adminserver is the one to use.

Cheers

**Comment by biemond** [comment]
Hi Brad, 

Did you see this bug in puppet master 
Move orawls and easy_type to the primary module location [pup-1515](https://tickets.puppetlabs.com/browse/PUP-1515) when the Puppet master loads a Type, it searches the environment that the agent requested. When it loads providers for that type, it searches the default environment instead of the one the agent requested.
