### ISSUE TITLE
StartScriptEnabled configurability

### ISSUE THREAD

**Issue by adamjk-dev** [biemond/biemond-orawls#101]
It would be nice if we could make this property configurable (true | false) in the templates that use it:

(templates/nodemgr/nodemanager.properties*, I see 3 templates that use it)

Thanks!

**Comment by biemond** [comment]
what is the use case for this change because StartScriptEnabled = true works for all wls configurations and it must have the value true for fmw software

and it also picks up all server arguments defined on the managed server. 
Best of both worlds, so you need to have a really good reason to add this feature

**Comment by adamjk-dev** [comment]
I am not a weblogic expert by any means, so I always enjoy hearing your feedback. It seems that in our configurations somehow our JVM memory arguments are being picked up twice. 

I got the following feedback from a customer:
"
Multiple arguments picked up (-Xms512m -Xmx512m) due to following setting in "/app/oracle/wls1036/wlserver_10.3/common/nodemanager/nodemanager.properties/nodemanager.properties”. (Puppet reverts this file so this fix is important so we can manage manually)
 
StartScriptEnabled=true (switch to false)

Memory argument is being picked up twice and we think it’s because of that setting in nodemanager.properties file.  Switching to false should take care of it.
"

So, I thought it was worth a shot to try. I know we set JVM arguments in these places in my hiera.yaml:

domain_instances:
  java_arguments:
        ADM:  "-XX:PermSize=256m -XX:MaxPermSize=512m -Xms512m -Xmx512m"

server_instances:
  arguments:
           - *server_vm_args_permsize
           - *server_vm_args_max_permsize
           - *server_vm_args_memory
           - *server_vm_args_max_memory

**Comment by biemond** [comment]
Ok :-) 

No worries, it is a weblogic/oracle standard, the last -D parameters counts and that is always the server arguments.

and indeed you should never change the bin scripts because a patch or some admin can revert your changes or difference on X nodes. 
Server argument and nodemanagers are the way to go.

**Comment by adamjk-dev** [comment]
Yeah, I am talking to another person on the team (who knows WL more than me), and apparently, when we call startupWeblogic.sh we point to some of our own scripts etc. that set some JVM arguments, then the ones we set in the hiera.yaml above get appended to the startup string. 

So, I see the process running as follows:
/app/java/1.6.0_45-R28.2.7-4.1.0/bin/java -jrockit -Xms512m -Xmx512m -Dweblogic.Name=AdminServer -Djava.security.policy=/app/oracle/wls1036/wlserver_10.3/server/lib/weblogic.policy -Dweblogic.ProductionModeEnabled=true -Dweblogic.system.BootIdentityFile=/projects/ADAMTEST/servers/AdminServer/security/boot.properties -Dweblogic.nodemanager.ServiceEnabled=true -XX:PermSize=256m -XX:MaxPermSize=512m -Xms512m -Xmx512m -da -Dplatform.home=/app/oracle/wls1036/wlserver_10.3 -Dwls.home=/app/oracle/wls1036/wlserver_10.3/server -Dweblogic.home=/app/oracle/wls1036/wlserver_10.3/server -Dweblogic.management.discover=true -Dwlw.iterativeDev=false -Dwlw.testConsole=false -Dwlw.logErrorsToConsole=false -Dweblogic.ext.dirs=/app/oracle/wls1036/patch_wls1036/profiles/default/sysext_manifest_classpath:/app/oracle/wls1036/patch_ocp371/profiles/default/sysext_manifest_classpath weblogic.Server

So, I see two sets of Xms and Xmx is what the customer is brining up. My coworker thought the last parameters took precedence as well (so I am testing by changing the numbers to make the 2nd set of parameters different so we can definitively say so).

But, you are saying it doesn't matter that two sets of equivalent defines exist? The last ones take precedence?

**Comment by biemond** [comment]
yeah indeed,

and get rid of your own scripts and put it in yaml so everybody can see, knows about it and is consistent on all servers.

**Comment by adamjk-dev** [comment]
Great, testing now (not that I don't trust you, haha). Oh, I agree. We are just in the initial states and I think people like to have some of their original stuff vs. adopt all new, so it is in that tough period in my opinion. I agree on openness and a single point of control for sure for this stuff. We will get there I hope :)

**Comment by adamjk-dev** [comment]
So, you were correct, the later parameters are the ones used. Seems no harm no foul, just a visible problem, but those set in the JVM arguments via hiera are applied to the string last and are then the ones used.
