### ISSUE TITLE
Adding LDAP authentication

### ISSUE THREAD

**Issue by joewimmer** [biemond/biemond-orawls#105]
Hey, So I am adding ActiveDirectoryAuthentication which is successful the first run but throws soft errors on the second run of:

```
Debug: Unexpected error: java.lang.IllegalArgumentException

Debug: Discarded all your changes successfully.

Debug: Edit session has been stopped successfully.

Debug: ~~~~COMMAND FAILED~~~~

Error: Could not set 'present' on ensure: command in deamon failed.
Error: Could not set 'present' on ensure: command in deamon failed.
Wrapped exception:
command in deamon failed.
Error: /Stage[main]/Weblogic::Security/Wls_authentication_provider[ActiveDirectoryAuthenticator]/ensure: change from absent to present failed: Could not set 'present' on ensure: command in deamon failed.
Debug: Class[Weblogic::Security]: The container Stage[main] will propagate my refresh event
Notice: /Stage[main]/Weblogic_prep::Links/File[/logs/JOETEST/log4j]: Dependency Wls_authentication_provider[ActiveDirectoryAuthenticator] has failures: true
Warning: /Stage[main]/Weblogic_prep::Links/File[/logs/JOETEST/log4j]: Skipping because of failed dependencies
Notice: /Stage[main]/Weblogic_prep::Links/File[/projects/JOETEST/logs]: Dependency Wls_authentication_provider[ActiveDirectoryAuthenticator] has failures: true
Warning: /Stage[main]/Weblogic_prep::Links/File[/projects/JOETEST/logs]: Skipping because of failed dependencies

```
Here is my hiera data:

```
authentication_provider_instances:
  'DefaultAuthenticator':
    ensure:             'present'
    control_flag:       'SUFFICIENT'
  'ActiveDirectoryAuthenticator':
    ensure:             'present'
    control_flag:       'SUFFICIENT'
    providerclassname:  'weblogic.security.providers.authentication.ActiveDirectoryAuthenticator'
    attributes:         'Credential;GroupBaseDN;GroupFromNameFilter;GroupMembershipSearching;Host;MaxGroupMembershipSearchLevel;Principal;UserBaseDN;UserFromNameFilter;UserNameAttribute;Port'
    attributesvalues:   'secretPassword;DC=ad,DC=organization,DC=org;(&(sAMAccountName=%g)(objectclass=group));limited;ad.organization.org;0;CN=SER_Account,OU=Service Accounts,DC=ad,DC=organization,DC=org;DC=ad,DC=organization,DC=org;(&(sAMAccountName=%u)(objectclass=user));sAMAccountName;389'
    order:              '0'

```

My only guess is that its trying to create the ActiveDirectoryAuthenticator when it already exists?

I also have to restart the server to not get this message when trying to view users/groups.

```
This page is not available because non-dynamic changes have been made and the Admin Server requires a restart. Please restart the Admin Server to make this page available. Alternatively, you can make this page available by enabling "Allow Security Management Operations if Non-dynamic Changes have been Made" field on the Domain: Security page. (Link to Domain Security Page) 

```

**Comment by biemond** [comment]
Hi,

indeed, after an authenticator change you need to subscribe on this change ( also for domain changes ) and autorestart the adminserver 

here you got an example of this.

https://github.com/biemond/biemond-orawls-vagrant/blob/master/puppet/hieradata/admin.example.com.yaml

but after restart it should re- create it again.  then the index.py script is failing.
https://github.com/biemond/biemond-orawls/blob/master/files/providers/wls_authentication_provider/index.py.erb

you can use puppet resource wls_authentication_provider --debug or run puppet with --debug to see this WLST script and test it yourself in wlst.sh 

hope this helps

**Comment by joewimmer** [comment]
Hey thanks for helping!
Maybe I'm missing something or don't understand what your saying.  This seems non-idempotent since it errors on the second run but all green on the initial run.  

When i try the: puppet resource wls_authentication_provider --debug command i get 

```
Could not run: Could not find template 'puppet:///modules/orawls/providers/wls_authentication_provider/index.py.erb'

```

Thanks again

**Comment by biemond** [comment]
ok,

oh you are using a puppet master, that the reason puppet resource fails

but the index py script fails , so it doesnt detect it is already there is and so it will do another create.  

can you do this puppet agent --test --debug. If it fails can you update to the latest version.

**Comment by joewimmer** [comment]
Hey,
After reviewing commit, 'ad6e98f30f884cc1a6c7b79feda629d75682583c', i've 
found that the check won't work for the 'ActiveDirectoryAuthenticator' provider that we are using. 

weblogic.security.providers.authentication.ActiveDirectoryAuthenticator

**Comment by biemond** [comment]
oh strange, 

does it crash

**Comment by biemond** [comment]
Can you try this manually with wlst

https://github.com/biemond/biemond-orawls/blob/master/files/providers/wls_authentication_provider/index.py.erb

Only user and group won't support external ldap because it can be too heavy to retrieve them all

**Comment by joewimmer** [comment]
Ran the script directly and got this.

```
Successfully connected to Admin Server 'AdminServer' that belongs to domain 
'JOETEST'.Warning: An insecure protocol was used to connect to the server. 
To ensure on-the-wire security, the SSL port orAdmin port should be used instead.dr-- DefaultAuthenticatordr-- DefaultIdentityAsserter___DefaultAuthenticator___
Problem invoking WLST - Traceback (innermost last):File "/home/ser_dvapp/index.py", line 41, 
in ?NameError: domain

```

In the output file is:

```
name;authentication_provider_name;control_flag;domain;order

```
Not sure if this is what you wanted...

**Comment by biemond** [comment]
thanks

can you add this to the top of the script. 

domain = 'xxx'

and try it again because https://github.com/biemond/biemond-orawls/blob/master/lib/utils/wls_daemon.rb
automatically add this to every WLST invocation.

**Comment by joewimmer** [comment]
```
Stdout:
 
dr--   DefaultAuthenticator
dr--   DefaultIdentityAsserter
 
___DefaultAuthenticator___
___DefaultIdentityAsserter___
This Exception occurred at Wed Jan 21 14:02:24 EST 2015.
javax.management.AttributeNotFoundException: Security:Name=myrealmDefaultIdentityAsserter:ControlFlag
ControlFlag does not exists, continue
~~~~COMMAND SUCCESFULL~~~~
 
```
/tmp/wlstScript.out:
 
```
name;authentication_provider_name;control_flag;domain;order
"xxx/DefaultAuthenticator";"DefaultAuthenticator";"REQUIRED";"xxx";"0"
"xxx/DefaultIdentityAsserter";"DefaultIdentityAsserter";;"xxx";"1"
```

**Comment by biemond** [comment]
Ok much better

did you add the AD authentication provider? 
Because this looks ok and it does not crash.

Thanks

**Comment by joewimmer** [comment]
Obviously I'm not the best with weblogic so I apologize.   When I login to the console there are three providers.  One being ActiveDirectoryAuthenticator.  When I run the script directly, your right it doesn't fail.  But when i run puppet it fails. Is there something that needs to be added to the script that will pick up ActiveDirectoryAuthenticator ? Thanks for your help. I know this is painful.

**Comment by biemond** [comment]
And did you restart the adminserver?

your script fails in create ( already exists) and not in index, the index script should detect this one so puppet does not need to execute the create script

Can you give me your AD wls puppet definition, I will also add this to my config and see if I can find the problem in the index py script.

**Comment by joewimmer** [comment]
Its all pulled from hiera which is 

```
authentication_provider_instances:
  'DefaultAuthenticator':
    ensure:             'present'
    control_flag:       'SUFFICIENT'
    order:              '0'
  'ActiveDirectoryAuthenticator':
    ensure:             'present'
    control_flag:       'SUFFICIENT'
    providerclassname:  'weblogic.security.providers.authentication.ActiveDirectoryAuthenticator'
    attributes:         'Credential;GroupBaseDN;GroupFromNameFilter;GroupMembershipSearching;Host;MaxGroupMembershipSearchLevel;Principal;UserBaseDN;UserFromNameFilter;UserNameAttribute;Port'
    attributesvalues:   'password;DC=ad,DC=company,DC=org;(&(sAMAccountName=%g)(objectclass=group));limited;ad.company.org;0;CN=SER_WASadmin,OU=Service Accounts,DC=ad,DC=company,DC=org;DC=ad,DC=company,DC=org;(&(sAMAccountName=%u)(objectclass=user));sAMAccountName;389'
    order:              '1'
    #before:             Orawls::Domain[domain]


```

I tried the before but that failed before running which is why its commented out. 

Hope this is what you requested.

**Comment by biemond** [comment]
thanks

I will do some tests and make a patch

**Comment by biemond** [comment]
Your config is working fine for me
see 
https://github.com/biemond/biemond-orawls-vagrant-12.1.3/blob/master/puppet/hieradata/admin.example.com.yaml#L144

[vagrant@admin ~]$ sudo puppet resource wls_authentication_provider
wls_authentication_provider { 'default/ActiveDirectoryAuthenticator':
  ensure       => 'present',
  control_flag => 'SUFFICIENT',
  order        => '1',
}
wls_authentication_provider { 'default/DefaultAuthenticator':
  ensure       => 'present',
  control_flag => 'SUFFICIENT',
  order        => '0',
}
wls_authentication_provider { 'default/DefaultIdentityAsserter':
  ensure => 'present',
  order  => '2',
}

So probably you need to restart the adminserver

like this 

    authentication_provider_instances:
      'DefaultAuthenticator':
        ensure:             'present'
        control_flag:       'SUFFICIENT'
        order:              '0'
      'ActiveDirectoryAuthenticator':
        ensure:             'present'
        control_flag:       'SUFFICIENT'
        providerclassname:  'weblogic.security.providers.authentication.ActiveDirectoryAuthenticator'
        attributes:         'Credential;GroupBaseDN;GroupFromNameFilter;GroupMembershipSearching;Host;MaxGroupMembershipSearchLevel;Principal;UserBaseDN;UserFromNameFilter;UserNameAttribute;Port'
        attributesvalues:   'password;DC=ad,DC=company,DC=org;(&(sAMAccountName=%g)(objectclass=group));limited;ad.company.org;0;CN=SER_WASadmin,OU=Service Accounts,DC=ad,DC=company,DC=org;DC=ad,DC=company,DC=org;(&(sAMAccountName=%u)(objectclass=user));sAMAccountName;389'
        order:              '1'

    # subscribe on a domain change and restart the adminserver
    wls_adminserver_instances_domain:
      'AdminServer_Wls1213':
        ensure:                    'running'
        server_name:               *domain_adminserver
        domain_name:               *domain_name
        domain_path:               "/opt/oracle/wlsdomains/domains/Wls1213"
        os_user:                   *wls_os_user
        weblogic_home_dir:         *wls_weblogic_home_dir
        weblogic_user:             *wls_weblogic_user
        weblogic_password:         *domain_wls_password
        jdk_home_dir:              '/usr/java/latest'
        nodemanager_address:       *domain_adminserver_address
        nodemanager_port:          *domain_nodemanager_port
        jsse_enabled:              true
        custom_trust:              *wls_custom_trust
        trust_keystore_file:       *wls_trust_keystore_file
        trust_keystore_passphrase: *wls_trust_keystore_passphrase
        refreshonly:               true
        subscribe:                 Wls_authentication_provider[ActiveDirectoryAuthenticator]
