### ISSUE TITLE
nodemanager sleep time

### ISSUE THREAD

**Issue by adamjk-dev** [biemond/biemond-orawls#106]
Hello sir,

So, I updated to use the latest orawls module today, and am currently getting this error:

Error: Failed to apply catalog: Parameter bedtime failed on Sleep[wake up nodemanager]: sleepy time isn't an integer at /etc/puppetlabs/puppet/environments/cse_wl_production/modules/orawls/manifests/nodemanager.pp:173
Wrapped exception:
sleepy time isn't an integer

Have you tried to set the 'wls_nodemanager_sleep' variable in your hiera data (instead of using the default of 20 seconds)?

When I run with the following in my hiera data, I get the error:
wls_nodemanager_sleep:    80

But, I commented it out and it seemed to not fail with that error (likely because it used the default of 20 seconds). Perhaps something is up with the type conversions with hiera and what is passed into the fiddyspence-sleep module? 

So, have you run this with that value set in hiera data as something else? Or, perhaps we can entertain increasing the default value (since it is now a "safer" sleep). Meaning, if we set the default to 300 or more seconds, it should cover more cases, but would still execute after 20 seconds if your node manager's port came up by then.

**Comment by biemond** [comment]
Hi,

interesting , 

can you also try to use the sleep parameter on the nodemanager manifest and see if this works.
$sleep        = hiera('wls_nodemanager_sleep'         , 20), # default sleep time

I am doing the same with version & port number 

   define orawls::domain (
     $version                               = hiera('wls_version'                   , 1111),  # 1036|1111|1211|1212|1213

I think hiera always return a string and the puppet code find its ok and ruby /fiddyspence-sleep is more strict

    newproperty(:bedtime) do
      desc "how long to sleep for"
      munge do |snore|
        Integer(snore)
      end
      validate do |zzzz|
        fail("sleepy time isn't an integer") unless zzzz =~ /^\d+$/
      end

probably 20 is ok, it is only longer when the server got a hard reboot and the nodemanager also tries to start the admin server again.

and you get an error but it is only showing this error.

**Comment by adamjk-dev** [comment]
Yeah, that is what I think is happening somehow. I thought wls_nodemanager_sleep was supposed to be interpreted as an integer, but fiddyspence-sleep doesn't seem to deal with that well.

I did comment out the setting in one of my hiera values, and it did go through (using the default value of 20). 

I can try some of my other offerings with 20 seconds, but experience has shown that this will not be long enough for me. I had to set that sleep time to up to 260 seconds on some WebLogic 10 clusters with an admin server, node manager, and 2 managed nodes all on the same VM. Weblogic 10 seems to take a bit longer than 12.

I wasn't sure if we can force that variable to be an integer after reading it from hiera or something. Or, since the sleep is a maximum sleep, maybe we can just increase your default value to something a bit larger, since it is a maximum sleep and not a definite sleep (won't hold up execution any longer than it takes the node manager port to come up).

**Comment by biemond** [comment]
I will increase it 

when I read this 
https://docs.puppetlabs.com/puppet/latest/reference/lang_datatypes.html#numbers

can you try this in the nodemanager.pp

$bedtime = $sleep * 1

sleep { "wake up ${title}":
    bedtime       => $bedtime,

**Comment by adamjk-dev** [comment]
Ah, nice find, sir. Interesting to know.

I should be able to try, but would it just be easier to multiply the hiera lookup * 1? Then, after you do a hiera lookup or default to 20, we multiple by 1 and get the same as an integer either way?

**Comment by adamjk-dev** [comment]
Ah, nice find, sir. Interesting to know.

I should be able to try, but would it just be easier to multiply the hiera lookup * 1? Then, after you do a hiera lookup or default to 20, we multiple by 1 and get the same as an integer either way?

**Comment by adamjk-dev** [comment]
Ah, nice find, sir. Interesting to know.

I should be able to try, but would it just be easier to multiply the hiera lookup * 1? Then, after you do a hiera lookup or default to 20, we multiple by 1 and get the same as an integer either way?

**Comment by adamjk-dev** [comment]
I am not even sure that fixed it, did you try it? I changed that and it is still failing...

**Comment by biemond** [comment]
indeed , also got an error.

will try something else

**Comment by adamjk-dev** [comment]
Glad I am not the only one, haha. Thanks!

**Comment by biemond** [comment]
Nothing helps, 

only can make a custom parser function which returns an integer.

First will try to change puppet-sleep.
fiddyspence/puppet-sleep/issues/#1

**Comment by adamjk-dev** [comment]
Crazy, that sounds like overkill, I would hope we wouldn't need that. I guess another option is to include library code in your module and control it yourself, but nice to use the provided module.

Also, still have the option to increase the default value since it is just a maximum and shouldn't slow progress for fast node manager startups etc.

**Comment by fiddyspence** [comment]
Hi - I'm trying to reproduce your behaviour (sorry - been a bit busy), but I can't get it to fail using any of the below, which makes me wonder what values your hiera call is returning that makes the validation fail:

The validation treats the input like a string, and expects it to match the regex /^\d+$/

sleep { 'sdfsd': bedtime => '3', refreshonly => false}
sleep { 3: refreshonly => false}

$foo = hiera('foo','3')
sleep { 'sdfsd': bedtime => $foo, refreshonly => false}

$foo = hiera('foo',3)
sleep { $foo: refreshonly => false}

**Comment by biemond** [comment]
Hi

I got it failing in all situations ( I know in vagrant I am using ruby 1.8.7 and on the puppet master ruby 1.9.3 )

only executes when I do not set the sleep parameter and then uses the default 20 

    # manifest
    define orawls::nodemanager (
      $sleep  = hiera('wls_nodemanager_sleep' , 20), # default sleep time
    ) {

      # using fiddyspence/sleep module
      sleep { "wake up ${title}":
        bedtime       => $sleep,
        wakeupfor     => "/bin/ps -ef | grep -v grep | /bin/grep 'weblogic.NodeManager'",
        dozetime      => 2,
        failontimeout => true,
      }

    }


    $default_params = {}
    $nodemanager_instances = hiera('nodemanager_instances', {})
    create_resources('orawls::nodemanager',$nodemanager_instances, $default_params)

    # hiera
    wls_nodemanager_sleep:    25

    nodemanager_instances:
      'nodemanager':

 or

    nodemanager_instances:
      'nodemanager':
        sleep:   25

or directly 

    orawls::nodemanager{'aaa':
      sleep  => 25
    }

**Comment by fiddyspence** [comment]
Are you somehow getting some whitespace in there (there is currently no legislation for whitespace which would cause what you're seeing)

    sleep:   25

**Comment by biemond** [comment]
I also got this error when I don't use hiera
but I think with the current version of hiera everything is string. They gonna change this.

Also tried to cast it to integer inside the define (  $newsleep = 1 * $sleep ) ,this should work when you read the puppet documentation.

**Comment by fiddyspence** [comment]
It doesn't matter if hiera returns a string, as long as it's /^\d+$/

**Comment by adamjk-dev** [comment]
I think we can close this issue now, since it was fixed in the fiddyspence-sleep module in version 1.2.0.

https://github.com/fiddyspence/puppet-sleep/issues/1

**Comment by biemond** [comment]
Indeed I will at this version as dependency
