### ISSUE TITLE
Could not autoload puppet/type/wls_server: file puppet/type/wls_server/tunnelingenabled

### ISSUE THREAD

**Issue by adamjk-dev** [biemond/biemond-orawls#108]
So, I upgraded to use your latest module, and keep getting this error when trying to build a single VM cluster (with an admin server, nodemanager, and 2 managed servers) .... 

Is there anything special that needs to be done when this type was added? The puppet agent should be running on each of our compile masters and I would hope that would update the types and providers etc.

I added the tunnelingenabled variable to my server_instances block in hiera (it was already set on the server_channel_instances block).

Thanks!

**Comment by biemond** [comment]
Ah,

tunnelingenabled should be optional and does not have a default value.

did you do all the master things , like restarting all puppet master services and do a puppet run on the master else it will cache the old one and does not detect the changes on the master side,

**Comment by adamjk-dev** [comment]
I am waiting to figure that out from a team I work with.... but that is definitely where I think there may be an issue. We have a decently complex setup... multi-tenant, with a global repository and my team's repository, multiple puppet compile masters being deployed to with R10k and such.

I know puppet is running on the compile masters, just not sure if they are restarting the services each time.

**Comment by adamjk-dev** [comment]
Yeah, we restarted pe-httpd on all of our compile masters and it still fails to load the type. Are there other services as well, we thought (by talking to Puppetlabs) that this was the one we needed to restart.

**Comment by biemond** [comment]
also did some puppet runs on these master compile servers
I noticed this more , module changes are not picked up by the master.

maybe puppet agent --test --trace give some more insight

**Comment by adamjk-dev** [comment]
/opt/puppet/bin/puppet agent --test --trace
Info: Retrieving plugin
Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/custom_auth_conf.rb
Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/facter_dot_d.rb
Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/platform_tag.rb
Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/pe_build.rb
Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/postgres_default_version.rb
Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/staging_windir.rb
Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/iptables_version.rb
Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/pe_version.rb
Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/tiaa_facts.rb
Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/pe_puppetdb_server_status.rb
Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/iptables_persistent_version.rb
Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/concat_basedir.rb
Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/pe_postgres_default_version.rb
Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/ip6tables_version.rb
Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/staging_http_get.rb
Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/orawls.rb
Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/windows.rb
Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/puppet_vardir.rb
Info: Loading facts in /var/opt/lib/pe-puppet/lib/facter/root_home.rb
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not autoload puppet/type/wls_server: file puppet/type/wls_server/tunnelingenabled not found on node <nodename>
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/indirector/rest.rb:207:in `is_http_200?'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/indirector/rest.rb:100:in `find'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/indirector/indirection.rb:201:in `find'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/configurer.rb:256:in `block in retrieve_new_catalog'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util.rb:327:in `block in thinmark'
/opt/puppet/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util.rb:326:in `thinmark'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/configurer.rb:255:in `retrieve_new_catalog'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/configurer.rb:60:in `retrieve_catalog'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/configurer.rb:103:in `prepare_and_retrieve_catalog'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/configurer.rb:170:in `run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:47:in `block (4 levels) in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent/locker.rb:20:in `lock'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:47:in `block (3 levels) in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:117:in `with_client'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:44:in `block (2 levels) in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:82:in `run_in_fork'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:43:in `block in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:179:in `call'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:179:in `controlled_run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/agent.rb:41:in `run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application/agent.rb:355:in `onetime'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application/agent.rb:321:in `run_command'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:371:in `block (2 levels) in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:477:in `plugin_hook'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:371:in `block in run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util.rb:479:in `exit_on_fail'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/application.rb:371:in `run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util/command_line.rb:137:in `run'
/opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/util/command_line.rb:91:in `execute'
/opt/puppet/bin/puppet:8:in `<main>'
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

**Comment by dblaisdell** [comment]
https://tickets.puppetlabs.com/browse/PUP-1515

"So, to summarize: when the Puppet master loads a Type, it searches the environment that the agent requested. When it loads providers for that type, it searches the default environment instead of the one the agent requested."

**Comment by biemond** [comment]
Ok, you have multiple environments like test and prod.

So when you move orawls to the default environment, restart all services, do a puppet, it should works

**Comment by dblaisdell** [comment]
The issue is DEV, needs to be ahead of PROD, and we can't run both simultaneously. 

Clearly this is a puppet issue and not your issue.

**Comment by biemond** [comment]
but really great to know this because someone else also got this issue.

I updated the orawls readme

thanks

**Comment by adamjk-dev** [comment]
Yeah, I have noticed it come up a few times haha. Good to know, gotta really pay attention to the environment people are working in really (or for us or them to understand).

Thanks for the help, and hopefully this clears some things up for people and now you know too haha.
