### ISSUE TITLE
OpenLDAP - wls_group provider 'simple': timeout on reading expected output from daemon process

### ISSUE THREAD

**Issue by jasonp18** [biemond/biemond-orawls#109]
Hi Edwin,

Hope you are well. Urgently, need your advice here. We've implemented OpenLDAP integation. Initial Puppet run is fine and after reboot of Weblogic cluster, the Ldap users are groups display in the Weblogic console and no errors in the Admin Server logs. However, the subsequent Puppet runs fail repeatedly.

Env details: 
orawls version: 1.0.17
Weblogic 11.1.1.7, Oracle 11g on Red Hat platform.

Thanks in advance and look forward to your reply...

    authentication_provider_instances:
        DefaultAuthenticator:
            ensure: present
            control_flag: SUFFICIENT
            tag: mwconfig
        DefaultIdentityAsserter:
            ensure: present
            providerclassname: weblogic.security.providers.authentication.DefaultIdentityAsserter
            attributes: DigestReplayDetectionEnabled;UseDefaultUserNameMapper;DefaultUserNameMapperAttributeType;ActiveTypes
            attributesvalues: 0;0;E;AuthenticatedUser
            tag: mwconfig
        IPT-Authenticator:
            ensure: present
            control_flag: SUFFICIENT
            providerclassname: weblogic.security.providers.authentication.OpenLDAPAuthenticator
            attributes: Principal;Credential;Host;Port;UserBaseDN;UserNameAttribute;AllUsersFilter;UserFromNameFilter;UserObjectClass;GroupBaseDN;GroupFromNameFilter;StaticGroupObjectClass;StaticMemberDNAttribute;StaticGroupDNsfromMemberDNFilter;GuidAttribute;SSLEnabled
            attributesvalues: cn=adm,ou=users,dc=dummy,dc=org,dc=uk;xxxxxxxx;hostname.com;636;ou=users,dc=homeoffice,dc=gov,dc=uk;cn;;(&(cn=%u)(objectclass=inetOrgPerson));inetOrgPerson;ou=groups,dc=dummy,dc=org,dc=uk;(&(cn=%g)(objectclass=groupofnames));groupofnames;member;(&(member=%M)(objectclass=groupofnames));entryuuid;false

Info: Connecting to wls on url t3://xxxxxx:7001
Error: Could not prefetch wls_group provider 'simple': timeout on reading expected output from daemon process.
Info: create default/Administrators
Info: Executing: wlstScript with action
Info: Got the right domain default script, now execute WLST
Info: Executing wls-script /tmp/wlstScript20150122-23148-1c9hlum.py
Info: Connecting to wls on url t3://xxxxxxx:7001
Error: Could not set 'present' on ensure: command in deamon failed.
Error: Could not set 'present' on ensure: command in deamon failed.
Wrapped exception:
command in deamon failed.
Error: /Stage[main]/Profile::Wls::Groups/Wls_group[Administrators]/ensure: change from absent to present failed: Could not set 'present' on ensure: command in deamon failed.

**Comment by biemond** [comment]
Ok,

so wls_group or wls_user is failing , did you also restart the adminserver.

can you run it manually with puppet agent/apply --test --debug --trace

this will give you the wlst script 
can you run this output in wlst ( and connect to the adminserver ) 

and start with ( this variable is normally set by the daemon )

domain = 'xxx'

**Comment by jasonp18** [comment]
Thanks...have closed this issue. Have hotfixed using the related code in the latest orawls version until we have a chance to upgrade.

Cheers Jason
