### ISSUE TITLE
Auth Provider Ordering throwing exception

### ISSUE THREAD

**Issue by ds2000** [biemond/biemond-orawls#112]
Hi,

We're trying to order out auth providers as below in Hiera:

    openldap:
        ensure: present
        control_flag: SUFFICIENT
        providerclassname: weblogic.security.providers.authentication.OpenLDAPAuthenticator
        attributes: Principal;Credential;Host;Port;UserBaseDN;UserNameAttribute;AllUsersFilter;UserFromNameFilter;UserObjectClass;GroupBaseDN;GroupFromNameFilter;StaticGroupObjectClass;StaticMemberDNAttribute;StaticGroupDNsfromMemberDNFilter;GuidAttribute;SSLEnabled
        attributesvalues: cn=admin,dc=xxxx,dc=xxxx,dc=xxxxx;password;servername;389;ou=users,dc=xxxxxxx,dc=xxxx,dc=xxxx;cn;;(&(cn=%u)(objectclass=inetOrgPerson));inetOrgPerson;ou=groups,dc=xxxxxxx,dc=xxxxx,dc=xxxxx;(&(cn=%g)(objectclass=groupofnames));groupofnames;member;(&(member=%M)(objectclass=groupofnames));entryuuid;false
        order: 0     
        tag: mwconfig
    DefaultAuthenticator:
        ensure: present
        control_flag: SUFFICIENT
        order: 1
        tag: mwconfig
    DefaultIdentityAsserter:
        ensure: present
        providerclassname: weblogic.security.providers.authentication.DefaultIdentityAsserter
        attributes: DigestReplayDetectionEnabled;UseDefaultUserNameMapper;DefaultUserNameMapperAttributeType;ActiveTypes
        attributesvalues: 0;0;E;AuthenticatedUser
        order: 2
        tag: mwconfig

However we're getting this error when puppet runs:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter order on node servername
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

We're running Puppet version 1.0.17

Thanks

Dave

**Comment by biemond** [comment]
Hi Dave, 

that it strange, are you by the way using a puppet master with multiple environments. if so please read this 
https://github.com/biemond/biemond-orawls#puppet-master-with-orawls-module-key-points
escpecially the puppet bug where types are always loaded from the primary location. 

Also in the latest version on github we are changing wls_authentication_provider. Add better order fault handling and the DefaultIdentityAsserter will get its own type
https://github.com/biemond/biemond-orawls#wls_identity_asserter

hope this helps

**Comment by ds2000** [comment]
Thanks, my colleague Jason (I think you guys have spoke a little before), has compared our version of the PM to .25 and we can see we're missing the ordering from our module.

We're currently looking at a way to patch this functionality in.

Thanks again

Dave
