### ISSUE TITLE
Hiera wlstexec not showing in debug.

### ISSUE THREAD

**Issue by ds2000** [biemond/biemond-orawls#113]
Hi,

Following on from this mornings issue (old puppet module not supporting ordering); I've added a WLST exec statement to the hiera as a work around (until we upgrade).  However, I'm not seeing any attempt to execute this in the debug log.  Am I missing something?

    orawls::wlstexec:
        OrderAuthProviders:
            domain_name: cdpdomain
            weblogic_home_dir: /u01/app/oracle/product/fmw/wlserver_10.3
            connect_url: t3://soatzm01:7101
            weblogic_user: weblogic
            weblogic_password: weblogic1
            adminserver_address: soatzm01
            adminserver_port: 7101
            logoutput: true
            script: orderAuthProvidersList.py
            params:
               - "LDAPProviderName = 'openldap'"
            tag: mwconfig

Thanks once again

Dave

**Comment by biemond** [comment]
hehe

wlstexec does not exists in orawls, I have this in wls puppet module but wls will conflict with orawls.
So you have to wait or do it manually in the weblogic console ( puppet won't change the order because it doesn't know this parameter )

**Comment by ds2000** [comment]
Thanks again, I certainly owe you a beer or two :)

I can do this as a sysexec and tweak my .py to accept the parameters that way.  

Thanks once more :+1: 

Dave
