### ISSUE TITLE
remove the creation of LocalMachine in domain.pp?

### ISSUE THREAD

**Issue by dportabella** [biemond/biemond-orawls#12]
Is there any reason why domain.pp creates a machine 'LocalMachine'?
just to attach the AdminServer to that LocalMachine?

however, there is not need to attach AdminServer to a 'LocalMachine'.
is this correct?
at least we don't do this.

can we remove this LocalMachine? I can send you the pull request.
otherwise, if that's really needed, the port should be configured
    cmo.setListenPort(portNumber)

and maybe the other parameters used in modules/orawls/files/providers/wls_machine/create.py.erb
(machineName, machinetype, nmType, listenaddress, listenport)

**Comment by biemond** [comment]
Changing the name of the local machine is now supported on the domain.pp manifest
