### ISSUE TITLE
wls_setting - default

### ISSUE THREAD

**Issue by robh007** [biemond/biemond-orawls#122]
Hi, question around wls_setting. Is a default always required? I've created 3 domains which all work as expected using the domain/type_instance values within the apporiate hiera configuration. But I've noticed that a key for 

default:
   !ruby/sym name: default

is placed in the /etc/wls_setting.yaml. I then get an error displayed because there are incorrect arguments within the hash. I could default a particular domain which would resolve this small issue. I just wondered if there's any other way to do it.

**Comment by biemond** [comment]
Thanks for reporting this bug. 

Mostly there is only 1 domain, but I will fix it.  There is no workaround , but when you delete this value . Is it added back in the next puppet run?

Cheers

**Comment by robh007** [comment]
I'm using vagrant to test my multi domain configuration. So I could use a puppet file resource or inline script to ensure the yaml file exists prior to running the WLS configuration within the manifest. I have the information required in hiera. I've just tested this with your suggestion the initial vagrant up fails with the default error. I then remove the default hash from the file and run a vagrant provision which puppet then runs cleanly. So I potentially have a work around. I see in the settings.rb code there's a test to see if the config_file exists else Hash['default'] I'm assuming this is where the problem lies.

**Comment by biemond** [comment]
thanks, 

Tonight, I will try to solve it t

**Comment by biemond** [comment]
Fixed in this commit SHA: 23ba92d38feefc94728a1430f30ff9a1aabe7ba2
can you try it yourself

**Comment by robh007** [comment]
Many thanks Edwin, this is working as expected now.
