### ISSUE TITLE
Settings not updated when run from multiple node in parallel for Cluster setup

### ISSUE THREAD

**Issue by yadavnikhil** [biemond/biemond-orawls#126]
Hi,

I'm currently running the puppet to change configuration for admin from multiple nodes in parallel & faced this issue few times. 

Below is what happens:Ex. Machine1 & Machine2 are running puppet in parallel & using same user to connect to admin via WLST.
1. Machine1 starts Edit session to add machine for its name in admin.
2. Machine2 also started Edit session to add machine for its name in admin.
3. Machine1 runs save() & activate() once done.
4. Machine2 tries to run save() & activate() which fails as current session is already activated by Machine1.

I think we should use the exclusive lock feature of weblogic when starting startEdit() with correct wait & timeout given to them.
Ex. startEdit(120000,120000,'true')  --> will wait for lock to be released for 120 secs & ensure only one session is currently active & modifying the configuration.

Thanks.

**Comment by biemond** [comment]
yeah you are right

Do you get this in copydomain with nmenroll on the nodes because it is designed that all configuration work is done on the admin server and the nodes only do an wls install, patch, nodemanager and copydomain.
In this case you won't get any problems with connect.

thanks

**Comment by yadavnikhil** [comment]
Still haven't encountered in copydomain for now.
For now, got the same when adding multiple managed nodes in wls_machines to the admin.
Admin is already configured & ready, its when I dynamically add multiple managed nodes to the admin.

Thanks,

**Comment by biemond** [comment]
ok 

that is not supported or designed for. you should at least do 1 for 1 or everything on the adminserver.
Your wls workaround is a fix but the problem lays in the wls core only 1 can have the edit session. They will change this in the next versions and will allow it when it doesn't conflict with the other sessions.

**Comment by yadavnikhil** [comment]
Yes, only single session that is active will be available by using exclusive lock in startEdit().
If its proposed to be handled in next versions, then well and good. But for now, if we deploying a cluster in cloud infrastructure, there will a possibility of adding multiple managed nodes in many scenarios & we can dynamically add the machine in cluster from new managed node without disturbing admin as it will also serve easy solution if we remove the machine when not needed or for maintenance from managed node itself (from puppet POV).

But for now the workaround of having startEdit() with exclusive locks will solve my problem but only for modules that managed needs to configure itself in admin. I'll try the same in my local branch.

Thanks :)
