### ISSUE TITLE
Dependency error orawls::weblogic vs orawls::domain

### ISSUE THREAD

**Issue by xmatej** [biemond/biemond-orawls#130]
Hello Edwin, 
I am currently facing problem with dependencies within orawls module

Error: Could not apply complete catalog: Found 1 dependency cycle:
(Exec[install weblogic 1036] => Class[Orawls::Weblogic] => Class[Profile::Weblogic::Domains] => Orawls::Domain[wlsDomain] => File[/data/install/] => File[/data/install/weblogic/weblogic_silent_install.xml] => Class[Orawls::Weblogic])

I have been using templates from your vagrant machine to define basic hiera defaults and manifest. Everything works until I add declare weblogic:domain. Please note, that I use install binaries locally, not remotelly
 
      include orawls::weblogic,bsu,domains
      include nodemanager,startwls

      class bsu{
        require orawls::weblogic
        $default_params = {}
        $bsu_instances = hiera('bsu_instances', {})
        create_resources('orawls::bsu',$bsu_instances, $default_params)
      }

      class opatch{
       require bsu
       $default_params = {}
       $opatch_instances = hiera('opatch_instances', {})
       create_resources('orawls::opatch',$opatch_instances, $default_params)
      }

      class domains{
              !!here is the problematic part, when i remove depedency to orawls::weblogic, the dependency           cycle dissappear!!!
    	  require orawls::weblogic, opatch  

    	  $default_params = {}
    	  $domain_instances = hiera('domain_instances', {})
    	  create_resources('orawls::domain',$domain_instances, $default_params)

    	  $wls_setting_instances = hiera('wls_setting_instances', {})
    	  create_resources('wls_setting',$wls_setting_instances, $default_params)
    	}

etc..

Thank you in advance
Ondrej

**Comment by biemond** [comment]
Hi, that is strange

I think this is the error File[/data/install/] => File[/data/install/weblogic/weblogic_silent_install.xml] 

Can you use the same install folder for both ( weblogic & domain ). I always do if defined file[...] and it will skip it the second time
when these install folders are not the same and one is a parent of the other then we will have a dependency error

Thanks

**Comment by xmatej** [comment]
Thank you for quick replay, 
it didn't help, unfortunatelly I was trying various combinations, the result is the same

Error: Could not apply complete catalog: Found 1 dependency cycle:
(Exec[install weblogic 1036] => Class[Orawls::Weblogic] => Class[Profile::Weblogic::Domains] => Orawls::Domain[wlsDomain] => File[/data/install] => File[/data/install/weblogic_silent_install.xml] => Exec[install weblogic 1036])

I am attaching dependency graph
![cycles8](https://cloud.githubusercontent.com/assets/5245390/6646589/bcc04508-c9c6-11e4-9dae-d52d7ccafc32.png)

**Comment by biemond** [comment]
Ok very strange.

can you test it against the latest orawls and also post your used config plus hiera config.
thanks

**Comment by xmatej** [comment]
Here is the config file

class profile::weblogic { 
 $wlsPreRequisities = [ htop, nmap, libcanberra-gtk2,PackageKit-gtk-module , liberation-sans-fonts, logstash , wireshark ]
 package { $wlsPreRequisities: ensure => "installed" }

#users definition start
#create group bea and user weblogic
 group { 'bea':
   ensure 	=> 'present',
   gid		=> 1000,
   before => User['weblogic']
 }
 user { 'weblogic':
   ensure 	=> 'present',
   uid		=> 1000,
   gid		=> 1000,
   home   => "/home/weblogic",
   managehome => true,
   before => Class["jdk7::urandomfix"]
 }
 
#users definition end

# instala java 
 $java_version        = hiera(profile::weblogic::java_version)
 $java_version_short  = hiera(profile::weblogic::java_version_short)
 
 #Download java repository
 wget::fetch { "java_binary":
      source      => "http://app-repo01.homecredit.net/pub/puppet/jdk-$java_version_short-linux-x64.tar.gz",
      destination => "/var/tmp/jdk_install/jdk-$java_version_short-linux-x64.tar.gz",
      timeout     => 0,
      verbose     => true,
      cache_dir   => '/var/cache/wget',
      before      => jdk7::install7["$java_version"]
       }
 
 jdk7::install7 { $java_version:
    version                => $java_version_short,
    fullVersion            => $java_version,
    x64                    => true,
    downloadDir            =>  "/var/tmp/jdk_download/",
    urandomJavaFix         => true,
    alternativesPriority   => 18000,
    sourcePath             => "/var/tmp/jdk_install/"
 }
 class { 'jdk7::urandomfix' : }

# Create link to current java in /opt/java 
 file {'/opt/java/':
  ensure => "link",
  target => "/usr/java/$java_version"
 }  

#Create weblogic directories
 file {'/opt/jks':
   ensure => "directory",
   mode => 644,
   owner => weblogic,
   group => bea
   } 

  Install weblogic binaries and patches  
  include orawls::weblogic,bsu,domains
  include nodemanager,startwls
  include userconfig,security,basic_config
  include datasources ,virtual_hosts,workmanagers, file_persistence,jms
  include pack_domain  
  
  class bsu{
    require orawls::weblogic
    $default_params = {}
    $bsu_instances = hiera('bsu_instances', {})
    create_resources('orawls::bsu',$bsu_instances, $default_params)
  }
  class fmw{
   require bsu
   $default_params = {}
   $fmw_installations = hiera('fmw_installations', {})
   create_resources('orawls::fmw',$fmw_installations, $default_params)
   }

  class opatch{
   require bsu
   $default_params = {}
   $opatch_instances = hiera('opatch_instances', {})
   create_resources('orawls::opatch',$opatch_instances, $default_params)
}
class domains{
	  require orawls::weblogic, opatch  
	  $default_params = {}
	  $domain_instances = hiera('domain_instances', {})
	  create_resources('orawls::domain',$domain_instances, $default_params)	
	  $wls_setting_instances = hiera('wls_setting_instances', {})
	  create_resources('wls_setting',$wls_setting_instances, $default_params)
	
	}

	class nodemanager {
	  require orawls::weblogic, domains
	  $default_params = {}
	  $nodemanager_instances = hiera('nodemanager_instances', {})
	  create_resources('orawls::nodemanager',$nodemanager_instances, $default_params)
	
	  $str_version  = hiera('wls_version')
	  $domains_path = hiera('wls_domains_dir')
	  $domain_name  = hiera('domain_name')
	
	  orautils::nodemanagerautostart{"autostart weblogic":
	    version                 => "${str_version}",
	    domain                  => $domain_name,
	    domainPath              => "${domains_path}/${domain_name}",
	    wlHome                  => hiera('wls_weblogic_home_dir'),
	    user                    => hiera('wls_os_user'),
	    jsseEnabled             => hiera('wls_jsse_enabled'             ,false),
	    customTrust             => hiera('wls_custom_trust'             ,false),
	    trustKeystoreFile       => hiera('wls_trust_keystore_file'      ,undef),
	    trustKeystorePassphrase => hiera('wls_trust_keystore_passphrase',undef),
	  }
	}
	
  class startwls {
	  require orawls::weblogic, domains,nodemanager
	
	  $default_params = {}
	  $control_instances = hiera('control_instances', {})
	  create_resources('orawls::control',$control_instances, $default_params)
	}

	class userconfig{
	  require orawls::weblogic, domains, nodemanager, startwls
	  $default_params = {}
	  $userconfig_instances = hiera('userconfig_instances', {})
	  create_resources('orawls::storeuserconfig',$userconfig_instances, $default_params)
	}

	class security{
	  require userconfig
	  $default_params = {}
	  $user_instances = hiera('user_instances', {})
	  create_resources('wls_user',$user_instances, $default_params)
	
	  $group_instances = hiera('group_instances', {})
	  create_resources('wls_group',$group_instances, $default_params)
	
	  $authentication_provider_instances = hiera('authentication_provider_instances', {})
	  create_resources('wls_authentication_provider',$authentication_provider_instances, $default_params)
	}

	class basic_config{
	  require security
	  $default_params = {}
	
	  $wls_domain_instances = hiera('wls_domain_instances', {})
	  create_resources('wls_domain',$wls_domain_instances, $default_params)
	
	  # subscribe on changes
	  $wls_adminserver_instances = hiera('wls_adminserver_instances', {})
	  create_resources('wls_adminserver',$wls_adminserver_instances, $default_params)
	
	  $machines_instances = hiera('machines_instances', {})
	  create_resources('wls_machine',$machines_instances, $default_params)
	
	  $server_instances = hiera('server_instances', {})
	  create_resources('wls_server',$server_instances, $default_params)
	
	  $server_channel_instances = hiera('server_channel_instances', {})
	  create_resources('wls_server_channel',$server_channel_instances, $default_params)
	
	  $cluster_instances = hiera('cluster_instances', {})
	  create_resources('wls_cluster',$cluster_instances, $default_params)
	
	  $coherence_cluster_instances = hiera('coherence_cluster_instances', {})
	  create_resources('wls_coherence_cluster',$coherence_cluster_instances, $default_params)
	
	  $server_template_instances = hiera('server_template_instances', {})
	  create_resources('wls_server_template',$server_template_instances, $default_params)
	
	  $dynamic_cluster_instances = hiera('dynamic_cluster_instances', {})
	  create_resources('wls_dynamic_cluster',$dynamic_cluster_instances, $default_params)
	
	}

	class datasources{
	  require basic_config
	  $default_params = {}
	  $datasource_instances = hiera('datasource_instances', {})
	  create_resources('wls_datasource',$datasource_instances, $default_params)
	}


	class virtual_hosts{
	  require datasources
	  $default_params = {}
	  $virtual_host_instances = hiera('virtual_host_instances', {})
	  create_resources('wls_virtual_host',$virtual_host_instances, $default_params)
	}

	class workmanagers{
	  require virtual_hosts
	  $default_params = {}
	
	  $workmanager_constraint_instances = hiera('workmanager_constraint_instances', {})
	  create_resources('wls_workmanager_constraint',$workmanager_constraint_instances, $default_params)
	
	  $workmanager_instances = hiera('workmanager_instances', {})
	  create_resources('wls_workmanager',$workmanager_instances, $default_params)
	}

	class file_persistence{
	  require workmanagers
	
	  $default_params = {}
	
	  $file_persistence_folders = hiera('file_persistence_folders', {})
	  create_resources('file',$file_persistence_folders, $default_params)
	
	  $file_persistence_store_instances = hiera('file_persistence_store_instances', {})
	  create_resources('wls_file_persistence_store',$file_persistence_store_instances, $default_params)
	}

	class jms{
	  require file_persistence
	
	  $default_params = {}
	  $jmsserver_instances = hiera('jmsserver_instances', {})
	  create_resources('wls_jmsserver',$jmsserver_instances, $default_params)
	
	  $jms_module_instances = hiera('jms_module_instances', {})
	  create_resources('wls_jms_module',$jms_module_instances, $default_params)
	
	  $jms_subdeployment_instances = hiera('jms_subdeployment_instances', {})
	  create_resources('wls_jms_subdeployment',$jms_subdeployment_instances, $default_params)
	
	  $jms_quota_instances = hiera('jms_quota_instances', {})
	  create_resources('wls_jms_quota',$jms_quota_instances, $default_params)
	
	  $jms_connection_factory_instances = hiera('jms_connection_factory_instances', {})
	  create_resources('wls_jms_connection_factory',$jms_connection_factory_instances, $default_params)
	
	  $jms_queue_instances = hiera('jms_queue_instances', {})
	  create_resources('wls_jms_queue',$jms_queue_instances, $default_params)
	
	  $jms_topic_instances = hiera('jms_topic_instances', {})
	  create_resources('wls_jms_topic',$jms_topic_instances, $default_params)
	
	  $foreign_server_instances = hiera('foreign_server_instances', {})
	  create_resources('wls_foreign_server',$foreign_server_instances, $default_params)
	
	  $foreign_server_object_instances = hiera('foreign_server_object_instances', {})
	  create_resources('wls_foreign_server_object',$foreign_server_object_instances, $default_params)
	
	  $safagent_instances = hiera('safagent_instances', {})
	  create_resources('wls_safagent',$safagent_instances, $default_params)
	
	  $saf_remote_context_instances = hiera('saf_remote_context_instances', {})
	  create_resources('wls_saf_remote_context',$saf_remote_context_instances, $default_params)
	
	  $saf_error_handler_instances = hiera('saf_error_handler_instances', {})
	  create_resources('wls_saf_error_handler',$saf_error_handler_instances, $default_params)
	
	  $saf_imported_destination_instances = hiera('saf_imported_destination_instances', {})
	  create_resources('wls_saf_imported_destination',$saf_imported_destination_instances, $default_params)
	
	  $saf_imported_destination_object_instances = hiera('saf_imported_destination_object_instances', {})
	  create_resources('wls_saf_imported_destination_object',$saf_imported_destination_object_instances, $default_params)
	}

class pack_domain{
	  require jms
	
	  $default_params = {}
	  $pack_domain_instances = hiera('pack_domain_instances', $default_params)
	  create_resources('orawls::packdomain',$pack_domain_instances, $default_params)
	}  
}

**Comment by xmatej** [comment]
here is the hiera file

---
orawls::weblogic::log_output:   true
logoutput:                     &logoutput                     true 

# global WebLogic vars
wls_oracle_base_home_dir: &wls_oracle_base_home_dir "/opt/oracle"
wls_weblogic_user:        &wls_weblogic_user        "weblogic"
wls_domains_dir:          &wls_domains_dir          '/var/fmw/domains'
wls_apps_dir:             &wls_apps_dir             '/var/fmw/applications'

# 10.3.6 settings
wls_weblogic_home_dir:    &wls_weblogic_home_dir    "/opt/oracle/middleware11g/wlserver_10.3"
wls_middleware_home_dir:  &wls_middleware_home_dir  "/opt/oracle/middleware11g"
wls_version:              &wls_version              1036

# global OS vars
wls_os_user:              &wls_os_user              "weblogic"
wls_os_group:             &wls_os_group             "bea"
wls_download_dir:         &wls_download_dir         "/data/install"
wls_source:               &wls_source               "/var/tmp/binaries"
wls_jdk_home_dir:         &wls_jdk_home_dir         "/opt/java/"
wls_log_dir:              &wls_log_dir              "/var/log/fmw"
wls_weblogic_user:        &wls_weblogic_user        "weblogic"
wls_weblogic_home_dir:    &wls_weblogic_home_dir    "/opt/oracle/middleware11g/wlserver_10.3"
wls_middleware_home_dir:  &wls_middleware_home_dir  "/opt/oracle/middleware11g"


#WebLogic installation variables
orawls::weblogic::version:              *wls_version
orawls::weblogic::filename:             "wls1036_generic.jar"

orawls::weblogic::middleware_home_dir:  *wls_middleware_home_dir
orawls::weblogic::log_output:           false

# hiera default anchors
orawls::weblogic::jdk_home_dir:         *wls_jdk_home_dir
orawls::weblogic::oracle_base_home_dir: *wls_oracle_base_home_dir
orawls::weblogic::os_user:              *wls_os_user
orawls::weblogic::os_group:             *wls_os_group
orawls::weblogic::download_dir:         *wls_download_dir
orawls::weblogic::source:               *wls_source
orawls::weblogic::remote_file:          false
orawls::weblogic::wls_domains_dir:      *wls_domains_dir
orawls::weblogic::wls_apps_dir:         *wls_apps_dir

#domain
# when you have just one domain on a server
domain_name:                "puppet_domain"
domain_adminserver:         "puppet_admin"
domain_adminserver_address: "10.129.16.27"
domain_adminserver_port:    8001
domain_nodemanager_port:    5556
domain_wls_password:        &domain_wls_password "weblogic1"
domain_user_config_file:    "/home/oracle/oracle-Wls1036-WebLogicConfig.properties"
domain_user_key_file:       "/home/oracle/oracle-Wls1036-WebLogicKey.properties"

# create a standard domain
domain_instances:
  'wlsDomain':
     domain_template:          "standard"
     development_mode:         false
     log_output:               *logoutput
     
wls_setting_instances:
  'default':
    user:               *wls_os_user
    weblogic_home_dir:  *wls_weblogic_home_dir
    connect_url:        "t3://10.129.16.27:8001"
    weblogic_user:      *wls_weblogic_user
    weblogic_password:  *domain_wls_password
    require:            Orawls::Domain[wlsDomain]

# pack domains
pack_domain_instances:
  'wlsDomain':
     log_output:               *logoutput

# create and startup the nodemanager
nodemanager_instances:
  'nodemanager':
     log_output:           *logoutput
     nodemanager_address:  "10.129.16.27"


# startup adminserver for extra configuration
control_instances:
  'startWLSAdminServer':
     domain_name:          "puppet_domain"
     server_type:          'admin'
     target:               'Server'
     server:               'puppet_admin'
     action:               'start'
     log_output:           *logoutput

**Comment by biemond** [comment]
Hi,

by the way did you set override_weblogic_user in facter because 'oracle' as os user is the default. If you don't do this, puppet cannot detect an existing weblogic installation and will try to install it again.

In a module /<MODULE>/facts.d/
or
set FACTER_override_weblogic_user=weblogic on the client 
or 
add a txt file on the puppet nodes in 
/etc/facter/facts.d/ # Puppet Open Source
/etc/puppetlabs/facter/facts.d/ # Puppet Enterprise

**Comment by biemond** [comment]
found the bug

I changed all directory creation actions to a custom type and it worked because I was using the same tmp folder in my jdk install module, In this case it already exists else in domain.pp it will be the first time this file type was defined

will fix it.

**Comment by biemond** [comment]
Can you try it with the latest version located on github.

**Comment by xmatej** [comment]
Hi Edwin, the problem is gone with the latest release.
Thank you very much!
