### ISSUE TITLE
Hide output from custom types

### ISSUE THREAD

**Issue by adamjk-dev** [biemond/biemond-orawls#143]
Is there a way to force output to not be shown when using the custom types, such as the wls_setting: https://github.com/biemond/biemond-orawls#wls_setting

```
wls_setting { 'default':
    user              => $wls_os_user,
    weblogic_home_dir => $weblogic_home_dir,
    connect_url       => "t3://${admin_server_address}:${$admin_server_port}",
    weblogic_user     => $wls_os_user,
    weblogic_password => $wls_user_password,
  }
```

This block outputs the password above, which we don't want in our logs etc. I wasn't sure if there was some way to quiet the output since there is no log_output variable etc.

**Comment by biemond** [comment]
Ok,

you mean this 

==> admin: Notice: /Stage[main]/Domains/Orawls::Domain[Wls1213]/Yaml_setting[domain Wls1213]/ensure: created
==> admin: Notice: /Stage[main]/Domains/Wls_setting[default]/user: defined 'user' as 'oracle'
==> admin: Notice: /Stage[main]/Domains/Wls_setting[default]/weblogic_home_dir: defined 'weblogic_home_dir' as '/opt/oracle/middleware12c/wlserver'
==> admin: Notice: /Stage[main]/Domains/Wls_setting[default]/weblogic_user: defined 'weblogic_user' as 'weblogic'
==> admin: Notice: /Stage[main]/Domains/Wls_setting[default]/connect_url: defined 'connect_url' as 't3://10.10.10.10:7001'
==> admin: Notice: /Stage[main]/Domains/Wls_setting[default]/weblogic_password: defined 'weblogic_password' as 'weblogic1'

Or did you find more password output.

I need to find out what code is generating this output. it looks like it is the yaml gem. Maybe we can suppress  it or encrypt it with the standard ruby gems of the puppet client

**Comment by adamjk-dev** [comment]
You are correct, I didn't want to paste my output since it has a more sensitive user and password. I thought I saw more the other day, but I just grep'd over my output from a whole WL Admin server run, and that was the only output I saw from that password. So, right now, I think that is the only place.

Yeah, if we could suppress that it would be great, I can't really have this output in the logs.

**Comment by biemond** [comment]
I got a workaround because I cannot fix it, it is output generated by puppet and a type.

you can set the loglevel to debug, this way it will only show up when you set puppet agent or apply loglevel to debug and off course when the wls_setting is created or updated. in other cases you won't see a thing in the output.

      'Wls11gSetting':
        user:               *wls_os_user
        weblogic_home_dir:  *wls_weblogic_home_dir
        connect_url:        "t3://%{hiera('domain_adminserver_address')}:7011"
        weblogic_user:      *wls_weblogic_user
        weblogic_password:  *domain_wls_password
        loglevel:           'debug'  <----

or use loglevel =>  'debug'

**Comment by nanliu** [comment]
I provided an example of redacting the password:

```
Notice: /Stage[main]/Fusion::Weblogic::Domains/Wls_setting[default]/weblogic_password: current_value [old password redacted], should be [new password redacted] (noop)
Notice: Class[Fusion::Weblogic::Domains]: Would have triggered 'refresh' from 1 events
```

I looked at easytype and it might be possible to have a generic password type.

**Comment by adamjk-dev** [comment]
Oh, so will it never output the password now? Can I close this issue?

**Comment by joewimmer** [comment]
The log level solution wasn't the best bc we found some that were error'ing out and showing the password in plain text.  So i made the password and environment variable and sourced it in the cmd. 
eg:

```
command  =>  "${javaCommand} ${download_dir}/${title}storeUserConfig.py  \$WL_PASSWORD",
environment => ["CLASSPATH=${weblogic_home_dir}/server/lib/weblogic.jar", "JAVA_HOME=${jdk_home_dir}", "WL_PASSWORD=${weblogic_password}"],
```

No more plain text passwords
