### ISSUE TITLE
OSB and ESS

### ISSUE THREAD

**Issue by xmatej** [biemond/biemond-orawls#145]
Hi Edmond,
I have request from our development team to install OSB 12.1.3 with enabled ESS in separate cluster. 
I´ve found in the assignOsbSoaBpmBamToClusters_1213.py.erb, that you have to install and enable SOA package to setup soaServerGroup = ["SOA-MGD-SVRS","ESS-MGD-SVRS"] . 

Is there any way, how to enable ESS and assign it to cluster, without installing soa package with your module?

Thanks
Ondrej

**Comment by biemond** [comment]
Hi Ondrej 

No that is not possible for now and I will add this fix to the soa domain template and the 12.1.3 fmwcluster scripts.

Thanks

**Comment by xmatej** [comment]
Hi Edwin,
thank you for the respond. Currently I use the osb domain template. It would be great to have the possibility to specify ESSClusterName and have the ESS plugins in enterprise manager etc. enabled in osb template as figured out below
![osb](https://cloud.githubusercontent.com/assets/5245390/7175793/cd3bbb58-e418-11e4-9980-c99305201da8.png)

Thank you very much

**Comment by biemond** [comment]
I did the first part by adding ESS to the osb domain option ( check the orawls git repo), next part is changing this to your own OSB & ESS cluster.

Thanks

**Comment by xmatej** [comment]
Hi Edwin,

Thanks a lot,  I will check it soon.
Can I ask you please, if there are some parameters , e.g. WebLogic Plug-In Enabled: yes ,  which are not covered in your module, we need to setup. Would you prefer from us ( i mean me and my colleagues, who works with middleware in our company) to contribute into you project, which seems me more conceptual to me, or shall we made the final domain settings outside of orawls module? I am talking especially about the small changes as mentioned missing parameters...

Thanks
Take care.

Ondrej Matejicek
OPS Middleware TI Teamleader

**Comment by biemond** [comment]
Just send me some pull request. you will get the credits and I will know what you exactly mean to achieve.

Thanks

**Comment by biemond** [comment]
It looks like the ESS cluster part is now also working.

you can check this vagrant box https://github.com/biemond/biemond-orawls-vagrant-12.1.3-infra-osb

**Comment by xmatej** [comment]
Hi,

Thanks, I’ve just tested it and it works Great. Thank you very much.

May I ask you, why the nodemanager.properties customizations are not performed for 1213 version

I mean following part in /manifests/nodemanager.pp
# nodemanager is part of the domain creation

if ( $version == 1111 or $version == 1036 or $version == 1211 ){
    file { "nodemanager.properties ux ${title}":
      ensure  => present

Thanks
Ondrej Matejicek
OPS Middleware TI Teamleader

**Comment by biemond** [comment]
Nice,

With 12.1.2 and higher this is done in the domain.pp manifest , with these versions the node manager is now part of the domain , every domain have its own and older ones are part of the middleware home.

**Comment by xmatej** [comment]
I see,

The problem is , that when I have a custom identity defined for the nodemanager, the nodemanager.properties file on the remote node after copy_domain is not changed to correct value.
I´ve seen this behavior on the biemond-orawls-vagrant-12.1.3<https://github.com/biemond/biemond-orawls-vagrant-12.1.3> as well. When you check nodemanager.properties on the node1 machine there is defined in hiera
custom_identity_alias:                 'node1'
custom_identity_keystore_filename:     '/vagrant/identity_node1.jks'
but in the file nodemanager.properties.
CustomIdentityAlias=admin
CustomIdentityKeyStoreFileName=/vagrant/identity_admin.jks

Ondrej Matejicek
OPS Middleware TI Teamleader

**Comment by biemond** [comment]
Oh, I didn't think about that one.  

you found a bug :+1: I will fix it.

**Comment by biemond** [comment]
I fixed the nodemanager bug and moved it from the domain
