### ISSUE TITLE
BSU patch fails with nologin shell for $os_user

### ISSUE THREAD

**Issue by uberfirestone** [biemond/biemond-orawls#151]
Applying a BSU-style patch to Weblogic server (10.3.6 in my case) does not work when the system account that it's supposed to run under has a nologin shell. 

I was able to work around by setting $os_user to root (for this class only), then chowning the middleware directory to the desired account after the patch is applied.

**Comment by biemond** [comment]
ok,

Root and Chown is not a real nice way to do this. How do you do this when you need to do this by hand?

Thanks

**Comment by uberfirestone** [comment]
My command would look something like:

[sysadm@host ~]$ sudo su -s /bin/bash - oracle /opt/oracle/middleware/utils/bsu/bsu.sh -install -options -here

where 'oracle' is the owner of the weblogic components

**Comment by biemond** [comment]
Thanks for the info

I added shell to all the Linux su -c statement, Can you try it yourself  ( the github repo )  and see if it works for you.

Cheers.

**Comment by uberfirestone** [comment]
That did the trick. Thanks!
