### ISSUE TITLE
Dynamically adding servers to clusters

### ISSUE THREAD

**Issue by BasLangenberg** [biemond/biemond-orawls#157]
Hi Edwin,

First of all, thank you **very** much for this module. It saved tons of work. :-)

I'm running into a problem with the wls_cluster type. If I understand it correctly, I should pass a list of wls_server objects to it in order to add them to the cluster. The problem is that I do not know exactly what the complete list of wls_server objects is.

More details:
- The WLS environments are provisioned in the cloud, we do not know the ip address / server hostnames up front
- The environment should be able to scale horizontally, so if I provision a new server, it should add itself to the domain
- The new server adds three mservers which need to be added to the cluster as per our standards. In every Puppet run, the node only knows of it's own mservers

I do not want to hard code the cluster nodes in a Hiera file, but this might be a last resort. A possible solution I have in mind is to edit the orawls module to add the cluster name to the wls_server's note section, and query this field in order to add or not add it to the cluster. 

I'm not sure if this is the way to go, as I feel like it is a dirty hack. Do you have any light to shine on this particular use case?

Before I forget, dynamic clustering is unfortunately not an option.

Thank you.

Regards,
Bas

**Comment by biemond** [comment]
Hi Bas, 

interesting, 

For orawls everything is mostly done on the adminserver
but what you can do is start with creating an adminserver, nodemanager, server and cluster with this server on the admin node.

On the nodes you only need to know the adminserver ip address after that you can install the software , copy domain and start the nodemanager.

I think you need to do something with the global facts (don't know the exact name ) , Every domain wls node should add itself to this global fact.

On the adminserver these should be picked up  by the next run and use this array used to create extra machines, servers and add them as servers to the existing cluster.

It is model driven so you can run it many times and it should pick up the changes,

Thanks

**Comment by BasLangenberg** [comment]
Hi Edwin,

Interesting approach. I fail to understand however how this should work. How can nodes be aware of these 'global facts'?

We're using PE here and there is no access to the actual master. I am working with the responsible team to get information about the availability of PuppetDB and if it is an option, as I can query for specific values. I try to use an unique environment fact which I pass from Hiera to enable this.

I did do some tinkering with your wls_server and wls_cluster types yesterday and 'misusing' the notes field works. I however run in a similar problem when trying to setup the JDBC. I need to modify your types to work around this in the same way.

I've talked to my manager and we agree that I can spend some time to forward you all compatible / globally usable changes in the form of pull requests, so you can expect these in a month or so. I made some other changes next to the ones I did for this particular challenge as well.

It seems that Puppet is a complex beast when you are trying to manage something more complex than a httpd server or ntp. :-)

Thanks,
Bas

**Comment by biemond** [comment]
Hi,

Very nice and you got PE. This will be an interesting and very wanted use case.

I mean exported resources like 
Resources are declared with the special @@ notation, which marks them as exported
so that they are not applied to the node where they are declared

like they do with haproxy https://github.com/puppetlabs/puppetlabs-haproxy

First export the resource for a balancermember:

    @@haproxy::balancermember { 'haproxy':
      listening_service => 'puppet00',
      ports             => '8140',
      server_names      => $::hostname,
      ipaddresses       => $::ipaddress,
      options           => 'check',
    }

Then collect the resource on a load balancer:

    Haproxy::Balancermember <<| listening_service == 'puppet00' |>>

Then create the resource for multiple balancermembers at once:

    haproxy::balancermember { 'haproxy':
      listening_service => 'puppet00',
      ports             => '8140',
      server_names      => ['server01', 'server02'],
      ipaddresses       => ['192.168.56.200', '192.168.56.201'],
      options           => 'check',
    }

This should also be possible and easier with puppetdb

Cheers

**Comment by BasLangenberg** [comment]
Hi Edwin,

Apologies for the late reply. I was on leave due to the birth of my daughter. :-) (Which is a bit more interesting than Puppet)

I wrote and implemented the workaround as discussed. I'm using the notes field in the server configuration to indicate which resources should be deployed to it, or if it should belong to a cluster. Although it is a hack, it does work for us.

As this is probably only a thing I am using on this particular project, I should get this fixed and rewrite this to be using PuppetDB in a later iteration.

I'll close the request, but if you are interested in my code, let me know.

Thanks again!

Bas

**Comment by biemond** [comment]
congrats :+1:  and thanks.

very interested, just send me a pull request on this module or at one of the vagrant boxes so I know what you did, this way it is documented and it will inspire me 

Cheers
