### ISSUE TITLE
JMS Queue forwarddelay attribute.

### ISSUE THREAD

**Issue by robh007** [biemond/biemond-orawls#158]
I've found what I think is an issue after an additional attribute was introduced on the JMS_QUEUE defined type. The attribute forwarddelay is only available on a distributed queue so when you have a normal queue i.e. distributed = '0' you get an error creating the JMS queue . forwarddelay gets set by default to -1. I may have a look at changing the WLST code and submit a PR. 

below is the output from the failed queue creation.

Debug: Successfully connected to Admin Server 'AdminServer' that belongs to domain 'squads'.

Debug:

Debug: Warning: An insecure protocol was used to connect to the

Debug: server. To ensure on-the-wire security, the SSL port or

Debug: Admin port should be used instead.

Debug:

Debug: wls:/squads/serverConfig>

Debug: Starting an edit session ...

Debug: Started edit session, please be sure to save and activate your

Debug: changes once you are done.

Debug: ForwardDelay

Debug: Unexpected error: exceptions.AttributeError

Debug: Discarded all your changes successfully.

Debug: Edit session has been stopped successfully.

Debug: ~~~~COMMAND FAILED~~~~

**Comment by biemond** [comment]
Ok,

That makes sense or does it already crash on the index script?

we should remove the default -1
https://github.com/biemond/biemond-orawls/blob/master/lib/puppet/type/wls_jms_queue/forwarddelay.rb#L5

Then you just can remove it from the properties.

the create script 

      if forwarddelay: 
         print "ForwardDelay"
         cmo.setForwardDelay( int(forwarddelay))

**Comment by robh007** [comment]
I've just issued a PR to remove the default code from the puppet type. Cheers Rob.

**Comment by robh007** [comment]
I think they maybe an issue on the index to because the attribute is hardcoded and doesn't exist so the next puppet run hangs and then fails on the index. I'll take a look later or it may get tomorrow now. But the initial fix is working.


This is in the index.py.erb 

def queue(token,token2,location,distributed):
    cd(location)
    jndiname      = get('JNDIName') 
    forwardDelay  = get('ForwardDelay')

**Comment by biemond** [comment]
Ok ,

let's give it a default value like ''
and do a try except around it 

I will do it now

thanks

**Comment by biemond** [comment]
I made a fix , can you try it again

**Comment by robh007** [comment]
Cheers Edwin, I've tested and initial puppet run works and creates WLS configuration. Subsequent puppet runs function fine and no longer report errors with the forwarddelay attribute not existing.

**Comment by biemond** [comment]
Thanks,

Also added a normal queue to my test cases so I will notice this sooner.
