### ISSUE TITLE
SSL Enabled Not Checked in AdminServer

### ISSUE THREAD

**Issue by dblaisdell** [biemond/biemond-orawls#162]
As a security minded user, I would like to enable SSL and disable the primary listen port for an Admin Server. However, the SSLEnabled property is not being set in the Admin server.

```
wls_server {'AdminServer':
    ensure                                => 'present',
    listenaddress                         => $admin_server_address,
    listenport                            => '7001',
    machine                               => 'LocalMachine',
    sslenabled                            => '1',
    sslhostnameverificationignored        => '1',
    ssllistenport                         => '7003',
    two_way_ssl                           => '0',
    client_certificate_enforced           => '0',
    jsseenabled                           => '1',
    custom_identity                       => '1',
    custom_identity_alias                 => 'tiaa-cloud-wildcard',
    custom_identity_keystore_filename     => '/opt/java/latest/jre/lib/security/cacerts',
    custom_identity_keystore_passphrase   => 'changeit',
    custom_identity_privatekey_passphrase => 'changeit',
    trust_keystore_file                   => '/opt/java/latest/jre/lib/security/cacerts',
    trust_keystore_passphrase             => 'changeit',
    max_message_size                      => '25000000',
  }
```

This is the debug output...
```
Debug: This Exception occurred at Fri May 22 14:15:00 EDT 2015.

Debug: javax.naming.CommunicationException [Root exception is java.net.ConnectException: t3://10.239.133.111:7001: Destination 10.239.133.111, 7001 unreachable; nested exception is:

Debug:  java.net.ConnectException: Connection refused; No available router to destination]

Debug: wls:/offline>

Debug: You will need to be connected to a running server to execute this command

Debug:

Debug:

Debug: You will need to be connected to a running server to execute this command

Debug:

Debug: Error: No domain or domain template has been read.

Debug: Error: get() cannot be applied at this point of path

Debug: Unexpected error: exceptions.AttributeError
```

**Comment by dblaisdell** [comment]
FYI, this is with 12.1.2

**Comment by biemond** [comment]
Ok thanks for reporting this.

I will take a look at it.
will let you know

Thanks Edwin

**Comment by biemond** [comment]
I cannot reproduce it 

I used these settings, with and without the log parameters.

So make sure you have the latest version of orawls and execute the modify script yourself (step by step ) in WLST so we know where it goes wrong.

thanks

      'AdminServer':
        ensure:                                'present'
        arguments:
               - *server_vm_args_permsize
               - *server_vm_args_max_permsize
               - *server_vm_args_memory
               - *server_vm_args_max_memory
               - '-Dweblogic.Stdout=/var/log/weblogic/AdminServer.out'
               - '-Dweblogic.Stderr=/var/log/weblogic/AdminServer_err.out'
        listenaddress:                         *domain_adminserver_address
        listenport:                            '7001'
        machine:                               'LocalMachine'
        max_message_size:                      '25000000'
        sslenabled:                            '1'
        ssllistenport:                         '7002'
        sslhostnameverificationignored:        '1'
        two_way_ssl:                           '0'
        client_certificate_enforced:           '0'
        jsseenabled:                           '1'
        custom_identity:                       '1'
        custom_identity_keystore_filename:     '/vagrant/identity_admin.jks'
        custom_identity_keystore_passphrase:   'welcome'
        custom_identity_alias:                 'admin'
        custom_identity_privatekey_passphrase: 'welcome'
        trust_keystore_file:                   *wls_trust_keystore_file
        trust_keystore_passphrase:             *wls_trust_keystore_passphrase
        # logfilename:                           '/var/log/weblogic/AdminServer.log'
        # log_datasource_filename:               '/var/log/weblogic/AdminServer_datasource.log'
        # log_file_min_size:                     '2000'
        # log_filecount:                         '10'
        # log_number_of_files_limited:           '1'
        # log_rotate_logon_startup:              '1'
        # log_rotationtype:                      'bySize'
        # log_http_filename:                     '/var/log/weblogic/AdminServer_access.log'
        # log_http_format_type:                  'extended'
        # log_http_format:                       'date time x-XForwardedFor s-ip cs-method cs-uri x-SOAPAction sc-status bytes time-taken x-UserAgent'
        # tunnelingenabled:                      '0'

**Comment by dblaisdell** [comment]
USER ERROR.

Had a non filtered spaceship operator running out of order.

Orawls::Control<| |> -> Wls_server['AdminServer']  works like a champ.
