### ISSUE TITLE
Feature Request: ListenPortEnable

### ISSUE THREAD

**Issue by dblaisdell** [biemond/biemond-orawls#163]
As a security concious user, I would like to disable the ListenPort, in order to promote SSL everywhere. However, I do not see an available option as part of wls_server configuration.

**Comment by biemond** [comment]
Thanks 

I will add a parameter listenportenabled ( with '1' as default  or '0' ) to wls_server resource type and this execute this in wlst 

    set('ListenPortEnabled','False')

**Comment by biemond** [comment]
I was thinking about this and this will probably only work when the adminserver still uses the normal listenport. I need to set wls_settings to t3:/xxx:7001 and after this I can disable the listenport but then I probably cannot log-on anymore ( I need to use t3s:/xxx:7002 ).  When we only disable the managed servers listenport then it will work.

So for the adminserver I maybe need to change the domain script and check all the manifests and types which do something with t3 protocol.

I will do some testing

cheers

**Comment by biemond** [comment]
I got it working

added new parameter adminserver_ssl_port on domain.pp manifest

plus wls_setting resource type now supports t3s with custom trust

    wls_setting_instances:
      'default':
        user:                      *wls_os_user
        weblogic_home_dir:         *wls_weblogic_home_dir
        connect_url:               "t3s://%{hiera('domain_adminserver_address')}:7002"
        weblogic_user:             *wls_weblogic_user
        weblogic_password:         *domain_wls_password
        custom_trust:              *wls_custom_trust
        trust_keystore_file:       *wls_trust_keystore_file
        trust_keystore_passphrase: *wls_trust_keystore_passphrase

After this you can disable the listenport with wls_server by settings this parameter listenportenabled = '0'

For a full working example see this 
https://github.com/biemond/biemond-orawls-vagrant-12.1.3

cheers
