### ISSUE TITLE
JDBC Persistent Store Support

### ISSUE THREAD

**Issue by bcornies** [biemond/biemond-orawls#167]
I see that configuration for File Persistent Stores is supported (and works well), but I can't seem to find anything in your module that supports JDBC Persistent Store configuration.

If it isn't support, I'm willing to do the work and submit a pull request.

**Comment by biemond** [comment]
Yeah, you are right and highly appreciated if you can send me a pull request

Thanks

**Comment by biemond** [comment]
it is now supported
