### ISSUE TITLE
Problem invoking WLST - java.io.FileNotFoundException: /home/oracle/domain_d_test_domain.py 

### ISSUE THREAD

**Issue by aevers1967** [biemond/biemond-orawls#178]
I am using release v1.0.35

During creation of the domain using domain.pp, i get the following error:  Problem invoking WLST - java.io.FileNotFoundException: /home/oracle/domain_d_test_domain.py (No such file or directory)

I see that the python script is created using the path "${download_dir}/domain_${domain_name}.py"  (domain.pp line 363   example: /opt/install/domain_d_test_domain.py

However when the  above script is executed  using  wlst.sh (domain.pp line 460) only the script is used as parameter.  In my environment the domain_d_test_domain.py script cannot be found!

Should the line 460 of domain.pp not be changed from:       
command     => "${wlstPath}/wlst.sh domain_${domain_name}.py",

to

command     => "${wlstPath}/wlst.sh ${download_dir}/domain_${domain_name}.py",

**Comment by biemond** [comment]
Let's see 

strange because I do a cwd in the exec  to the download folder.
but maybe there is some permission issue and redirect back to the home folder

do you switch install folders and what are the permissions of the directories 

    # create domain
    exec { "execwlst ${domain_name} ${title}":
      command     => "${wlstPath}/wlst.sh domain_${domain_name}.py",
      environment => ["JAVA_HOME=${jdk_home_dir}"],
      unless      => "/usr/bin/test -e ${domain_dir}",
      creates     => $domain_dir,
      cwd         => $download_dir,
      require     => [File["domain.py ${domain_name} ${title}"],
                      File["${download_dir}/utils.py"],
                      File[$domains_dir],],
      timeout     => 0,
      path        => $exec_path,
      user        => $os_user,
      group       => $os_group,
    }

also see in the domain py script I do 

    execfile('<%= @download_dir %>/utils.py')

So your wanted change won't hurt. :+1:

**Comment by aevers1967** [comment]
Thanks for the feedback.  There probably something wrong with permissions at my environment.  No code changes are needed.
