### ISSUE TITLE
dependency easy_type repo missing

### ISSUE THREAD

**Issue by nanliu** [biemond/biemond-orawls#179]
Not sure what happened to https://github.com/hajee/easy_type repo. @hajee ?

**Comment by hajee** [comment]
@biemond check pr #177

**Comment by biemond** [comment]
Done thanks for reporting this

**Comment by nanliu** [comment]
@hajee, is there a particular reason this dependency is no longer available on github? thanks for the update.

**Comment by hajee** [comment]
@nanliu Contact me by email hajee@moretIA.com
