### ISSUE TITLE
git tag v.s. puppet metadata.json

### ISSUE THREAD

**Issue by nanliu** [biemond/biemond-orawls#187]
So looks like git tag and metadata.json are not in sync? metadata.json shows 1.0.37 while git tag is 1.0.36?

https://github.com/biemond/biemond-orawls/commits/master/metadata.json
https://github.com/biemond/biemond-orawls/releases

**Comment by biemond** [comment]
yeah I pushed new version so all new changes are under 1.0.37 and not under 1.0.36 ( this version is final now )
the github release zip and forge both contains version 1.0.36 so these are ok.

**Comment by nanliu** [comment]
Oh, the file is indicating the next target version and not the released version. Sorry, my mistake.
