### ISSUE TITLE
Java returned 255 instead of one of [0]

### ISSUE THREAD

**Issue by BurningTheSky** [biemond/biemond-orawls#210]
Hi, I am trying to do the most basic of the WLS installs and am getting the error below. Any suggestions would be greatly appreciated:

Notice: /Stage[main]/Orawls::Weblogic/Wls_directory_structure[weblogic structure 1212]/ensure: defined 'ensure' as 'present'
Notice: /Stage[main]/Orawls::Weblogic/File[/data/install/wls_121200.jar]/ensure: defined content as '{md5}66380e1b5143949f0169e9b62e9272fa'
Notice: /Stage[main]/Orawls::Weblogic/File[/data/install/weblogic_silent_install.xml]/ensure: created
Notice: /Stage[main]/Orawls::Weblogic/Exec[install weblogic 1212]/returns: Extracting files.........
Notice: /Stage[main]/Orawls::Weblogic/Exec[install weblogic 1212]/returns: The OpenJDK JVM is not supported on this platform.
Notice: /Stage[main]/Orawls::Weblogic/Exec[install weblogic 1212]/returns: The Oracle Universal Installer failed.  Exiting.
Error: java  -Xmx1024m -Djava.io.tmpdir=/tmp -jar /data/install/wls_121200.jar -silent -responseFile /data/install/weblogic_silent_install.xml  -invPtrLoc /etc/oraInst.loc -ignoreSysPrereqs returned 255 instead of one of [0]
Error: /Stage[main]/Orawls::Weblogic/Exec[install weblogic 1212]/returns: change from notrun to 0 failed: java  -Xmx1024m -Djava.io.tmpdir=/tmp -jar /data/install/wls_121200.jar -silent -responseFile /data/install/weblogic_silent_install.xml  -invPtrLoc /etc/oraInst.loc -ignoreSysPrereqs returned 255 instead of one of [0]

Java is installed:
# java -version
openjdk version "1.8.0_51"
OpenJDK Runtime Environment (build 1.8.0_51-b16)
OpenJDK 64-Bit Server VM (build 25.51-b03, mixed mode)

And I set the jdk in line with this:
# which java
/usr/bin/java

This is the class I am using to try to install WLS:
        class{'orawls::weblogic':
                version              => 1212,                       # 1036|1211|1212|1213
                filename             => 'wls_121200.jar',           # wls1036_generic.jar|wls1211_generic.jar|wls_121200.jar
                jdk_home_dir         => '/usr/bin/java',
                oracle_base_home_dir => "/opt/oracle",
                middleware_home_dir  => "/opt/oracle/middleware12c",
                weblogic_home_dir    => "/opt/oracle/middleware12c/wlserver",
                os_user              => "oracle",
                os_group             => "dba",
                download_dir         => "/data/install",
                source               => 'puppet:///modules/orawls/',                 # /vagrant | /mnt |
                log_output           => true,
        }

**Comment by biemond** [comment]
Hi Sky,

you are almost there :+1: 
Notice: /Stage[main]/Orawls::Weblogic/Exec[install weblogic 1212]/returns: The OpenJDK JVM is not supported on this platform.

just switch to the oracle jdk and it should work

Cheers Edwin

**Comment by BurningTheSky** [comment]
Perfect, thanks Edwin! Now for the fun of all the domain config etc
