### ISSUE TITLE
undefined method `sort' for :absent:Symbol when managing data sources

### ISSUE THREAD

**Issue by alexjfisher** [biemond/biemond-orawls#212]
Hi

I think I've found a bug.  To reproduce, use puppet to
1.  Create a wls_server
2.  Create some wls_datasources that target the server

This works.  Then, delete the server using the weblogic console and rerun puppet.

```
Error: undefined method `sort' for :absent:Symbol
Error: /Stage[main]/Profile::Oracle::Os_wls::Data_sources/Wls_datasource[MyDS]/target: change from absent to MyServer failed: undefined method `sort' for :absent:Symbol
```

When the server was deleted, the datasource no longer has any targets.  When puppet is rerun, it recreates the server and then correctly tries to reconfigure the datasources.  But, the module code seems to get upset ordering a list of empty targets??

Hope this makes some sort of sense! :)

Kind Regards,
Alex

**Comment by alexjfisher** [comment]
Should have probably mentioned what platform I'm using...
Puppet 3.7.5 (parser = future) on OracleLinux 6 (ie ruby 1.8.7?)

Thanks,
Alex

**Comment by biemond** [comment]
Ok thanks,

So the index wls_datasource phase goes wrong in WLST when there no targets or when it contains a not existing target. or in Ruby on the target attribute https://github.com/biemond/biemond-orawls/blob/master/lib/puppet/type/shared/target.rb#L12

can you do `sudo puppet wls_datasource --debug --trace`

this will show you what puppet code crashes or you see at least the wlst output.

Thanks

**Comment by alexjfisher** [comment]
Did you mean "puppet **resource** wls_datasource..."?  That doesn't produce the error though.

It only goes wrong with puppet apply, but interestingly it appears the configuration *is* updated (datasource re-targeted correctly) despite the error.  A second run of puppet then completes with no errors.

I can also trigger the error when using --noop.  Here is the ruby trace...
```
Error: undefined method `sort' for :absent:Symbol
/var/lib/puppet/lib/puppet/type/shared/target.rb:13:in `insync?'
/usr/lib/ruby/site_ruby/1.8/puppet/property.rb:314:in `safe_insync?'
/usr/lib/ruby/site_ruby/1.8/puppet/transaction/resource_harness.rb:117:in `sync_if_needed'
/usr/lib/ruby/site_ruby/1.8/puppet/transaction/resource_harness.rb:89:in `perform_changes'
/usr/lib/ruby/site_ruby/1.8/puppet/transaction/resource_harness.rb:88:in `each'
/usr/lib/ruby/site_ruby/1.8/puppet/transaction/resource_harness.rb:88:in `perform_changes'
/usr/lib/ruby/site_ruby/1.8/puppet/transaction/resource_harness.rb:20:in `evaluate'
/usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:204:in `apply'
/usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:217:in `eval_resource'
/usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:147:in `call'
/usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:147:in `evaluate'
/usr/lib/ruby/site_ruby/1.8/puppet/util.rb:327:in `thinmark'
/usr/lib/ruby/1.8/benchmark.rb:308:in `realtime'
/usr/lib/ruby/site_ruby/1.8/puppet/util.rb:326:in `thinmark'
/usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:147:in `evaluate'
/usr/lib/ruby/site_ruby/1.8/puppet/graph/relationship_graph.rb:118:in `traverse'
/usr/lib/ruby/site_ruby/1.8/puppet/transaction.rb:138:in `evaluate'
/usr/lib/ruby/site_ruby/1.8/puppet/resource/catalog.rb:169:in `apply'
/usr/lib/ruby/site_ruby/1.8/puppet/util/log.rb:149:in `with_destination'
/usr/lib/ruby/site_ruby/1.8/puppet/transaction/report.rb:112:in `as_logging_destination'
/usr/lib/ruby/site_ruby/1.8/puppet/resource/catalog.rb:168:in `apply'
/usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:120:in `apply_catalog'
/usr/lib/ruby/site_ruby/1.8/puppet/util.rb:161:in `benchmark'
/usr/lib/ruby/1.8/benchmark.rb:308:in `realtime'
/usr/lib/ruby/site_ruby/1.8/puppet/util.rb:160:in `benchmark'
/usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:119:in `apply_catalog'
/usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:227:in `run_internal'
/usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:134:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/context.rb:64:in `override'
/usr/lib/ruby/site_ruby/1.8/puppet.rb:244:in `override'
/usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:133:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:47:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/agent/locker.rb:20:in `lock'
/usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:47:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:117:in `with_client'
/usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:44:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:82:in `run_in_fork'
/usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:43:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:179:in `call'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:179:in `controlled_run'
/usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:41:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/application/agent.rb:356:in `onetime'
/usr/lib/ruby/site_ruby/1.8/puppet/application/agent.rb:322:in `run_command'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:381:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:507:in `plugin_hook'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:381:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/util.rb:488:in `exit_on_fail'
/usr/lib/ruby/site_ruby/1.8/puppet/application.rb:381:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/util/command_line.rb:146:in `run'
/usr/lib/ruby/site_ruby/1.8/puppet/util/command_line.rb:92:in `execute'
/usr/bin/puppet:8
Error: /Stage[main]/Profile::Oracle::Os_wls::Data_sources/Wls_datasource[MyDS]/target: change from absent to MyServer failed: undefined method `sort' for :absent:Symbol
````

Is this enough of the logs?  The complete trace is very long and would probably need quite a lot of time consuming sanitizing before I could post it here.

**Comment by biemond** [comment]
thanks, 

indeed puppet resource 

this says enough on line 13,  Error: undefined method `sort' for :absent:Symbol
/var/lib/puppet/lib/puppet/type/shared/target.rb:13:in `insync?'

    def insync?(is)
      is.sort == should.sort
    end

So I need to check if 'is' or 'should' are objects.
@hajee any idea how to check if this it is not a symbol

**Comment by hajee** [comment]
`target` and `targettype` needs to be specified as an Array. If you specify an array, it works. We should however do better checking on the specified parameter and give you a nice error message.

**Comment by alexjfisher** [comment]
To be clear, I have specified ```target``` and ```targettype``` as arrays.  Puppet is producing the error when it tries to enforce this configuration after I have manually untargeted the datasource (for example by deleting the server in the console).

puppet resource does run after I manually untarget the datasource, but the resource it returns doesn't have a ```target``` or ```targettype``` property.  Should it actually be returning empty array properties instead??

**Comment by hajee** [comment]
Ah. So in that case,  the `should` is an array, but the `is`, is not an array. We could add:

```ruby
is = [] if is == :absent or is.nil?
```
This would make sure the comparison  is always done on  an array

**Comment by alexjfisher** [comment]
That looks like the easiest fix.  Would you like me to give it a try and create a PR if it works?

**Comment by biemond** [comment]
perfect. 
you know your testcase and you can conform if it really works plus get the credits with a PR

**Comment by alexjfisher** [comment]
Solves the issue for me.  I did a complete server rebuild to double check.  No problems encountered.
