### ISSUE TITLE
wls_datasource statementcachesize of 0 is reported as 10 by puppet resource

### ISSUE THREAD

**Issue by hajee** [biemond/biemond-orawls#216]
The index code set's the value to 10, if it is not set. When you set it to 0, the index therefore returns 10.

**Comment by biemond** [comment]
don't think your solution solves this. 10 is the default. so when you don't set it, the value should stay 10. So I think the default value of attribute statementcachesize should be 10

**Comment by hajee** [comment]
If it isn't set, Puppet doesn't change this. Maybe better remove the `defaultto 10` in the property definition.

**Comment by hajee** [comment]
I've also removed the `defaultto 10` line. Now WLS kan manage it's own default without puppet interfering. So:

```puppet
ls_datasource { 'default/bert':
  ensure                           => 'present',
  ...
  #without statementcachesize
}

```

Create's a datasource with the wls default 10. When you index it:

```puppet
wls_datasource { 'default/bert':
  ensure                           => 'present',
...
  statementcachesize               => '10',
...
}
```

When you explicitly set it to 0, it now also works.

**Comment by hajee** [comment]
Maybe we should consider removing all defaults in the puppet code. This makes it possible to lat Weblogic determine it's own defaults. It also helps when you just want to change one attribute on a WLS object that is created by Fusion, while leaving all others to the value fusion used. What do you think?

**Comment by hajee** [comment]
@biemond 

What do you think about this? 

Issue #243 from @alexjfisher is also about this kind of stuff.

Use case is a customer that wants to set specfific attributes on - for example  `maxcapacity` on a `wls_datasource` - that is created by the SOA installation. He only care's about the `maxcapacity` attribute, and would like to keep the rest to what the SOA installation has done. If we use this manifest:

```puppet
wls_datasource{'default/a_soa_datasource':
  maxcapacity => 100,
}
```

Puppet will change all sorts of attributes. This is caused by the defaults specfied in the ruby code for the property.

If we would remove these ruby defaults, we would let Weblogic manage it's own defaults. This would also allow Puppet to manage only those attributes it knowns about.

**Comment by biemond** [comment]
Yep, I don't want to use defaults and mostly I remove them because of this but if soa  also changes the defaults that I want to know them to be in control . 

This is only a problem for soa/osb etc because with plain wls there are no predefined wls artifacts, so in the meantime do puppet resource_datasource to know the current state.

It does not have the highest priority plus we need to fix it on all the wls artifacts and this requires many changes with so many extra test effort. 
I will do this when I refactor the  create and modify to 1 Python script in all the wls types.
