### ISSUE TITLE
Can't apply same opatch ID to multiple oracle homes

### ISSUE THREAD

**Issue by bradmcnaughton** [biemond/biemond-orawls#221]
Hi Edwin

I haven't found a way with Puppet and your module to apply the same opatch ID across multiple homes on the same domain. Sometimes this is required (e.g. Patchsets - 20900797 is one example). This is because the patch ID is the namevar for the opatch resource and Puppet will not allow it to occur twice in the catalog.

Do you know a way to do this with the current codebase? Otherwise I will make an attempt to add the functionality.

There are two possible design choices I believe. I would suggest we change the oracle_product_home_dir value to a list, and modify the resource to loop on it when applying the patch.

__Example 1__
orawls::opatch {'20900797':
  ensure                  => "present",
  oracle_product_home_dir => [ '/app/oracle/product/Oracle_SOA1', '/app/oracle/product/oracle_common' ],
  patch_id                => "20900797",
  patch_file              => "p20900797_1117_Generic.zip",
}

The drawback of this is that it wouldn't be possible to easily make the patch absent in one home while preserving it in the other, but in most use cases I think that would not be a real world use case anyway.

Another option would be to modify the type so that patch_id must be explicitly set and was not the name var, so you would define the resources as:

__Example 2__
orawls::opatch {'common_20900797':
  ensure                  => "present",
  oracle_product_home_dir => "/app/oracle/product/oracle_common",
  patch_id                => "20900797",
  patch_file              => "p20900797_1117_Generic.zip",
}

orawls::opatch {'soa_20900797':
  ensure                  => "present",
  oracle_product_home_dir => "/app/oracle/product/Oracle_SOA1",
  patch_id                => "20900797",
  patch_file              => "p20900797_1117_Generic.zip",
}

Let me know if you have any thoughts on the matter. Otherwise I will try to provide a pull request for you sometime. :)

Cheers
Brad

**Comment by bradmcnaughton** [comment]
I have thought about it a bit more and I'm not sure if turning oracle_product_home_dir from a string to an array/list will break all backwards compatibility.

Maybe to ensure existing implementations do not break I will check the value for a comma and split it, and if it is a string I will convert it into a single member array.

**Comment by biemond** [comment]
Option 2 is better for now and Option 1 is the best one.
Let's check the oradb opatch implementation, In this I can apply the same patch to grid and db home 

It seems I only need to check file { "${download_dir}/${patch_file}" is already defined and opatch title is db_opatch{ "${patch_id} ${title}"

**Comment by bradmcnaughton** [comment]
#227 pushed to fix this.

Also, it should be backwards compatible, from my testing it's good.

Thanks for the hint to check out db_opatch, made things easy in the end.
