### ISSUE TITLE
Domain exists check does not account for Puppet running as agent

### ISSUE THREAD

**Issue by bcornies** [biemond/biemond-orawls#224]
When managing a Weblogic server as part of a Puppet master/agent setup (i.e. running `puppet agent` instead of `puppet apply`) Puppet thinks the domain home doesn't exist which causes it to continuously try to re-create the domain.

Running the agent multiple times leads to the following output:

```
Notice: orawls::domain jmsBroker /opt/wls1036_jmsBroker/user_projects/domains/jmsBroker 1036 does not exists
Notice: /Stage[main]/Jmsbroker/Weblogic::Admin[jmsBroker]/Weblogic::Domain[jmsBroker]/Orawls::Domain[jmsBroker]/Notify[orawls::domain jmsBroker /opt/wls1036_jmsBroker/user_projects/domains/jmsBroker 1036 does not exists]/message: defined 'message' as 'orawls::domain jmsBroker /opt/wls1036_jmsBroker/user_projects/domains/jmsBroker 1036 does not exists'
Notice: /Stage[main]/Jmsbroker/Weblogic::Admin[jmsBroker]/Weblogic::Domain[jmsBroker]/Orawls::Domain[jmsBroker]/File[domain.py jmsBroker jmsBroker]/ensure: created
Notice: /Stage[main]/Jmsbroker/Weblogic::Admin[jmsBroker]/Weblogic::Domain[jmsBroker]/Orawls::Domain[jmsBroker]/Exec[domain.py jmsBroker jmsBroker]/returns: executed successfully
```

The problem is the `domain_exists($domain_dir)` function call in domain.pp. Functions get run during compilation on the Puppet master, so the function is actually checking for the existence of the domain direction _on the master_ which, of course, won't exist.

The function call needs to be made into a fact which will get run on the agent.

**Comment by biemond** [comment]
That's strange because lib/facter/orawls.rb tries to find all the domains on the client and will set all the facts.

So basically the orawls.rb crashes or cannot find the domains directory.  
it tries to read this file /etc/wls_domains.yaml on the client, so probably it is not there (because of missing dependencies or the domain creation did not went well )

Can you send me the first input , before it starts this will compare all domains.

And maybe run it with --debug.

**Comment by bcornies** [comment]
Sorry for the delay in getting back to you. I've upgraded to v1.0.41 and haven't been able to reproduce. I'm not sure if it was the upgrade that fixed it or something else. I'll see if I can reproduce.

**Comment by bcornies** [comment]
Hey Edwin,

I've verified that this is NOT an issue. I later realized that the domain_exists() function uses fact lookups and not direct server inspection (i.e. File.exists?). I will close this issue.
