### ISSUE TITLE
Wls_datasource target & targettype not fully idempotent

### ISSUE THREAD

**Issue by JoshiiSinfield** [biemond/biemond-orawls#230]
Hi,

The wls_datasource type/provider thinks that the target and targetType have changed due to ordering of values not being consistent:

notice	/Stage[main]/Datasources/Wls_datasource[development/squad7_WWW_SIAuditPool]/target	target changed ['squad7', 'squad7_WWW'] to 'squad7_WWW,squad7'
notice	/Stage[main]/Datasources/Wls_datasource[development/squad7_WWW_SIAuditPool]/targettype	targettype changed ['Server', 'Server'] to 'Server,Server'

looking in modify.py.erb I think the solution would be to sort the two arrays? What do you think?

**Comment by biemond** [comment]
Hi,

it should work https://github.com/biemond/biemond-orawls/blob/master/lib/puppet/type/shared/target.rb#L8

but it even does it for  ['Server', 'Server'] to 'Server,Server'.

it is not a WLST problem , it is in this ruby code

I will also test it on a datasource, maybe this only occurs when you got to target values.
@hajee Do you know what it is wrong.

Thanks

**Comment by hajee** [comment]
@JoshiiSinfield Are you using Arrays for `target` and `targettype` ?

I use Array's like this and this works fine.
```puppet
wls_datasource{'my_datasource':
  target      => ['squad7', 'squad7_WWW'],
  targettype  => ['Server', 'Server'],
}
```

An improvement would be to give better messages when you're **NOT** using an array.

**Comment by biemond** [comment]
Yeah, it also works for me 

are you using the latest release?

This is also working for me, even when I change the target order

    'hrDS':
      ensure:                      'present'
      drivername:                  'oracle.jdbc.xa.client.OracleXADataSource'
      extraproperties:
        - 'SendStreamAsBlob=true'
        - 'oracle.net.CONNECT_TIMEOUT=10001'
      globaltransactionsprotocol:  'TwoPhaseCommit'
      initialcapacity:             '2'
      jndinames:
        - 'jdbc/hrDS'
        - 'jdbc/hrDS2'
      maxcapacity:                 '15'
      target:
        - 'wlsServer2'
        - 'wlsServer1'
      targettype:
        - 'Server'
        - 'Server'
      testtablename:               'SQL SELECT 1 FROM DUAL'
      url:                         "jdbc:oracle:thin:@dbagent2.alfa.local:1521/test.oracle.com"
      user:                        'hr'
      password:                    'hr'
      usexa:                       '1'

**Comment by JoshiiSinfield** [comment]
Hi @biemond @hajee 

Thanks - This is the data for target and targettype:
  target: squad7_WWW,squad7
  targettype: Server,Server

hmm I wonder if it's because my data isn't in alphabetical order?
I'll also try specifying them both as an array, not comma-separated values.

Thanks for your help guys. I'll get back to you asap.

Josh.

**Comment by hajee** [comment]
The fact that they are not in alphabetical order shouldn't matter. If you use the array variant, I'm pretty sure it is idempotent.

Success

**Comment by JoshiiSinfield** [comment]
Hi All,

Thanks for this - I can confirm that using an array ensures idempotency. Seems like a strink does not though.

Feel free to close this if you like, or leave open if you want to reference this for the "better error message if not using an array" suggestion @hajee  made.

Cheers,
Josh
