### ISSUE TITLE
SOA installation fails if orawls::fmw resource title contains a space

### ISSUE THREAD

**Issue by alexjfisher** [biemond/biemond-orawls#231]
```
Error: Response file: /u01/install/SOA does not exist
```
This is because my orawls::fmw resource was called 'SOA BPEL'.  The response file does exist, but also contains the space.

I could create a PR for this but what approach would you prefer?  A few solutions:

* Add code to validate the resource's title and reject anything that isn't alphanumeric
* Escape the spaces when building $command  here https://github.com/biemond/biemond-orawls/blob/master/manifests/fmw.pp#L463
* Create a new variable $_title based on $title but with illegal characters stripped out or replaced and use that in the rest of the manifest.

**Comment by biemond** [comment]
Hi,

I think the last is the best. this way we help the user and still got a unique title
Thanks

**Comment by alexjfisher** [comment]
I'll open a PR shortly.  Meanwhile, apologies if I accidentally got travis to email you!
