### ISSUE TITLE
wls_deployment silently not deploying anything when using weblogic 12.1.1

### ISSUE THREAD

**Issue by alexjfisher** [biemond/biemond-orawls#239]
Hi

I had to downgrade one of my weblogic server roles from 12.1.3 to 12.1.1.  With 12.1.3, the webapps I was deploying deployed without issue.  No such luck with 12.1.1.

The wls_deployment type doesn't return any errors, but the deployments don't happen.  Run puppet again, and it tries deploying again, each time reporting that it has successfully deployed the webapps.

I was getting https://community.oracle.com/thread/2487297?tstart=0 so applied the suggested patch.  Now I don't get the warning, but I still don't end up with anything deployed.

I'm using 'stagingmode' => 'stage'.  There doesn't seem to be a 'stage' directory at /u01/app/oracle/Middleware/user_projects/domains/DOMAIN/servers/SERVER/stage
I tried manually creating this directory, but that made no difference either.

Any ideas?

Thanks,
Alex

**Comment by alexjfisher** [comment]
Putting some debug into the wlst script here https://github.com/biemond/biemond-orawls/blob/master/files/providers/wls_deployment/create.py.erb#L60 helped me track down the issue.

The deployments were failing with
```
java.io.IOException: [J2EE Deployment SPI:260080]Unable to define the application install directory at "/tmp/myapp.war". Directory could not be created or is a file.>
```

It turns out that the 'localpath' directory can't be '/tmp'.
http://stackoverflow.com/questions/11355642/remote-upload-using-wlst

In weblogic 12.1.3, this issue doesn't occur (I've not tested 12.1.2).

Perhaps the wls_deployment type should do some validation on this parameter?

Thanks,
Alex

**Comment by biemond** [comment]
Thanks for solving this.

What we can do is add a validation to this localpath parameter and raise an exception
https://github.com/biemond/biemond-orawls/blob/master/lib/puppet/type/wls_deployment/localpath.rb
