### ISSUE TITLE
wls_server type modifies unmanaged properties

### ISSUE THREAD

**Issue by alexjfisher** [biemond/biemond-orawls#242]
Hi

I came across this when trying to update the osb_server1 created by the OSB domain template.

If there is only a single property I wish to change/manage, I don't think it is the correct behaviour for the type to remove any of the other settings.
eg https://github.com/biemond/biemond-orawls/blob/master/files/providers/wls_server/modify.py.erb#L91

The type is very inconsistent.  Some properties are untouched and others are blanked (classpath, server start arguments etc).

**Comment by biemond** [comment]
Hi,

The best practice is to remove the default servers and create a cluster with 1 or 2 nodes.  And with this you need to create the servers yourself and this way you know exactly how the server configuration looks like.

but you can always use puppet resource wls_server this will show you all the settings made by the template.

cheers

**Comment by alexjfisher** [comment]
yep I'm currently rebuilding my server so I can find out what the deleted settings were.  I can then add them to my hiera.  I still don't think this is great though.  But I'll try to come up with a patch.

What if new properties get added in a later version?  If I don't add them to my hiera/code, the module might delete them without me ever knowing I had to set them?

**Comment by biemond** [comment]
I try not to use defaults on the attributes and if so I will use the wls ones. 
when not provided I will try not override those.

**Comment by alexjfisher** [comment]
Does this sort of approach look sensible?
https://github.com/biemond/biemond-orawls/pull/243

**Comment by biemond** [comment]
Now I know what you mean, but can you make arguments empty again.


    if arguments is not None:
       #empty strings in python are falsey
       if arguments:

is this not the same?

**Comment by alexjfisher** [comment]
I guess None is also falsely, so I can probably clean up the logic.  The point was that if arguments is None (because they've been left out), then we don't want to do the ```set('ServerStart/'+name+'/Arguments', None)```

You can still delete the arguments by setting the arguments property to an empty string (and maybe also undef?? - I'd like to double check this).

Perhaps setting the arguments var to some other value like 'UNMANAGED' might make the code clearer.
I'll take another look tomorrow.

**Comment by alexjfisher** [comment]
To make arguments empty, it was not necessarily enough to just leave it out of the puppet resource.  If no other properties were being modified, modify.py would not be called.

I've updated https://github.com/biemond/biemond-orawls/pull/243 to make it more readable.  I've also fixed the behaviour of bea_home and classpath.

```listenaddress``` needs fixing to. Do you know what the ```and not listenAddress.isspace()``` is about?
https://github.com/biemond/biemond-orawls/blob/master/files/providers/wls_server/modify.py.erb#L88

**Comment by alexjfisher** [comment]
https://github.com/biemond/biemond-orawls/blob/master/files/providers/wls_server/modify.py.erb#L123 doesn't look right.  If ```TunnelingEnabled``` was true, but you're now trying to set it to false, https://github.com/biemond/biemond-orawls/blob/master/files/providers/wls_server/modify.py.erb#L124 would never get called?

**Comment by biemond** [comment]
listenAddress.isspace is used so it can listen on all ip addresses.
and tunnelingenabled is text and not a boolean, it is converted to a boolean.

**Comment by alexjfisher** [comment]
I've updated https://github.com/biemond/biemond-orawls/pull/243 and it all seems to work ok.  To make a server listen on all addresses, both a single space and an empty string should work.  An added bonus is that listening on all addresses is now idempotent.

@hajee - Do you mind having a look too?  Since the module uses easy-type, I'd appreciate your feedback. Make sure I'm not proposing anything too brain-dead! :)
