### ISSUE TITLE
Opatch tries to apply patches already present

### ISSUE THREAD

**Issue by BasLangenberg** [biemond/biemond-orawls#245]
I noticed that my Puppet run is failing after initial provisioning since I updated the orawls module yesterday eob.

> ==> admin: Debug: /Stage[main]/Profile::Wlspatch/Orawls::Opatch[20838345]/File[/app/software/p20838345_121300_Generic.zip]: The container Orawls::Opatch[20838345] will propagate my ref
resh event
> ==> admin: Debug: /Stage[main]/Profile::Wlspatch/Orawls::Opatch[20838345]/File[/app/software/p20838345_121300_Generic.zip]: The container Orawls::Opatch[20838345] will propagate my ref
resh event
> ==> admin: Debug: /Stage[main]/Profile::Wlspatch/Orawls::Opatch[20838345]/File[/app/software/p20838345_121300_Generic.zip]: The container Orawls::Opatch[20838345] will propagate my ref
resh event
> ==> admin: Debug: opatch_status for patch 20838345 command: /app/oracle/products/1213/OPatch/opatch lsinventory -patch_id -oh /app/oracle/products/1213 -invPtrLoc /etc/oraInst.loc
> ==> admin: Debug: line 20838345;
> ==> admin: Debug: opatch_status output NotFound for patchId 20838345
> ==> admin: Debug: opatch action: present with command /app/oracle/products/1213/OPatch/opatch apply -silent -jre /app/oracle/products//jdk1.7.0_75/jre -oh /app/oracle/products/1213 /ap
p/software/20838345
> ==> admin: OPatch system modification phase did not start:
> ==> admin: Info: opatch result: Oracle Interim Patch Installer version 13.2.0.0.0
> ==> admin: Copyright (c) 2014, Oracle Corporation.  All rights reserved.
> ==> admin:
> ==> admin:
> ==> admin: Oracle Home       : /app/oracle/products/1213
> ==> admin: Central Inventory : /app/oracle/oraInventory
> ==> admin:    from           : /app/oracle/products/1213/oraInst.loc
> ==> admin: OPatch version    : 13.2.0.0.0
> ==> admin: OUI version       : 13.2.0.0.0
> ==> admin: Log file location : /app/oracle/products/1213/cfgtoollogs/opatch/opatch2015-10-20_09-52-32AM_1.log
> ==> admin:
> ==> admin:
> ==> admin: OPatch detects the Middleware Home as "/app/oracle/products/1213"
> ==> admin:
> ==> admin: Oct 20, 2015 9:52:43 AM oracle.sysman.oii.oiii.OiiiInstallAreaControl initAreaControl
> ==> admin: INFO: Install area Control created with access level  0
> ==> admin: Applying interim patch '20838345' to OH '/app/oracle/products/1213'
> ==> admin: Verifying environment and performing prerequisite checks...
> ==> admin:
> ==> admin: The following patch(es) are already installed in the Oracle Home.
> ==> admin:  [20838345]
> ==> admin: Please roll back the existing identical patch(es) first.
> ==> admin:
> ==> admin: Log file location: /app/oracle/products/1213/cfgtoollogs/opatch/opatch2015-10-20_09-52-32AM_1.log
> ==> admin:
> ==> admin: OPatch stopped on request.
> ==> admin:

(Logging is from Vagrant)

For some reason the patch which is present, is not detected as such. I'm investigation the problem, but wanted to give you a heads up about this...

**Comment by biemond** [comment]
Ok,

Can you run it yourself and look at the output.
/app/oracle/products/1213/OPatch/opatch lsinventory -patch_id -oh /app/oracle/products/1213 -invPtrLoc /etc/oraInst.loc

and is it a bundle patch, mostly this patch number are not registered( only the patch id's inside) and you need to use a sub patch id as reference,

**Comment by BasLangenberg** [comment]
I found something. I added a line in lib/puppet/provider/opatch/opatch.rb on line 57

> Puppet.debug "DEBUG #{patchName}"

In my debug logging I found the following:

==> admin: Debug: line 20838345**;**
==> admin: Debug: DEBUG 20838345 

So the opatch variable is the same patch ID, only with a ; after it. Of course Puppet now thinks they do not match. My Ruby is not that strong (I should read up on it) but I figure we try to cast it to an array of some sort.

This only happens if I use the orawls version as of commit 0e18423. Before I was on 0124d52.

I'm doing some more testing.

**Comment by BasLangenberg** [comment]
It's getting more strange. Knowing I only have one bundle installed, I removed the + ; from the Ruby code to test some more.

> ==> admin: Debug: line 20838345
> ==> admin: Debug: DEBUG 20838345

After this, It still goes wrong and tries to apply the patch again.

I'm starting to think it's me. Will go through my roles and profiles.

**Comment by biemond** [comment]
Ok,

I just do an include,  the patchnumber only have to be in the output. 
https://github.com/biemond/biemond-orawls/blob/master/lib/puppet/provider/opatch/opatch.rb#L57

but this can be wrong , don't know why I add ; to it but the include check should still work.

    output.each_line do |li|
        opatch = li[5, li.index(':') - 5].strip + ';' if li['Patch'] && li[': applied on']

**Comment by BasLangenberg** [comment]
If I explicitly cast both variables to integers, it works.

>  def opatch_status
>    user                    = resource[:os_user]
>    patchName               = resource[:patch_id]
>    oracle_product_home_dir = resource[:oracle_product_home_dir]
>    orainst_dir             = resource[:orainst_dir]
>
>    command  = oracle_product_home_dir + '/OPatch/opatch lsinventory -patch_id -oh ' + oracle_product_home_dir + ' -invPtrLoc ' + orainst_dir + '/oraInst.loc'
>    Puppet.debug "opatch_status for patch #{patchName} command: #{command}"
>
>    kernel = Facter.value(:kernel)
>    su_shell = kernel == 'Linux' ? '-s /bin/bash' : ''
>
>    output = `su #{su_shell} - #{user} -c '#{command}'`
>
>    output.each_line do |li|
>      opatch = li[5, li.index(':') - 5].strip if li['Patch'] && li[': applied on']
>      unless opatch.nil?
>        Puppet.debug "line #{opatch}"
>        Puppet.debug "DEBUG #{patchName}"
>        patchNum = patchName.to_i
>        if opatch.to_i == patchNum
>          Puppet.debug 'found patch'
>          return patchName
>        end
>      end
>    end
>    'NotFound'
>  end

This might be some horrible, horrible Ruby.

I'll do some more testing (remove patch etc) and file a PR

**Comment by biemond** [comment]
that is strange, include should work on text. So ruby behaves strangely

Are you using the future parser or latest puppet release which uses a different ruby?

**Comment by BasLangenberg** [comment]
Puppet v3.8.1 with Vagrant 1.7.2. Nothing changed, next to updating orawls to the latest version. If I do a git checkout HEAD~1 all is working fine. I am a terrible person not including your module as a submodule in our repo, so I only occasionally update to your latest and greatest version. 

I'm confused too. I did some digging on include? and that should indeed work. I went a bit more strongly typed on this one, and that does seem more robust on my system.

**Comment by biemond** [comment]
by the way we are now testing #244 from @hajee , this  a new opatch type which use

     patch_ids = raw_list.scan(/Patch\s.(\d+)\s.*:\sapplied on/).flatten

and also uses include to test it

     all_patches = oracle_homes(resources).collect {|h| patches_in_home(h, os_user)}.flatten
        resources.keys.each do |patch_name| 
           if all_patches.include?(patch_name)
              resources[patch_name].provider = new(:name => name, :ensure => :present)

**Comment by BasLangenberg** [comment]
I removed the patch manually and did 2 provisions. The first one applied the patch, the second one did detect the existence of the patch correctly.

````
==> admin: Debug: /Stage[main]/Profile::Wlspatch/Orawls::Opatch[20838345]/File[/app/software│  certificate       Provide access to the CA for certificate management.
/p20838345_121300_Generic.zip]: The container Orawls::Opatch[20838345] will propagate my ref│  certificate_request  Manage certificate requests.
resh event                                                                                  │  certificate_revocation_list  Manage the list of revoked certificates.
==> admin: Debug: /Stage[main]/Profile::Wlspatch/Orawls::Opatch[20838345]/File[/app/software│  config            Interact with Puppet's settings.
/p20838345_121300_Generic.zip]: The container Orawls::Opatch[20838345] will propagate my ref│  describe          Display help about resource types
resh event                                                                                  │  device            Manage remote network devices
==> admin: Debug: /Stage[main]/Profile::Wlspatch/Orawls::Opatch[20838345]/File[/app/software│  doc               Generate Puppet documentation and references
/p20838345_121300_Generic.zip]: The container Orawls::Opatch[20838345] will propagate my ref│  facts             Retrieve and store facts.
resh event                                                                                  │  file              Retrieve and store files in a filebucket
==> admin: Debug: opatch_status for patch 20838345 command: /app/oracle/products/1213/OPatch│  filebucket        Store and retrieve files in a filebucket
/opatch lsinventory -patch_id -oh /app/oracle/products/1213 -invPtrLoc /etc/oraInst.loc     │  help              Display Puppet help.
==> admin: Debug: line 20838345                                                             │  inspect           Send an inspection report
==> admin: Debug: found patch                                                               │  instrumentation_data  Manage instrumentation listener accumulated data. DEPRECATED.
==> admin: Debug: opatch_status output 20838345 for patchId 20838345                        │  instrumentation_listener  Manage instrumentation listeners. DEPRECATED.
==> admin: Debug: Orawls::Opatch[20838345]: The container Class[Profile::Wlspatch] will prop│  instrumentation_probe  Manage instrumentation probes. Deprecated
agate my refresh event                      
````

Do you want me to file a PR?

**Comment by biemond** [comment]
yeah that's do that.

thanks

**Comment by BasLangenberg** [comment]
See #246
