### ISSUE TITLE
Request (not issue): Stopping Composites

### ISSUE THREAD

**Issue by ds2000** [biemond/biemond-orawls#258]
Hi Edwin,

Great module, we've been using it alot :+1: 

Just a very quick one, we have some draindown / prereqs that require a few composites being shutdown before we update our code.  I'm currently writing a py for this but was wondering in the future if this was on your radar?

Many thanks
Dave

**Comment by biemond** [comment]
Hi, 

if you can show me the code I can take a look at it and see if we can make a type for it. 
in the meantime in the github version of orawls you can use the wls_exec type

see #255 for more information.

**Comment by ds2000** [comment]
Thanks,

The code from wlst is just sca_stopComposite / sca_startComposite within WLST offline.  I guess in Hiera we would need the deployment rpm:

myapp:
    compositeName: applicationName
    ensure: stopped / running

and then puppet knowing to invoke a python script that would connect to the domain and stop the services.

I'm currently writing a small script that I'll install as a service; I'll parameterise this from a env_config file the devs have access to where they can specify the services they want to stop.  From there our selfservice deployments can manage the transactions with 'service weblogic-composite-state stop/start' - so we're eliminating the human interaction.

Its a bit of a work around but sadly we're on an old version of the module that we can't up-issue for the immediate future so we've got no real control over wls_exec.

Thanks
