### ISSUE TITLE
Could not autoload puppet/type/wls_domain from version >= 1.0.41

### ISSUE THREAD

**Issue by zokusai** [biemond/biemond-orawls#281]
Hi,

With this environment:

Oracle Linux Server release 5.11
puppet 3.8.4 (gem package)

├── adrien-filemapper (v1.1.3)
├── biemond-orawls (v1.0.41)
├── fiddyspence-sleep (v1.2.0)
├── fiddyspence-sysctl (v1.1.0)
├── hajee-easy_type (v0.15.5)
├── hajee-oracle (v1.7.27)
├── puppetlabs-java (v1.4.2)
├── puppetlabs-stdlib (v4.9.0)
└── reidmv-yamlfile (v0.2.0)

And version >= 1.0.41, I always obtain the following error:

Error: Could not autoload puppet/type/wls_domain: file puppet/type/wls_domain/web_app_container_show_archived_real_path_enabled not found
Debug: Storing state
Debug: Stored state in 0.01 seconds
Error: Failed to apply catalog: Could not autoload puppet/type/wls_domain: file puppet/type/wls_domain/web_app_container_show_archived_real_path_enabled not found

Thanks

**Comment by zokusai** [comment]
Looking more at it, I see that the problem only happen when the installation was done through r10k:
r10k 2.1.1

In my Pupperfile the declaration is:
mod 'biemond-orawls'

Using "puppet module install biemond-orawls" the problem disappear.

In both cases the versions of the dependencies keep the same.

You have any ideas about what might be happen?

Thanks

**Comment by robh007** [comment]
I had a similar issue, are you using the forge to get the module? I switched to use github and the issue went away. I also did a puppet module install and the file in question arrived within the puppet module. I too was using r10k.

**Comment by biemond** [comment]
Maybe it can be this bug . types changes are not picked up unless there are on the primary puppet  module location , this is a known puppet bug.

**Comment by robh007** [comment]
I was running masterless. As mentioned above it appeared to be something to do with the r10k deploy and using the puppetforge. When I switched to use your github repo it worked fine.

**Comment by zokusai** [comment]
Thanks, you are absolutely right!! Changing to the git reference, work as expected.
I'm also running it in masterless mode with r10k + puppet apply.
