### ISSUE TITLE
unable to install weblogic 1221 with orawls::weblogic 

### ISSUE THREAD

**Issue by srinivasmohan57** [biemond/biemond-orawls#315]
Hi,

Facing issue while installing weblogic 1221, as the silent script is expecting an nonexisting or empty oracle_home directory but where as oraInventory  directory is getting created in oracle_home. 

weblogic.pp has the below 
$oraInventory  = "${oracle_base_home_dir}/oraInventory"

reference:
https://community.oracle.com/thread/3544823?start=0&tstart=0

Is there a way to overcome this?

**Comment by biemond** [comment]
Hi,

you can do this. Indeed you won't do that inside a middleware home because it can be also used by other oracle product.

oracle_base_home_dir => /opt/oracle
middleware_home_dir  => /opt/oracle/middleware11gR1

also check this vagrant box 
https://github.com/biemond/biemond-orawls-vagrant-12.2.1

Thanks

**Comment by srinivasmohan57** [comment]
Thanks, working fine.

Have got one more issue with domain creation. Logs says domain directory has files but it is  a non existing directory and was created during orawls::domain execution.
Please help in resolving the issue.
Notice: orawls::domain wls_domain01 /domains/wls_domain01 1221 does not exists

Notice: /Stage[main]/Wlsserver::Create_wlsdomain_12c/Orawls::Domain[wls_domain01]/Exec[execwlst wls_domain01 wls_domain01]/returns: **60303**: The domain directory "/domains/wls_domain01" **you specified contains files**. You may only create a domain in an empty directory.
n.

**Comment by biemond** [comment]
you need to send me your config and check what is inside this domain folder.

Thanks Edwin

**Comment by srinivasmohan57** [comment]
Hi Edwin, 
A hidden directory is getting created **.oracle_jre_usage **  inside the domain directory with a file **afa83bb4b45cf321.timestamp**  have jre path and time stamp

below is the configuration used
  orawls::domain { "wls_domain01":
    version                     => 1221,
    weblogic_home_dir           => '/opt/products/middleware/wlserver',
    middleware_home_dir         => '/opt/products/middleware',
    jdk_home_dir                => '/opt/jdk1.8.0_73',
    wls_domains_dir             => '/domains',
    wls_apps_dir                => '/domains/applications',
    domain_template             => "standard",
    domain_name                 => 'wls_domain01',
    development_mode            => false,
    adminserver_name            => "admin",
    adminserver_address         => $facts['ipaddress'],
    adminserver_port            => 7001,
    nodemanager_secure_listener => false,
    nodemanager_address         => $facts['ipaddress'],
    nodemanager_port            => 5556,
    weblogic_user               => 'admin',
    weblogic_password           => 'XXXXXXX',
    java_arguments              => "-XX:PermSize=256m -XX:MaxPermSize=512m -Xms1024m -Xmx1024m",
    jsse_enabled                => false,
    os_user                     => "$os_user",
    os_group                    => "$os_group",
    download_dir                => '/tmp',
    log_output                  => true,
  }

Thanks
Srinivas

**Comment by biemond** [comment]
Ok 

can you try this, don't mix up domains with shared applications directories also this is the right way for passing on java parameters

```
orawls::domain { "wls_domain01":
version => 1221,
weblogic_home_dir => '/opt/products/middleware/wlserver',
middleware_home_dir => '/opt/products/middleware',
jdk_home_dir => '/opt/jdk1.8.0_73',
wls_domains_dir => '/wls_domains/domains',
wls_apps_dir => '/wls_domains/applications',
domain_template => "standard",
domain_name => 'wls_domain01',
development_mode => false,
adminserver_name => "admin",
adminserver_address => $facts['ipaddress'],
adminserver_port => 7001,
nodemanager_secure_listener => false,
nodemanager_address => $facts['ipaddress'],
nodemanager_port => 5556,
weblogic_user => 'admin',
weblogic_password => 'XXXXXXX',
java_arguments => { "ADM" => "-XX:PermSize=256m -XX:MaxPermSize=512m -Xms1024m -Xmx1024m"},
jsse_enabled => false,
os_user => "$os_user",
os_group => "$os_group",
download_dir => '/tmp',
log_output => true,
}

```
