### ISSUE TITLE
Running orawls without root permissions

### ISSUE THREAD

**Issue by altroy75** [biemond/biemond-orawls#330]
When trying to run orawls masterless, using a user which doesn't have elevated permissions the module fails. After some investigation we have identified at least the following issues:
1. orawls requires read/write access to /etc. 
2. orawls initializes easy_type with a user which makes easy_type to run "su - #{user}". Under a non-root user it doesn't work.
3. exec resource in several places uses "user" parameter, which again doesn't work under a non-root user.

**Comment by biemond** [comment]
Hi,

it was more that puppet always runs as root. So it was build for that. It will works perfectly with puppet agent or apply.

1) indeed I will a common location for the domains information. 
2) indeed for puppet type / resource we will wlst as root under the right user.
3) you are right.

I don't know if we can support this but puppet can support sudo.  I don't what we need to do , to support that.

Thanks Edwin

**Comment by altroy75** [comment]
Unfortunately, on our customer's site we don't have sudo permissions either. 
We will try to provide a solution and then we will propose it as a pull request, OK?

**Comment by biemond** [comment]
orawls now supports this
