### ISSUE TITLE
How to set WLST custom Classpath for WlsDaemon

### ISSUE THREAD

**Issue by MarkRoddick** [biemond/biemond-orawls#331]
Hi,

I need to add some custom JARS to the Classpath before invoking WLST. 
I have noticed in wls_daemon.rb "postClasspath" can be set.

Please can you provide some guidance on how I set this?

**Comment by biemond** [comment]
Hi,

you can do this

```
wls_setting { 'domain2':
  user                         => 'oracle',
  weblogic_home_dir            => '/opt/oracle/middleware11g/wlserver_10.3',
  connect_url                  => "t3://localhost:7011",
  weblogic_user                => 'weblogic',
  weblogic_password            => 'weblogic1',
  post_classpath               => '/opt/oracle/wlsdomains/domains/Wls1036/lib/aa.jar'
}
```

or 

```
wls_setting_instances:
  'default':
    user:               'oracle'
    weblogic_home_dir:  '/opt/oracle/middleware12c/wlserver'
    connect_url:        "t3://10.10.10.21:7001"
    weblogic_user:      'weblogic'
    weblogic_password:  'weblogic1'
    post_classpath:     '/opt/oracle/middleware12c/oracle_common/modules/internal/features/jrf_wlsFmw_oracle.jrf.wlst_12.1.3.jar'
```

So when you got our own authentication provider you probably need to add the jar to your domain lib directory after the domain creation.

like I do here 
```
class domains{
  require orawls::weblogic, opatch

  $default_params = {}
  $domain_instances = hiera('domain_instances', {})
  create_resources('orawls::domain',$domain_instances, $default_params)

  $file_domain_libs = hiera('file_domain_libs', {})
  create_resources('file',$file_domain_libs, $default_params)

  $wls_setting_instances = hiera('wls_setting_instances', {})
  create_resources('wls_setting',$wls_setting_instances, $default_params)

}
```

matching hiera
```
domain_instances:
  'Wls11g':
    domain_template:                       "standard"
    development_mode:                      false
    log_output:                            *logoutput
    domain_name:                           'Wls11g'
    adminserver_port:                      7011

file_domain_libs:
  '/opt/oracle/wlsdomains/domains/Wls11g/lib/idmsSecurityProvider-3.26-SNAPSHOT.jar':
    ensure:     present
    source:     '/vagrant/idmsSecurityProvider-3.26-SNAPSHOT.jar'
    mode:       '0775'
    owner:      'wls'
    group:      'dba'
    require:    Orawls::Domain[Wls11g]
    before:     Wls_setting[default]

wls_setting_instances:
  'default':
    user:                      *wls_os_user
    weblogic_home_dir:         *wls_weblogic_home_dir
    connect_url:               "t3://%{hiera('domain_adminserver_address')}:7011"
    weblogic_user:             *wls_weblogic_user
    weblogic_password:         *domain_wls_password
    loglevel:                  'debug'
    debug_module:              'true'
    archive_path:              '/var/tmp/install/wls11g_domain'
    post_classpath:            "/opt/oracle/wlsdomains/domains/Wls11g/lib/idmsSecurityProvider-3.26-SNAPSHOT.jar"

```

**Comment by MarkRoddick** [comment]
Brilliant thanks that works! Sorry i've just noticed this in your documentation.

There are some resources which use the wlst.sh script rather than the wlsDeamon e.g. fmwlogdir.pp:

`${middleware_home_dir}/oracle_common/common/bin/wlst.sh {download_dir}/${title}changeFMWLogFolder.py ${weblogic_password}`

Do you know how can I modify this to use the deamon? As the classpath set for the deamon is not set when initializing a new WLST process through the shell script.

**Comment by biemond** [comment]
Basically 

wlsDaemon is only for all the native wls types. Something like start/stop , create a domain and changing FMW log folder is not supported.  

But you can make a custom type and basically you need to create a type and create the following py scripts like an index and modify. Index for retrieving the current state and modify for the changing of the location of the log file. I think create or destroy is not possible.

Or change the fmwlogdir manifest and add a parameter to it and set some WLST environment parameter which will be picked up by WLST.sh. Try it out without puppet and see if it works and after that you can implement it 

Hope this helps

**Comment by MarkRoddick** [comment]
Thanks Edwin that helps.
I have just created a WLST wrapper for now to invoke before running WLST.sh.
We may look into creating a custom type but least this works in the short term.
