### ISSUE TITLE
Cannot reassign variable install_type

### ISSUE THREAD

**Issue by mkelderm** [biemond/biemond-orawls#333]
Running the module, results into an error:

Cannot reassign variable install_type at /data/puppet/environments/trunk/modules/orawls/manifests/fmw.pp:142

install_type is already set by ohs_mode 

Note: I am trying to install fmw_product soa

**Comment by biemond** [comment]
indeed a stupid bug, moved it to the web if statement
with #da10ed4 I hope I fixed it
