### ISSUE TITLE
wls_server fails on java.lang.NullPointerException

### ISSUE THREAD

**Issue by racorretjer** [biemond/biemond-orawls#336]
Hello.

To provide a bit of context, I am using JRockit with this module.

I installed weblogic through orawls::weblogic, created a new domain with orawls::domain, setup the nodemanager with orawls::nodemanager, started the 'startWebLogic.sh' located in my domain directory with the command ./startWebLogic.sh &, and I created a couple of machines with the wls_machine type. Up until then, everything works fine.

When I try to create managed servers through the type 'wls_server', I get an 'Unexpected error: java.lang.NullPointerException' error. Digging through the files that were being executed at that time, I managed to single out the error to the following line in 'orawls/files/wlst/common.py.erb':
os.system('chmod 600 ' + full_file_name)

that is line 76 of that file.
I've commented out that line just to make sure that it's not something else. The puppet run succeeds after doing so.

Now, I'm not exactly savvy on Jython, but I don't understand why this should fail.

If you need more information on how to recreate the problem, please let me know.

Thanks

**Comment by biemond** [comment]
Hi,

is jrocket compatible with java 1.6 ? I suspect jython doesn't understand/have os or os.system.
Can you check this? 
http://www.jython.org/docs/library/os.html
and find out which version of jython you are using plus let's test it with latest version of jdk1.7

Thanks

**Comment by racorretjer** [comment]
Hello. Thank you for your swift reply.

The Jython interpreter version that wlst.sh is using is 2.2.1. The version of JRockit I am using is 1.6.0... I wasn't sure if that translates to compatibility with oracle jdk 1.6.0, so I tested my code with JDK1.6.0 and it seems that that did the trick, though I still need JRockit. I'll work on adding support for JRockit on that Jython script.

**Comment by racorretjer** [comment]
Hi again.

So I managed to add support to JRockit by adding the 'import traceback' line to the top of the orawls/files/wlst/common.py.erb file. I will now test against all other JDK implementations and make sure that that didn't break anything else.

**Comment by biemond** [comment]
👍
