### ISSUE TITLE
Unable to modify existing authenticator

### ISSUE THREAD

**Issue by reehalhs** [biemond/biemond-orawls#338]
Greetings Edwin!
 
I am trying to modify the attributes of existing authenticator, but the wlst script exists with exception. It probably happens because the module always invokes 'create' rather than 'modify'. Since the authenticator already exists, thus it errors out.

I also noticed that there is no factor generated about the authenticators configured in the domain. Could that be the reasons?

Following is the wlst snippet code which is always executed weather new or existing.

try:
    cd('/')
    realmName  = cmo.getSecurityConfiguration().getDefaultRealm()
    path = getPath(realmName)
    cd(path)
    cmo.createAuthenticationProvider(name, providerclassname)

Obviously, for existing authenticator, the creation of mbean will fail. For existing authenticator, should it not be invoking 'on modify' script?

Regards,

Hardeep

**Comment by biemond** [comment]
Hi Hardeep

I think the index always goes wrong and that why it wants to create it everything
maybe we can look first at index.py.  
or do 
```
puppet resource wls_authentication_provider --debug
```

it can be you are missing a jar in wls_settings post_classpath attribute.

Hope this helps

**Comment by reehalhs** [comment]
Yes it did help!

I am trying configure active directory authenticator and also modify the default authenticator. In the first run, active directory authenticator is configured as well as default one is modified, however, if I apply the catalog again, then, I am getting error on Active directory authenticator. I Inspected the outcome of index.rb and it lists only default authenticator, whereas config.xml shows that active directory authenticator is also configured.

it is possible that active directory authenticator is not fully configured yet (not restarting admin yet :( ), thus it does not show up in the query result in index.rb. 

I think I will get to the bottom of it :)

Regards,

Hardeep

**Comment by biemond** [comment]
yeah 

you should restart the adminserver else it won't be picked up. the edit() has the current state .
you can subscribe to these changes and auto restart the adminserver.

**Comment by reehalhs** [comment]
Edwin! just wanted to share that I was able to configure active directory authenticator - modify role and restart admin server successfully and allowing users to login with the active directory credentials.

Regards,

Hardeep

**Comment by biemond** [comment]
Super 👍
