### ISSUE TITLE
Weblogic won't install if domain_dir is inside weblogic_home

### ISSUE THREAD

**Issue by bFekete** [biemond/biemond-orawls#344]
Currently if I set 

-  middleware_home = /opt/oracle/middleware
-  weblogic_home = /opt/oracle/middleware/wls1036
-  wls_domains_dir = /opt/oracle/middleware/wls1036/domains
-  wls_apps_dir = /opt/oracle/middleware/wls1036/apps

it won't install weblogic via the silent file because the exec will only run if the /opt/oracle/middleware/wls1036 doesn't exist, but the wls_domains_dir sets up the directory structure and creates the directories before the installing.

- https://github.com/biemond/biemond-orawls/blob/master/manifests/weblogic_type.pp#L204
- https://github.com/biemond/biemond-orawls/blob/master/manifests/weblogic_type.pp#L162-L167

**Comment by biemond** [comment]
yeah, 

best practice is to put the domains outside the mdw home or leave wls_domains_dir empty and then it will use user_project/domains inside the mdw_home.

an option is to move domains dir creation after the wls install but that will make it more complicated.

Thanks Edwin

**Comment by bFekete** [comment]
Alright, thanks!
