### ISSUE TITLE
wls_server and wl_machine fail when running puppet agent with --debug flag

### ISSUE THREAD

**Issue by thc100x100** [biemond/biemond-orawls#354]
Seems that wls_settings is not applied when run puppet agent on debug...
It shows the following exception, when running the agent without the --debug flag it works nice:

`Info: index wls_machine 
Info: Executing: wlstScript with action index
Info: domain found default
Error: Could not prefetch wls_machine provider 'simple': undefined local variable or method `weblogicConnectUrL' for Puppet::Type::Wls_machine:Class
Info: create default/orco_machine_1 
Info: Executing: wlstScript with action 
Info: Got the right domain default script, now execute WLS` 

it looks like it is not able to read the /etc/wls_setting.yaml file... but it is there and with the proper connect_url:

this also happens with the wls_domains, it doesn't detect the wls_domains.yaml when you run the puppet agent with the --debug flag

**Comment by biemond** [comment]
Hi,

it was a spelling error in weblogicConnectUrL -> weblogicConnectUrl
see #352 #353 

and is now fixed .

I will push a new version to forge
