### ISSUE TITLE
Opatch failing when running puppet as non root

### ISSUE THREAD

**Issue by MarkRoddick** [biemond/biemond-orawls#361]
Hi Edwin,

The Weblogic installation completes however OPatch is failing when running puppet as non-root user.
Running the same code as the root user works without issues.

Please can you take a look?

Error:
`Info: Applying configuration version '1468335762'
Debug: Evicting cache entry for environment 'online_dev'
Debug: Caching environment 'online_dev' (ttl = 0 sec)
Debug: Prefetching prefetching resources for wls_opatch
Debug: Executing '/u01/oracle/product/fmw1213/OPatch/opatch lsinventory -oh /u01/oracle/product/fmw1213 -invPtrLoc /etc/oraInst.loc'
Error: Could not prefetch wls_opatch provider 'prefetching': Execution of '/u01/oracle/product/fmw1213/OPatch/opatch lsinventory -oh /u01/oracle/product/fmw1213 -invPtrLoc /etc/oraInst.loc' returned 1:
`

Hiera:

opatch_instances:
    '16175470':
      ensure:                   'present'
      oracle_product_home_dir:  '/u01/oracle/product/fmw1213'
      patch_id:                 '19360945'
      patch_file:               '19360945_121300_Generic.zip'
      jdk_home_dir              '/usr/java/jdk1.7.0_95'
      os_user:                  'oracle'
      os_group:                 'oinstall'
      download_dir:             '/u02/oracle/install'
      source:                   '/mnt/software/oracle'
      log_output:               true

Kind regards,
Mark

**Comment by biemond** [comment]
ok,

sometimes opatch needs to run as root ( but that is more for DB, grid) . I guess it needs some tmp access/resources. Can you make a vagrant box with your config,  so I can test it.

this is great example.

**Comment by MarkRoddick** [comment]
I can run the Opatch command (below) fine as non root user. Looks like it is something to do with the opatch prefetching as non root - puppet\modules\orawls\lib\puppet\provider\wls_opatch\prefetching.rb

`/u01/oracle/product/fmw1213/OPatch/opatch lsinventory -oh /u01/oracle/product/fmw1213 -invPtrLoc /etc/oraInst.loc`

**Comment by MarkRoddick** [comment]
Running the lsinventory Opatch command manually as non root user works fine:
`/u01/oracle/product/fmw1213/OPatch/opatch lsinventory -oh /u01/oracle/product/fmw1213 -invPtrLoc /etc/oraInst.loc`

Looks like it is something to do with the opatch prefetching - puppet\modules\orawls\lib\puppet\provider\wls_opatch\prefetching.rb

**Comment by biemond** [comment]
maybe it is because of this 

 Puppet::Util::Execution.execute(full_command, :failonfail => true, :uid => os_user)

I think it tries to be root and then switch to the right user. this was a PR
maybe we should use this 
`su #{su_shell} - #{user} -c '#{command}'`

thanks

**Comment by MarkRoddick** [comment]
Thanks for the tip - I have got Opatch now running when as non root.

I have tried catering for both root and non root users (see new prefetching.rb file [prefetching.rb.txt](https://github.com/biemond/biemond-orawls/files/360007/prefetching.rb.txt)) however I am experiencing the below issue when running as root.

Any ideas?
 
```
Debug: Prefetching prefetching resources for wls_opatch
Error: Could not prefetch wls_opatch provider 'prefetching': Puppet::Util::Log requires a message

```

**Comment by biemond** [comment]
I think output is empty in this statement Puppet.info output 
Did you get any output.

**Comment by MarkRoddick** [comment]
Sorry my fault the wrong command was executing when root.
This now works fine - ill submit a pull request.

Thanks!

**Comment by biemond** [comment]
👍
