### ISSUE TITLE
Domain does not exist issue when running as non root

### ISSUE THREAD

**Issue by MarkRoddick** [biemond/biemond-orawls#366]
Hi Edwin,

Again on the non root topic.
I have managed to create a domain, but when re-running puppet after the domain is created the function $found = domain_exists($domain) is unable to locate the domain. This causes the domain extensions template to be executed again which fails as the template has already been applied.

Manifest: `orawls\manifests\domain.pp`
Output: `orawls::domain online_osb_dev /u01/oracle/config/domains/online_osb_dev 1213 does not exists`

Is it something to do with puppet\parser\functions\domain_exists.rb ?

.. ill also submit a pull separate request as I have had to modify RCU to run as non root.

Regards,
Mark

**Comment by MarkRoddick** [comment]
... just to add running as root works without issues

**Comment by biemond** [comment]
you are right 

in lib/facter/orawls.rb I try to find /etc/wls_domains.yaml this or read your override location for non root. ( you need to set this override_wls_domains_file fact on your host.)

```
def get_domains(domain_folder, count_domains)
  # check all domain in a domains folder
  if FileTest.exists?(domain_folder)
    count_domains += 1
    # add domain facts
    get_domain(domain_folder, count_domains)
    # add a full path domain fact
    Facter.add("ora_mdw_domain_#{count_domains}") do
      setcode do
        domain_folder
      end
    end
  end
  count_domains
end

# get wls_domains.yaml file location if overridden
def get_wls_domains_file
  wls_domains_file = Facter.value('override_wls_domains_file')
  if wls_domains_file.nil?
    Puppet.debug 'wls_domains_file is default to /etc/wls_domains.yaml'
  else
    Puppet.debug "wls_domains_file is overridden to #{wls_domains_file}"
    return wls_domains_file
  end
  '/etc/wls_domains.yaml'
end
```

**Comment by biemond** [comment]
for domain information: override_wls_domains_file=[custom_path]/wls_domains.yaml
or set FACTER_override_wls_domains_file=[custom_path]/wls_domains.yaml

for settings infortmation: override_wls_setting_file=[custom_path]/wls_setting.yaml
or set FACTER_override_wls_setting_file=[custom_path]/wls_setting.yaml

**Comment by MarkRoddick** [comment]
Yeah your right however I have set the fact and the wls_domains_file is located in the custom location but for some reason its not working.
Just to test I copied the file to /etc/wls_domains.yaml file and it worked without issues.

This is how I am setting the fact:

```
Facter.add('override_wls_domains_file') do
  setcode do
    '/home/oracle/.puppet/wls_domains.yaml'
  end
end
```

Strange, any ideas why its not picking up the wls_domains.yaml when its in the custom location?

**Comment by biemond** [comment]
Run it in debug mode , it should give you some clues or add some extra debug statements to orawls.rb

I always do the export way on the host vm , not on the puppet master 

or I use this on the host vm

/opt/puppetlabs/facter/facts.d/
/etc/puppetlabs/facter/facts.d/
/etc/facter/facts.d/

and a file like this 

.yaml: YAML data, in the following format:

---
key1: val1
key2: val2
key3: val3

.json: JSON data, in the following format:

{
    "key1": "val1",
    "key2": "val2",
    "key3": "val3"
}

.txt: Key value pairs, in the following format:

key1=value1
key2=value2
key3=value3

**Comment by MarkRoddick** [comment]
My mistake - I had an old copy of the ora_wls module still on the server so it was overwriting the fact from there:

```
Info: Loading facts
Debug: Loading facts from /u01/puppet/environments/online_dev/modules/orawls/lib/facter/orawls.rb
Info: Loading facts
Debug: Loading facts from /u01/puppet/environments/online_dev/modules/orawls_old/lib/facter/orawls.rb
```

Its working fine now - end to end as non root; install, patch, rcu, domain. I just need to send you the new rcu code to cater for non root.

Thanks for your help!

**Comment by biemond** [comment]
awesome
