### ISSUE TITLE
12.2.1 domain creation skipping adminserver configuration

### ISSUE THREAD

**Issue by pymate** [biemond/biemond-orawls#378]
Domain gets created and the adminserver is started up. But any customizations made to the adminserver configuration via server_instances are not being triggered -

Error: create of a domain is not allowed
Error: /Stage[main]/Basic_config/Wls_domain[testdomain]/ensure: change from absent to present failed: create of a domain is not allowed
Notice: /Stage[main]/Basic_config/Wls_adminserver[adminserver_1]: Dependency Wls_domain[dev-evo] has failures: true
Warning: /Stage[main]/Basic_config/Wls_adminserver[adminserver_1]: Skipping because of failed dependencies

This can probably be ignored, but nevertheless something that should be looked at -
Info: adminserver result: WARNING: This is a deprecated script. Please invoke the wlst.sh script under oracle_common/common/bin

**Comment by biemond** [comment]
Hi, 

you have to give me some information , is the subscripe on the adminserver not working?
can you add that code.

I think you got some config error, wls_domain can only modify and in your case it want to do a create so it is not detecting your domain maybe wls_setting is not ok

yeah that can be ignored, they will probably change that path one day.

thanks

**Comment by pymate** [comment]
User error!. wls_setting was changed in between puppet runs..
