### ISSUE TITLE
$target in wls_managedserver is coming as empty

### ISSUE THREAD

**Issue by pymate** [biemond/biemond-orawls#379]
While trying to start managed servers, we see WLST exceptions as the target value is not being passed properly.

Below is the yaml snippet for the managedserver control instance:

```
managedserver_controllers:
  'wlserver1':
     domain_name:          testdomain
     server_type:              'managed'
     target:                       'Server'
     server:                        'wlserver1'
     action:                        'start'
     adminserver_address:  "domain_adminserver_address
     adminserver_port:       *domain_adminserver_port
     nodemanager_secure_listener: false
     nodemanager_port:     5557
     weblogic_user:             "weblogic"
     weblogic_password:     "Password123"
     jsse_enabled:                 true
     download_dir:               *wls_domain_download_dir
     log_output:                     true
```

This is from the debug log -

connect("weblogic","Password123","t3://abcxyz:7001")
state("wlserver1","")
exit()
EOF

As seen above, the value of target is not being passed on even though it is correctly set in the yaml.

**Comment by biemond** [comment]
Hi,

I don't why this happens

I don't see the error 
https://github.com/biemond/biemond-orawls/blob/master/manifests/control.pp#L71

https://github.com/biemond/biemond-orawls/blob/master/lib/puppet/type/wls_managedserver.rb#L46

and 

https://github.com/biemond/biemond-orawls/blob/master/lib/puppet/provider/wls_managedserver/wls_managedserver.rb#L86
