### ISSUE TITLE
Postgres datasource configuration

### ISSUE THREAD

**Issue by giuliana-bezerra** [biemond/biemond-orawls#394]
Does this module support Postgres datasource configuration (wls_datasource)? I can't find resources to load a non-default driver. I have tried the 'post_classpath' resource:

```
wls_setting { 'default':
    user              => $os_user,
    weblogic_home_dir => $wl_home,
    connect_url       => "t3://${listen_address}:${admin_server_port}",
    weblogic_user     => $user,
    weblogic_password => $password,
    post_classpath    => "${dtp_extratoirwl::lib_dir}/postgresql-9.3-1103.jdbc3.jar"
}

wls_datasource { 'ExtratoIRDS':
    ensure     => present,
    drivername => 'org.postgresql.Driver',
    jndinames  => ['jdbc/ExtratoIRDS'],
    target     => [$datasource_target_server],
    targettype => ['Server'],
    url        => $datasource_url,
    user       => $datasource_user,
    password   => $datasource_password
}

```
Even though the datasource is created, I'm getting 'Cannot load driver: org.postgresql.Driver'' when trying to connect to Postgres DB. Am I doing something wrong?

**Comment by biemond** [comment]
Hi, 

I guess you need to add the jar yourself to the domain/lib after the domain creation and before the adminserver starts up. 

like you said, you also need to set the post_classpath on wls_settings to prevent some retrieval errors.

**Comment by giuliana-bezerra** [comment]
It worked! I had only added the jar file to server/lib folder. Thanks a lot!

**Comment by lfallo1** [comment]
saved me as well, thanks.
