### ISSUE TITLE
AD Connection over TLSv1

### ISSUE THREAD

**Issue by adamjk-dev** [biemond/biemond-orawls#398]
So, I have been trying to get this to work.

orawls v1.0.57, latest orautils module

Trying to get WL 12.2.1 talking to our AD server, but it requires TLSv1. So, we were trying to add these options as $extra_arguments to where we could:
```
-Dweblogic.security.SSL.protocolVersion=TLS1 -Dweblogic.security.SSL.minimumProtocolVersion=TLSV1
```

Do you have an example or know on which resources we need to pass these extra arguments to get this working completely?

**Comment by biemond** [comment]
I guess these ones,

- wls_setting for AD configuration
- domain.pp for adminserver
- nodemanager.pp ( maybe , it can affect ssl)
- all wls_server types set this argument on all services

**Comment by adamjk-dev** [comment]
So, does wls_server allow extra_arguments? I don't think it does right now. But, the wls_adminserver (which isn't currently in my code) does allow extra_arguments.

Should we be using wls_adminserver type instead of wls_server combined with wls_setting?

**Comment by biemond** [comment]
it is arguments on wls_server

wls_adminserver, is not a type for setting arguments, it is just for connecting and starting the adminserver through the nodemanager. So hopefully you don't need to set these else it will be a change. wls_adminserver only allows trust , jsee and custom trust stores

**Comment by adamjk-dev** [comment]
Are you sure it is available on wls_server? I get errors when adding it there.

Searching your module doesn't show it there either: https://github.com/biemond/biemond-orawls/search?p=1&q=extra_arguments

**Comment by biemond** [comment]
https://github.com/biemond/biemond-orawls-vagrant-12.2.1/blob/master/puppet/hieradata/admin.example.com.yaml#L328

not extra_arguments

**Comment by biemond** [comment]
after changing you need to subscribe to the auto restart 

also set this on domain.pp 
https://github.com/biemond/biemond-orawls-vagrant-12.2.1/blob/master/puppet/environments/development/modules/orawls/manifests/domain.pp#L25

java_arguments = { "ADM" => "..." }

for wls_settings
https://github.com/biemond/biemond-orawls-vagrant-12.2.1/blob/master/puppet/environments/development/modules/orawls/lib/puppet/type/wls_setting.rb#L35

**Comment by adamjk-dev** [comment]
Touche, I didn't see 'arguments' on the wls_server type, good call. Okay, yeah I am now testing some iterations etc. Thanks for the pointers and examples.

Let me see if I can get it to work with all these locations set.

**Comment by biemond** [comment]
maybe also this on the nodemanager because it can effect ssl

https://github.com/biemond/biemond-orawls-vagrant-12.2.1/blob/master/puppet/environments/development/modules/orawls/manifests/nodemanager.pp#L21

**Comment by adamjk-dev** [comment]
Yeah, I put it on....

1. wls_server {'AdminServer':} - as 'arguments'
2. orawls::control { 'start_admin_server':} - as extra_arguments
3. wls_setting { 'default':} - as extra_arguments
4. orawls::nodemanager { 'create_orawls_nodemanager': } - as extra_arguments
5. orawls::domain { 'create_orawls_domain':} - as java_arguments on ADM
   java_arguments                        => { "ADM" => "-XX:PermSize=256m -XX:MaxPermSize=512m -Xms1024m -Xmx1024m -Dweblogic.Stdout=/logs/TESTDOMAIN/weblogic/AdminServer.out -Dweblogic.Stderr=/logs/TESTDOMAIN/weblogic/AdminServer_err.out -Dweblogic.security.SSL.protocolVersion=TLS1 -Dweblogic.security.SSL.minimumProtocolVersion=TLSV1",},

**Comment by adamjk-dev** [comment]
Maybe it is because of which wlst.sh script we are calling? I see a warning about a deprecation of it:

```
Jan 24 11:19:31 densbb3utajk01 puppet-agent[12096]: adminserver result: WARNING: This is a deprecated script. Please invoke the wlst.sh script under oracle_common/common/bin.
```

And, if I look at both WLST scripts I have on disk, only one takes those CONFIG_JVM_ARGS into account:

```
# cat /app/oracle/wls1221/oracle_common/common/bin/wlst.sh | grep CONFIG_JVM_ARGS
JVM_ARGS="${WLST_PROPERTIES} ${JVM_D64} ${UTILS_MEM_ARGS} ${CONFIG_JVM_ARGS}"
# cat /app/oracle/wls1221/wlserver/common/bin/wlst.sh | grep CONFIG_JVM_ARGS
```

**Comment by biemond** [comment]
No 
it is because of startup.properties inside domain/servers/AdminServer/data/nodemanager/startup.properties

or something like that see 

https://github.com/biemond/biemond-orawls-vagrant-12.2.1/blob/master/puppet/environments/development/modules/orawls/templates/domains/domain.py.erb#L122

https://github.com/biemond/biemond-orawls-vagrant-12.2.1/blob/master/puppet/environments/development/modules/orawls/templates/domains/utils.py.erb#L15

did you recreate the whole vm , domain creation is only done once.

**Comment by adamjk-dev** [comment]
I just tore it all down and re-ran it all, still no love:

```
# cat /projects/TESTDOMAIN/servers/AdminServer/data/nodemanager/startup.properties
Arguments=-XX\:PermSize\=256m -Dweblogic.security.SSL.protocolVersion\=TLS1 -Dweblogic.security.SSL.minimumProtocolVersion\=TLSV1 -XX\:MaxPermSize\=512m -Xms1024m -Xmx1024m -Dweblogic.Stdout\=/logs/TESTDOMAIN/weblogic/AdminServer.out -Dweblogic.Stderr\=/logs/TESTDOMAIN/weblogic/AdminServer_err.out

Notice: /Stage[main]/Profile::Weblogic_adminserver/Wls_server[AdminServer]/sslenabled: sslenabled changed '0' to '1'
Notice: /Stage[main]/Profile::Weblogic_adminserver/Wls_server[AdminServer]/arguments: removing ["-XX:PermSize=256m", "-XX:MaxPermSize=512m", "-Xms1024m", "-Xmx1024m", "-Dweblogic.Stdout=/logs/TESTDOMAIN/weblogic/AdminServer.out", "-Dweblogic.Stderr=/logs/TESTDOMAIN/weblogic/AdminServer_err.out"]
Notice: /Stage[main]/Profile::Weblogic_adminserver/Wls_server[AdminServer]/max_message_size: max_message_size changed '10000000' to '25000000'
Info: modify default/AdminServer
```

ps output:
```
00:00:22 /opt/java/latest/bin/java -server -Xms256m -Xmx512m -XX:CompileThreshold=8000 -Dweblogic.Name=AdminServer -Djava.security.policy=/app/oracle/wls1221/wlserver/server/lib/weblogic.policy -Xverify:none -Djava.system.class.loader=com.oracle.classloader.weblogic.LaunchClassLoader -javaagent:/app/oracle/wls1221/wlserver/server/lib/debugpatch-agent.jar -da -Dwls.home=/app/oracle/wls1221/wlserver/server -Dweblogic.home=/app/oracle/wls1221/wlserver/server weblogic.Server
```

**Comment by adamjk-dev** [comment]
The problem might be.... because all of your code uses these environment variables and such from other places.

But, we have a restart on the weblogic server that we hardcoded after we did the LDAP integration (a long time ago we had to do this)
```
command     => "/projects/${domain_name}/bin/stopWebLogic.sh && nohup /projects/${domain_name}/bin/startWebLogic.sh &",
```

But, when we call this, we aren't enforcing all of those environment variables etc. Should we be triggering or notifying another resource instead?

**Comment by biemond** [comment]
no scripts, this should work.
the nodemanager should pick the startup.properties and everything should use the nodemanager to start.

I will do some tests.

**Comment by adamjk-dev** [comment]
Well, what I am saying, is that in our own code, we restart the AdminServer by using that exec above. But, we don't set the environment variables like your call does.

Your call: https://github.com/biemond/biemond-orawls/blob/da3dadee7dab4d8a5f938165b90a40bde2ac9de7/lib/puppet/provider/wls_adminserver/wls_adminserver.rb#L65

Whereas, we are just calling:
/projects/${domain_name}/bin/stopWebLogic.sh && nohup /projects/${domain_name}/bin/startWebLogic.sh &
(And not passing any environment variables in)

**Comment by biemond** [comment]
yeah with scripts you are on your own.

orawls is doing everything from the nodemanager and with startScriptEnable it will also invoke the scripts.

**Comment by adamjk-dev** [comment]
Right, I am seeing the gap now (all of these environment variables). So, what should we be doing instead? Should we be notifying the wls_server resource for the AdminServer or what? Is there a built-in way to trigger a restart on the AdminServer?

As it stands, we don't use the wls_adminserver type, but instead use the wls_server resource etc.

**Comment by biemond** [comment]
I guess it works for me when I set this  -Daa=1 -Dbb=2 on nodemanager, domain.pp and do start of the adminserver

````
oracle   20320 20269  4 20:37 ?        00:00:03 /usr/java/latest/bin/java -server -Xms32m -Xmx200m -Dcoherence.home=/opt/oracle/middleware12c/wlserver/../coherence -Dbea.home=/opt/oracle/middleware12c/wlserver/.. -Dweblogic.ssl.JSSEEnabled=true -Dweblogic.security.SSL.enableJSSE=true -Dweblogic.security.TrustKeyStore=CustomTrust -Dweblogic.security.CustomTrustKeyStoreFileName=/vagrant/truststore.jks -Dweblogic.security.CustomTrustKeystorePassPhrase=welcome -Daa=1 -Dbb=2 -Dweblogic.RootDirectory=/opt/oracle/wlsdomains/domains/Wls1221 -Djava.system.class.loader=com.oracle.classloader.weblogic.LaunchClassLoader -Djava.security.policy=/opt/oracle/middleware12c/wlserver/server/lib/weblogic.policy -Dweblogic.nodemanager.JavaHome=/usr/java/latest weblogic.NodeManager -v


oracle   20612 20561 49 20:37 ?        00:00:33 /usr/java/latest/bin/java -server -Xms256m -Xmx512m -Dweblogic.Name=AdminServer -Djava.security.policy=/opt/oracle/middleware12c/wlserver/server/lib/weblogic.policy -Dweblogic.ProductionModeEnabled=true -Dweblogic.system.BootIdentityFile=/opt/oracle/wlsdomains/domains/Wls1221/servers/AdminServer/security/boot.properties -Dweblogic.nodemanager.ServiceEnabled=true -Dweblogic.nmservice.RotationEnabled=true -Daa=1 -Dbb=2 -Djava.system.class.loader=com.oracle.classloader.weblogic.LaunchClassLoader -javaagent:/opt/oracle/middleware12c/wlserver/server/lib/debugpatch-agent.jar -da -Dwls.home=/opt/oracle/middleware12c/wlserver/server -Dweblogic.home=/opt/oracle/middleware12c/wlserver/server weblogic.Server
oracle   20850 20800 77 20:37 ?        00:00:36 /usr/java/latest/bin/java -server -Xms256m -Xmx512m -Dweblogic.Name=AdminServer -Djava.security.policy=/opt/oracle/middleware12c/wlserver/server/lib/weblogic.policy -Dweblogic.ProductionModeEnabled=true -Dweblogic.system.BootIdentityFile=/opt/oracle/wlsdomains/domains/plain_Wls/servers/AdminServer/security/boot.properties -Dweblogic.nodemanager.ServiceEnabled=true -Dweblogic.nmservice.RotationEnabled=true -Daa=1 -Dbb=2 -Djava.system.class.loader=com.oracle.classloader.weblogic.LaunchClassLoader -javaagent:/opt/oracle/middleware12c/wlserver/server/lib/debugpatch-agent.jar -da -Dwls.home=/opt/oracle/middleware12c/wlserver/server -Dweblogic.home=/opt/oracle/middleware12c/wlserver/server weblogic.Server

````

startup.properties

[oracle@admin domains]$ cd Wls1221/servers/AdminServer/data/nodemanager/
[oracle@admin nodemanager]$ cat startup.properties
Arguments=-Daa\=1 -Dbb\=2

**Comment by adamjk-dev** [comment]
Right, so that is working. The only problem for us now is how we are restarting the AdminServer after adding an AuthProvider. So, what is the recommended way to restart the AdminServer? 

Should we be notifying the wls_server resource for the AdminServer or what? Is there a built-in way to trigger a restart on the AdminServer?

As it stands, we don't use the wls_adminserver type, but instead use the wls_server resource etc.

**Comment by biemond** [comment]
with wls_adminserver and do a subscribe , see the 12.2.1 vagrant box with wls_server

**Comment by adamjk-dev** [comment]
So do we need to have wls_adminserver resource? What if we don't have one right now?

**Comment by biemond** [comment]
yes add it,doesn't do much. it just restart the adminserver

**Comment by adamjk-dev** [comment]
Okay, good to know, thanks. I will have to try that. I think we owe you some food/beverages at least by now, huh?

**Comment by adamjk-dev** [comment]
So, happy to report that it is all working now. The extra args and everything is functioning as expected, synced with AuthProvider over TLSv1 in WL 1221, and added in the wls_adminserver resource and ripped out our old stuff to restart. Thanks for the help, as always. The module is awesome.
