### ISSUE TITLE
What is the best way to add group to global role

### ISSUE THREAD

**Issue by wijetnga** [biemond/biemond-orawls#401]
What is the best way to add group to global role? and best way to create multiple users to "DefaultAuthenticator"

Here is example of python code for adding group... 

connect(userConfigFile=sys.argv[2],userKeyFile=sys.argv[3],url='t3://' + sys.argv[1])
envName = sys.argv[4]
sr = cmo.getSecurityConfiguration().getDefaultRealm();
rm = sr.lookupRoleMapper('XACMLRoleMapper');
rm.setRoleExpression(None,'Admin','Grp(Administrators)|Grp(WebLogicConsoleAdmin' + envName + ')');

_______________________________________________________________

code for adding user python...

connect(userConfigFile=sys.argv[2],userKeyFile=sys.argv[3],url='t3://' + sys.argv[1])

print "Creating deployer user ..."
atnr=cmo.getSecurityConfiguration().getDefaultRealm().lookupAuthenticationProvider("DefaultAuthenticator")
atnr.createUser('deployer','password','deployment user')
atnr.addMemberToGroup('Deployers','deployer')
print "Created deployer successfully"

**Comment by biemond** [comment]
hi,

Please check the vagrant box and docs.

we support this 
https://github.com/biemond/biemond-orawls/blob/master/README.markdown#wls_group
https://github.com/biemond/biemond-orawls/blob/master/README.markdown#wls_user

Just define your users and add them to the groups and you can specify the authenticator

thanks

**Comment by wijetnga** [comment]
Thanks I got that working. How do I add groups to global roles (XACMLRoleMapper)?

Can you please give me a n example?

Thanks in advanced.

**Comment by wijetnga** [comment]
How do I add groups and users to global roles (XACMLRoleMapper)?

**Comment by wijetnga** [comment]
Any help on this?

**Comment by biemond** [comment]
like this

I didn't test it out myself but this should work

`````
wls_role { 'default/Deployer':
  ensure     => 'present',
  expression => 'Grp(Deployers)',
  realm      => 'myrealm',
}
````

**Comment by wijetnga** [comment]
Interesting...
  I am able to add to "default/Deployer"following works fine but failed when I try to add to "'default/Admin'". Any idea? Below are my settings..

wls_role { 'default/Deployer':
  ensure     => 'present',
  expression => 'Usr(myAduserName)',
  realm      => 'myrealm',
}

wls_role { 'default/Admin':
    ensure     => $ensure_weblogic_user,
    expression => 'Usr(myAduserName)',
    realm      => 'myrealm',
  }

**Comment by biemond** [comment]
maybe more restrictive

I don't know if you should add user to a role, maybe a group is better
is the user adding to the deployer or administrator group not enough. these are already part of those roles

here are some more examples.

````
# this will use default as wls_setting identifier
wls_role { 'default/Deployer':
  ensure     => 'present',
  expression => 'Grp(Deployers)',
  realm      => 'myrealm',
}

wls_role { 'default/OracleSystemRole':
  ensure     => 'present',
  expression => 'Grp(OracleSystemGroup)',
  realm      => 'myrealm',
}

wls_role { 'default/Admin':
  ensure     => 'present',
  expression => '?weblogic.entitlement.rules.AdministrativeGroup(Administrators)',
  realm      => 'myrealm',
}

wls_role { 'default/Anonymous':
  ensure     => 'present',
  expression => 'Grp(everyone)',
  realm      => 'myrealm',
}
````

**Comment by wijetnga** [comment]
Thanks,
How do I add two groups to role? Below ex didn't work

wls_role { 'default/Deployer':
  ensure     => 'present',
  expression => 'Grp(A), Grp (B)',
  realm      => 'myrealm',
}

**Comment by biemond** [comment]
one way to find out is to do reverse engineering. Do it from the wls console after that do this  on the admin vm

puppet resource wls_role
or 
puppet resource wls_role default/Deployer

**Comment by wijetnga** [comment]
Works...

wls_role { 'default/Deployer':
ensure => 'present',
expression => 'Grp(A)|Grp (B)',
realm => 'myrealm',
}
