### ISSUE TITLE
Permissions (mode) of 'oraInst.loc' file

### ISSUE THREAD

**Issue by Edmilson-JR** [biemond/biemond-orawls#406]
Greetings, Edwin.

I noticed that, in release 1.0.23, the mode (file's permissions) of oraInst.loc was changed from '0644' to '0755'.

Do you remember why was that?

I'm having problem with the security area because of that. They want the file to have 0644 permission, but i can't do that currently.

So I've made some local changes to grant the management of file's mode and like to ask you if you agree with that.

The changes were made in ''fmw.pp' and in "utils::orainst.pp".

```
define orawls::fmw(
  ...
  $oraInst_mode         = '0755',
)

orawls::utils::orainst { "create oraInst for ${name}":  # <= line 483
      ora_inventory_dir => $oraInventory,
      os_group          => $os_group,
      mode              => $oraInst_mode,
    }
```
and
```
define orawls::utils::orainst
(
  ...
  $mode              = '0755',
  $orainstpath_dir   = hiera('orainstpath_dir', undef),
)

    'SunOS': {
          ...
          mode   => $mode,
        }
      }

      file { "${oraInstPath}/oraInst.loc":
        ...
        mode    => $mode,
    }
```

Thanks.

**Comment by Edmilson-JR** [comment]
By the way, I have the same issue with 'nodemanager.properties' file's permissions.

Locally, I did the same thing that I said above and it's working.

So, if you can think about this too...

Thanks.

**Comment by biemond** [comment]
Hi,

I don't why I even add this to the release notes. I guess 0644 should work for all situations
everyone has read access.
https://github.com/biemond/biemond-orawls/commit/119a398d64923475ff1589a7e091215807aec630

thanks

**Comment by Edmilson-JR** [comment]
So can I make a PR?

If so, with parameterized value or with only '0644'?

A parameterized value is better for me, but you are the boss...

lol

**Comment by biemond** [comment]
I am making a puppet 4 only version, I will use your defaults and try it out ( I need to test everything again)
https://github.com/biemond/biemond-orawls/tree/puppet4
https://github.com/biemond/biemond-orawls/blob/puppet4/data/common.yaml#L8

**Comment by biemond** [comment]
PR with just 0644 and try to run puppet multiple times if that works I don't see any problems with 0644

**Comment by Edmilson-JR** [comment]
All right! Thanks, man.

I've run it here multiple times, but i'll run it a little bit more to ensure...

And the 'nodemanager.properties' file's permisson (https://github.com/biemond/biemond-orawls/blob/da3dadee7dab4d8a5f938165b90a40bde2ac9de7/manifests/nodemanager.pp#L202)?

Can I change this too? With more security (0640 mode) ?

**Comment by biemond** [comment]
lets also change that one

**Comment by Edmilson-JR** [comment]
Now that the PR was accepted, I'll close this issue, ok?
