### ISSUE TITLE
Looking for assistance with wlstexec

### ISSUE THREAD

**Issue by userMar2017** [biemond/biemond-orawls#415]
Hi,

Looking for some assistance with executing wlst to create a machine. I am unable to get it to work.

**Error** 

Error: Evaluation Error: Error while evaluating a Resource Statement, Unknown resource type: 'orawls::wlstexec' at create_machine.pp:3:1 on node learning.puppetlabs.vm

**Puppet manifest**

include orawls

orawls::wlstexec{'createMachine_node1':
  version                    => 1111,
  domain_name                => "domain_name",
..
..

**Comment by biemond** [comment]
Hi,

is there a reason why you don't use wls_machine plus wls_settings types. wlstexec is very old and now we have more than 50 native wls types , no need to use something so generic as wlstexec and I made it hidden and undocumented so people won't use it. hehe

Thanks Edwin

**Comment by cwyswy11555** [comment]
Wow, I was not expecting a response so quickly. Would you be able to point me to the relevant docs and maybe examples.

Thanks again Edwin !

**Comment by biemond** [comment]
check the readme and the all example vagrant boxes, only requirement is that you set wls_setting else I don't know howto connect to the domain.

see 
https://github.com/biemond/biemond-orawls-vagrant-12.2.1/blob/master/puppet/hieradata/admin.example.com.yaml#L85

https://github.com/biemond/biemond-orawls-vagrant-12.2.1/blob/master/puppet/hieradata/admin.example.com.yaml#L286

good luck

**Comment by cwyswy11555** [comment]
Many thanks Edwin. I was finally able to get it to work but realized that no matter what I set in the puppet manifest it simply picks up the settings from /etc/wls_setting.yaml file.

For now, I overrode the setting ( using override_wls_setting_file ). But the machine creation piece works as defined in the puppet manifest.

wls_setting { 'default':
  user                         => 'xxxx',
  weblogic_home_dir            => '/appl/oracle/middleware/wlserver',
  connect_url                  => "t3://xxx:7001",
  weblogic_user                => 'xxx',
  weblogic_password            => 'xxx',
  use_default_value_when_empty => false,
}

wls_machine { 'xxxx':
  ensure        => 'present',
  listenaddress => '1.2.3.4',
  listenport    => '5556',
  machinetype   => 'UnixMachine',
  nmtype        => 'SSL',
}

**Comment by biemond** [comment]
it works on the title of the machine so wls_machine aaaa will always use the default wls_setting. wls_machine enva/aaaa as title will use enva wls_setting entry. this way you can control the domain on which it is executed

**Comment by cwyswy11555** [comment]
Got it. Thanks again !
