### ISSUE TITLE
set the NodeManager Home directory

### ISSUE THREAD

**Issue by rssh22** [biemond/biemond-orawls#416]
Hello Biemond,

I've seen that the NodeManager Home directory is hardcoded in manifests/nodemanager.pp.

In production environments sometimes is useful to have a nodemanager instance per domain. So you can stop a nodemanager instance without affecting the others. Having the possibility of choosing different nodemanager homes gives you the possibility of having different nodemanager instances.

Well, maybe you can consider to add this new feature.

Regards,

Raúl

**Comment by biemond** [comment]
Hi,

you mean for 11g which has 1 per mdw home, with 12c I only support per domain
I don't think this is a common requirement because nodemanager is only used when someone start or stops something and that does not happen too much on a day. Plus they get a message in the console.

Thanks,
