### ISSUE TITLE
Help with orawls::weblogic

### ISSUE THREAD

**Issue by userMar2017** [biemond/biemond-orawls#421]
Hi Ed,

Seeking some help with the following -

When I attempt the following, it works as expected.

class{'orawls::weblogic':
  version              => 1213,
  filename             => 'fmw_12.1.3.0.0_wls.jar',
  fmw_infra            => false,
  jdk_home_dir         => 'some_dir',
..
..
}
include orawls::weblogic

However, when I change it to the following it does not. What am I doing wrong ?

include orawls
orawls::weblogic { '1213' :
  version              => '1213',
  filename             => 'fmw_12.1.3.0.0_wls.jar',
  fmw_infra            => false,
  jdk_home_dir         => 'some_dir',
..
..
}

**Comment by biemond** [comment]
Hi,

version should be an integer. Are you using the latest because then you will get an attribute value error.

**Comment by userMar2017** [comment]
Hi Ed,

Yes, I already tried using integer of 1213 but also attempted a few other options. I pasted the wrong one. Sorry.

And yes, I downloaded it recently. Error I receive is the one below 

Error: Evaluation Error: Error while evaluating a Resource Statement, Unknown resource type: 'orawls::weblogic' at <file_name>.pp:3:1 on node learning.puppetlabs.vm

Line 3 is orawls::weblogic{'1213':

**Comment by biemond** [comment]
Are you using puppet 4 and you need to change your config because everything is changed,

no default hiera lookup , use the weblogic class and I will inherit the params for these. 
Can you check the readme or 1 of the new vagrant boxes.

you want to use the define and not class

````
   class{'orawls::weblogic':
     version                   => 12212,
     filename                  => 'fmw_12.2.1.2.0_wls.jar',
     jdk_home_dir              => '/usr/java/latest',
     oracle_base_home_dir      => "/opt/oracle",
     middleware_home_dir       => "/opt/oracle/middleware12c",
     weblogic_home_dir         => "/opt/oracle/middleware12c/wlserver",
     download_dir              => "/var/tmp/install",
     puppet_download_mnt_point => "/software",
     log_output                => true,
     remote_file               => false
     wls_domains_dir           => '/opt/oracle/wlsdomains//domains',
     wls_apps_dir              => '/opt/oracle/wlsdomains/applications',
   }
````

**Comment by userMar2017** [comment]
The class already works for me so it looks like I am on the right track then

class{'orawls::weblogic':
version => 1213,
filename => 'fmw_12.1.3.0.0_wls.jar',
