### ISSUE TITLE
Issue in FMW SOA 12.2.1 extension installation

### ISSUE THREAD

**Issue by oscarbeltran** [biemond/biemond-orawls#423]
I am using your module to install Oracle Fusion Middleware SOA 12.2.1 and I have found problems in the installation of SOA Core Extension. 
I'm using the defined type "orawls::domain" with de param "domain_template => 'soa'". The domain and bbdd schemas creation works fine but the extension installation always gives the following error (set() failed):

  Notice: /Stage[main]/Profile::Orawls::Fmw::Admin_server/Orawls::Domain[dominiopru]/Exec[execwlst dominiopru extension dominiopru]/returns: SEVERE: Error: set() failed.

In this part of the puppet execution is applying the exec { "execwlst ${domain_name} extension ${title}" resource and is using de wlst .py file generated with the 'orawls/domains/extensions/soa_template.py.erb' template.
Analyzing the soa_template.py.erb file I found the problem in this part:

````
if WEBLOGIC_VERSION not in [1213, 1221, 12211, 12212]:
    cd('/')
    # destroy the normal one
    delete('LocalMachine', 'Machine')
    print('change the default machine LocalMachine with type Machine')
    create_machine('UnixMachine', 'LocalMachine', '<%= @adminserver_address %>',NODEMANAGER_SECURE_LISTENER)

print 'Change AdminServer'
cd('/Servers/' + ADMIN_SERVER)
set('Machine', 'LocalMachine')
````
It's trying to make a set('Machine', 'LocalMachine') and the 'LocalMachine' does not seem to exist (our version is 1221).
I have solved the problem by adding the following line (create_machine):

````
if WEBLOGIC_VERSION not in [1213, 1221, 12211, 12212]:
    cd('/')
    # destroy the normal one
    delete('LocalMachine', 'Machine')
    print('change the default machine LocalMachine with type Machine')
    create_machine('UnixMachine', 'LocalMachine', '<%= @adminserver_address %>',NODEMANAGER_SECURE_LISTENER)

create_machine('UnixMachine', 'LocalMachine', '<%= @adminserver_address %>',NODEMANAGER_SECURE_LISTENER)
print 'Change AdminServer'
cd('/Servers/' + ADMIN_SERVER)
set('Machine', 'LocalMachine')
````

With this change the extension installation works fine

I hope you analyze the problem to implement the corresponding correction

**Comment by biemond** [comment]
Thanks,

I will take a look, but LocalMachine should always be there unless you changed the name in here 

https://github.com/biemond/biemond-orawls/blob/master/manifests/domain.pp#L20
and
https://github.com/biemond/biemond-orawls/blob/master/templates/domains/domain.py.erb#L50

**Comment by oscarbeltran** [comment]
Yes, I'm changing the default value of the param $adminserver_machine_name
For now, I will try to leave the default

Thanks

**Comment by biemond** [comment]
Great, after you are done with the domain you can do what you want. Create a new machine and change the admin service in puppet with the wls types.
