### ISSUE TITLE
Issue after creating OHS instance

### ISSUE THREAD

**Issue by userMar2017** [biemond/biemond-orawls#426]
I install OHS in standalone mode and use the "orawls::domain" to create the OHS instance. The instance gets created successfully however, after a few minutes it seems to overwrite mod_wl_ohs.conf as shown below. The "IncludeOptional" directive prevents OHS from starting up. Also, we need the original mod_wl_ohs.conf anyway.

I guess I could modify the file in "files/mod_wl_ohs_12c.conf" but am hoping there is a configuration setting someplace to prevent this from taking place.

Kindly assist.

Original
```
# NOTE : This is a template to configure mod_weblogic. 

LoadModule weblogic_module   "${PRODUCT_HOME}/modules/mod_wl_ohs.so"

# This empty block is needed to save mod_wl related configuration from EM to this file when changes are made at the Base Virtual Host Level
<IfModule weblogic_module>
#      WebLogicHost <WEBLOGIC_HOST>
#      WebLogicPort <WEBLOGIC_PORT>
#      MatchExpression *.jsp
</IfModule>

# <Location /weblogic>
#      SetHandler weblogic-handler
#      PathTrim /weblogic
#      ErrorPage  http:/WEBLOGIC_HOME:WEBLOGIC_PORT/
#  </Location>
```

Modified one
```
# NOTE: This is a template to configure mod_weblogic, generated by Puppet.

LoadModule weblogic_module "${PRODUCT_HOME}/modules/mod_wl_ohs.so"

IncludeOptional mod_wl_ohs.d/*.conf
```

**Comment by biemond** [comment]
Hi ,

what is the fmw version you are using and are you using the puppet 4 module of orawls.

I tested it in this box, https://github.com/biemond/biemond-orawls-vagrant-ohs-puppet4
and this is working for me 

https://github.com/biemond/biemond-orawls-vagrant-ohs-puppet4/blob/master/puppet/hieradata/ohs1221.example.com.yaml#L120

Thanks

**Comment by userMar2017** [comment]
Hi Ed,

I am using 12.1.3.

Is there anyway to disable that mod_wl_ohs configuration all together ?

**Comment by biemond** [comment]
It is done here 
https://github.com/biemond/biemond-orawls/blob/puppet4/manifests/domain.pp#L725

but why is it failing , what is the error you get. 
for 12c I had to use IncludeOptional instead of Include mod_wl_ohs.d/*.conf

**Comment by userMar2017** [comment]
Hi Ed,
Here it is 

<2017-04-06 11:54:14> <INFO> <OHS-0> <Syntax error on line 5 of <DOMAIN_HOME>/config/fmwconfig/components/OHS/instances/ohs1/mod_wl_ohs.conf:><2017-04-06 11:54:14> <INFO> <OHS-0> <Invalid command 'IncludeOptional', perhaps misspelled or defined by a module not included in the server configuration>
<2017-04-06 11:54:14> <INFO> <OHS-0> <<ORACLE_HOME>/ohs/bin/httpd.sh httpd.worker -k start -f <DOMAIN_NAME>/config/fmwconfig/components/OHS/instances/ohs1/httpd.conf: exit 
status = 1>

**Comment by userMar2017** [comment]
To add to this, we really need the default configuration in the mod_wl_ohs.conf file

**Comment by biemond** [comment]
Ok , good to know 

So this should be at least 1213 and I can make it optional

```
if ( $version <= 1212 ){
        $source_mod = 'puppet:///modules/orawls/mod_wl_ohs.conf'
      } else {
        $source_mod = 'puppet:///modules/orawls/mod_wl_ohs_12c.conf'
      }
```

**Comment by userMar2017** [comment]
Hi Ed,

Hate to be pushy but we are going all out with your modules :) How soon can you provide a fix ?

I can switch that entry from 1212 to 1213 as a quick fix if its going to take time.

**Comment by biemond** [comment]
Soon, are you using the puppet 4 version of orawls.

**Comment by userMar2017** [comment]
How can I check ?

**Comment by biemond** [comment]
what version of puppet ( puppet -v)  you are using and also look at the metadata.json of orawls.

**Comment by userMar2017** [comment]
Puppet is 4.8.2
metadata.json contains

      "name": "puppet",
      "version_requirement": ">=4.3.0"

**Comment by biemond** [comment]
perfect, I will publish a fix

**Comment by biemond** [comment]
you can the download the zip from here 
https://github.com/biemond/biemond-orawls/tree/puppet4

I only put the check on 1213 instead of 1212

**Comment by userMar2017** [comment]
It works now ; the contents are given below. The original entries are still getting overwritten, but at least it does not fail during startup. I will modify the file as per my requirements later.

Thanks Ed for your swift response to this issue !

LoadModule weblogic_module "${PRODUCT_HOME}/modules/mod_wl_ohs.so"

Include mod_wl_ohs.d/*.conf
