### ISSUE TITLE
OHS Install : Local installation

### ISSUE THREAD

**Issue by userMar2017** [biemond/biemond-orawls#427]
-- I am using OHS 12.1.3

-- If I set "remote_file" to "true", the installation fails with the following error

Error: Could not find command '/tmp/puppet_binary/webtier1213/fmw_12.1.3.0.0_ohs_linux64.bin'
Error: /Stage[main]/XXX::Ohs::Install_ohs1213/Orawls::Fmw[webtier1213]/Exec[install webtier1213]/returns: 

change from notrun to 0 failed: Could not find command '/tmp/<tmp_dir>/webtier1213/fmw_12.1.3.0.0_ohs_linux64.bin'

-- To fix this I had to modify

File :  orawls/ manifests/fmw.pp
 
From
    779         command     => "${install}${download_dir}/${sanitised_title}/${binFile1} ${command} -invPtrLoc 
${oraInstPath}/oraInst.loc -ignoreSysPrereqs -jreLoc ${jdk_home_dir}",
 
To
    779         command     => "${install}${download_dir}/${binFile1} ${command} -invPtrLoc 
${oraInstPath}/oraInst.lo        c -ignoreSysPrereqs -jreLoc ${jdk_home_dir}",

**Comment by userMar2017** [comment]
To be clear, I am requesting that you review the change I have proposed and if you agree, modify it at the source.

**Comment by biemond** [comment]
Hi,

it goes wrong over here I expect a zip and not a bin
like this "fmw_12.2.1.2.0_ohs_linux64_Disk1_1of1.zip"

```
    # for performance reasons, download and extract or just extract it
    if $remote_file == true {
      file { "${download_dir}/${fmw_file1}":
        ensure => file,
        source => "${puppet_download_mnt_point}/${fmw_file1}",
        mode   => lookup('orawls::permissions'),
        owner  => $os_user,
        group  => $os_group,
        backup => false,
        before => Exec["extract ${fmw_file1} for ${name}"],
      }
      $disk1_file = "${download_dir}/${fmw_file1}"
    } else {
      $disk1_file = "${puppet_download_mnt_point}/${fmw_file1}"
    }

    exec { "extract ${fmw_file1} for ${name}":
      command   => "unzip -o ${disk1_file} -d ${download_dir}/${sanitised_title}",
      creates   => $createFile1,
      path      => $exec_path,
      user      => $os_user,
      group     => $os_group,
      timeout   => 0,
      cwd       => $temp_dir,
      logoutput => false,
      require   => Orawls::Utils::Orainst["create oraInst for ${name}"],
    }
```

**Comment by userMar2017** [comment]
Hi Ed,

Does it mean I cannot use a "bin" file ? Note that it works after I made the change that I pointed out earlier.

While troubleshooting, I found that it tries to access the following block of code

    778       exec { "install ${sanitised_title}":
    779         command     => "${install}${download_dir}/${sanitised_title}/${binFile1} ${command} -invPtrLoc 

${oraI        nstPath}/oraInst.loc -ignoreSysPrereqs -jreLoc ${jdk_home_dir}",
    780         environment => "TEMP=${temp_dir}",
    781         timeout     => 0,
    782         creates     => $oracleHome,
    783         cwd         => $temp_dir,
    784         path        => $exec_path,
    785         user        => $os_user,
    786         group       => $os_group,
    787         logoutput   => $log_output,
    788         require     => [File["${download_dir}/${sanitised_title}_silent.rsp"],
    789                         Orawls::Utils::Orainst["create oraInst for ${name}"],
    790                         Exec["extract ${fmw_file1} for ${name}"],],
    791       }

**Comment by biemond** [comment]
I know probably the extract doesn't raise an error but it needs a zip like you get from OTN or edelivery, it works for you now but it won't work if you also need to extract the zip else I need to add an extra extra parameter to fmw

**Comment by userMar2017** [comment]
I checked OTN and edelivery but did not find a zip file for 12.1.3. I can recheck.

**Comment by smseidl** [comment]
I was running into the same issues with the .bin file… I was able to work around it by manually zipping the bin file.  Is that an option for you?

Edwin,  if you are requiring zip files, should you put check in to ensure you get a zip, and fail with a clear message if you get something else?

Scott Seidl
Schneider
(920) 592-2163
www.schneider.com<http://www.schneider.com>
Mail Stop Code:  US.GRB.01.03.11

The information contained in this email message may be privileged, confidential and protected from disclosure, and no waiver of any privilege is intended. If you are not the intended recipient, any dissemination, distribution or copying is strictly prohibited. If you think that you have received this email message in error, please email the sender and delete all copies.

**Comment by userMar2017** [comment]
On OTN, for OHS 12.1.3, what I see is file "V44417-01.zip" ; that in turn contains the bin file. Based on what Scott noticed, maybe I can rename that file to fmw_12.1.3.0.0_ohs_linux64.zip and see what happens

**Comment by biemond** [comment]
They removed the old 12c version from OTN , I still see 11g and 12.2.1 , so they are probably are only on edelivery.

No add it to a zip , not rename. 

Indeed I can check for zip as extension but so much more to do and in the examples I am always using zip for full OUI or bin.

**Comment by userMar2017** [comment]
I will try V44417-01.zip as input and let you know the result

**Comment by userMar2017** [comment]
All right, once I drop the zip file it works.

One problem is that even if I set "remote_file" to "false", it only deletes the vxxxx.zip file in the tmp folder. It does *not* delete the "webtier1213/fmw_12.1.3.0.0_ohs_linux64.bin" in the tmp folder. Is there any fix for this ?

**Comment by biemond** [comment]
Not yet , 

I need to move all code inside this check
https://github.com/biemond/biemond-orawls/blob/puppet4/manifests/fmw.pp#L565
else it will happen again in all puppet runs, after this I can do a cleanup of the local files

**Comment by biemond** [comment]
fixed
