### ISSUE TITLE
Changing Root Directory in For managed server .

### ISSUE THREAD

**Issue by piusranjan** [biemond/biemond-orawls#430]
Hi Biemond,
 We are installing a  weblogic cluster in 2 linux VM.

Installation domain location is as below:
Machine1 --> Admin Server > /myprod/users/biemond/JEE/myprod/WLS/myprodDomain( Location where Admin server will be installed)
Machine2 >Managed Server>/myprod/users/pius/JEE/myprod/WLS/myprodDomain  (Managed server will be installed)
And below is the resource to create manage server isntance.
```
managedserver_instances:
    "%{::cluster_name}":
        "%{hiera('domain_name')}/%{hiera('myproddemocluster_mngsrv_name')}":
            ensure:                         'present'
            arguments:                      "%{hiera('jvm_arguments')} %{hiera('additional_jvm_arguments')}"
            classpath:                      "%{hiera('server_classpath')}"
            listenaddress:                  "%{hostname}"
            listenport:                     "%{::managed_port}"
            listenportenabled:              '1'
            logfilename:                    "%{hiera('jee_logs_dir')}/%{hiera('domain_name')}/%{hiera('myproddemocluster_mngsrv_name')}/%{hiera('myproddemocluster_mngsrv_name')}.log"     
            sslenabled:                     '0'
            jsseenabled:                    '0'     
            sslhostnameverificationignored: '1'
            two_way_ssl:                    '0'
            client_certificate_enforced:    '0'  
            machine:                        "%{hostname}"
            server_parameters:              "%{::cluster_name}" 
```
Installation of Admin server is fine. But when it is trying to to install managed server , it is failing in  below code
C:\Users\psatpath\Desktop\Data\ACD\biemond-orawls-1.0.59\files\providers\wls_server/create.py.erb

```
DOMAIN_PATH = get('RootDirectory')    create_boot_properties_file(DOMAIN_PATH+'/servers/'+name+'/security','boot.properties',weblogicUser,weblogicPassword)
```

As  get('RootDirectory')  is always returning    /myprod/users/biemond/JEE/myprod/WLS/myprodDomain  , its is not able to create boot.properties in the Machine2

To solve the above problem,  we have to create  user biemond in  machine2 and we have to install  using biemond user .

Is this a defect or  we  can change the root directory of managed server . If yes what attribute we need to pass. Please suggest us.

Thanks,
Pius

**Comment by biemond** [comment]
Hi,

you need to do everything on admin host, when you are totally finished you can do pack the domain as the last step. After this you move to the 2nd vm

here you need to create all users, install wls etc ( you can do this in parallel on all vm's). After this you can copy domain, configure the nodemanager and start it.

So I don't what you are doing and in which order.

**Comment by piusranjan** [comment]
This is the  order  we are doing :   

1) We are creating  Admin  and in first VM .
2) Then we are creating Managed server in second vm   and targeting it to cluster.

Thanks,
Pius

**Comment by biemond** [comment]
don't do that it is not designed for that, do everything first on admin ( all domain things) and then do 2nd vm, only copydomain and do nodemanager things

**Comment by piusranjan** [comment]
Then  how we can  achieve auto scaling  ?We might have to add a node with managed server with minimum impact .

**Comment by biemond** [comment]
there is no auto scaling in weblogic, it is a licensing monster plus scaling up inside the machine is always better than adding the overhead of a cluster. 
But you can already add some nodes who don't exists yet and provision when you need then or at least keep the domain directory the same, there is no reason to change the domain dir.

**Comment by piusranjan** [comment]
Thanks Biemond. Right now we are not doing pack domain and copy domain. Is there any guideline document   provided by oracle /bea to do in that way ?

**Comment by biemond** [comment]
yeah it is the only way. read all the docs

**Comment by piusranjan** [comment]
Thanks Biemond.
