### ISSUE TITLE
oraInst Path : Unable to customize

### ISSUE THREAD

**Issue by userMar2017** [biemond/biemond-orawls#435]
Hi Edwin,

I am unable to customize the patch of oraInst.loc file.

1. I added a variable override_orainst_dir ; it did not help

2. Added the following ; it did not help

  orainstpath_dir      => "/some_other_folder",

3. And tried a few other things, which did not help either

Can you please provide some guidance ?

**Comment by biemond** [comment]
Hi,

I see these parameters

https://github.com/biemond/biemond-orawls/blob/puppet4/manifests/weblogic.pp#L63
or
https://github.com/biemond/biemond-orawls/blob/puppet4/manifests/weblogic_type.pp#L61

but it not passed on to this
https://github.com/biemond/biemond-orawls/blob/puppet4/manifests/utils/orainst.pp#L14

So I can easily fix this.

but you also need to set it on fmw.pp and set these facts override_orainst_dir=[custom_path] or set FACTER_override_orainst_dir=[custom_path]

Thanks

**Comment by userMar2017** [comment]
Great. Let me know when its correct and I will attempt again.

**Comment by biemond** [comment]
Can you download and use this version https://github.com/biemond/biemond-orawls/tree/puppet4

This should work. Let me know if it works so I can push a new release

**Comment by userMar2017** [comment]
I ran into a few other issues ; probably unrelated.

But yes, it picks up the new path now. The file oraInst.loc is owned by user root but I can always change it later.

Thanks again Edwin for helping out so quickly.

Do let me know once a new release has been published.

**Comment by biemond** [comment]
thanks for testing

I also tested the default normal situation. So I will push a new release now
