### ISSUE TITLE
nodemanager_port not getting picked up

### ISSUE THREAD

**Issue by userMar2017** [biemond/biemond-orawls#438]
Hi Ed,

While trying to create a OHS domain, we are noticing that the nodemanager_port value is not getting reflected on the system. Is this a known issue ? 

If we set it to anything other than 5556, it still sets it up with value of 5556.

**Comment by biemond** [comment]
this is correct, I see I totally ignore it on domain.pp, also on normal domains
https://github.com/biemond/biemond-orawls/blob/puppet4/templates/ohs/domain.py.epp

but it is not really important in case of the adminserver .  You connect to the nodemanager and start the admin from here so port doesn't matter only username/password is important.
but for managed servers it is important so the admin server knows where to connect to but that is done by wls_machine etc.

**Comment by userMar2017** [comment]
Its also important if we say, we install two separate installs on the same server - one for weblogic and other for ohs. In that case it will cause a conflict. Is there any easy way of fixing this or should we write another manifest to modify the port number via simple unix commands ?

**Comment by biemond** [comment]
Nodemanager configuration happens after domain so here you need to specify it. Domain doesn't matter

**Comment by rrod157** [comment]
here's a snippet of the config.xml after domain creation, clearly the 

  <machine xsi:type="unix-machineType">
    <name>localmachine</name>
    <node-manager>
      <name>localmachine</name>
      <listen-address>localhost</listen-address>
      <listen-port>5556</listen-port>
    </node-manager>
  </machine>

Clearly the port passed on to orawls::domain is not picked-up:

nodemanager_port                      => 5557,

also, can the nodemanager_address variable can also be set under orawls::domain?

**Comment by biemond** [comment]
I know but It does not do anything on domain , nodemanager is the one and you can change it later with wls machine

**Comment by rrod157** [comment]
Agree with you that wls_machine would fix the nodemanager port and address. Thank you! :)
