### ISSUE TITLE
idempotent issue of wls_setting

### ISSUE THREAD

**Issue by rrod157** [biemond/biemond-orawls#442]
Hello, i have a problem with the idem-potency of the puppet code i have created. During the first run, it works file because i have the following wls_setting:

`wls_setting { 'default':
  user                         => 'oracle',
  weblogic_home_dir            => '/appl/Oracle/Middleware/Oracle_Home/wlserver',
  connect_url                  => "t3://${::fqdn}:7001",
  weblogic_user                => 'weblogic',
  weblogic_password            => 'weblogic',
  custom_trust                 => 'true',
  trust_keystore_file          => "/appl/domains/default_domain/jks/trust.jks",
  trust_keystore_passphrase    => 'password',
  use_default_value_when_empty => true,
}`

However, i am doing a customization of my domain just before the entire puppet code completed the run. I am enabling the admin port via custom script i have created and ran it against my domain using exec command:

`cd('/')
cmo.setAdministrationPort(7003)
cmo.setAdministrationPortEnabled(true)
`
After all is settled and servers were restarted, the puppet agent will trigger it again (default schedule). This time, it would fail because the admin console is now listening to https-7003 combination.

Is there a way we can resolve this issue? i am thinking that when it ran the code for the second time,  it uses the default setting:
`connect_url => "t3://${::fqdn}:7001",
`

**Comment by biemond** [comment]
Hi 

on the domain.pp you can already define all the admin ports before adminserver is started & wls_setting is defined. This way you always fine.

I don't understand why you don't set it right away and you have a custom script. that is not really the puppet way.  If you still want to do this make at least connect url is a fact on the machine and puppet can pick this up and use it on wls_setting.

thanks
