### ISSUE TITLE
Add params to wls_datasource

### ISSUE THREAD

**Issue by kobybr** [biemond/biemond-orawls#444]
Need to be able to set  statementcachetype & datasourcetype on wls_datasource.

**Comment by kobybr** [comment]
Thanks!

**Comment by biemond** [comment]
Oh I fixed the index range order.

Also I see datasourceType is a 12c feature , I will do a try catch and return the default.

**Comment by kobybr** [comment]
Sorry about the index order.   Thanks for the quick fix.
