### ISSUE TITLE
Error: Could not set 'present' on ensure: command in deamon failed

### ISSUE THREAD

**Issue by CharanBR** [biemond/biemond-orawls#452]
Hi @biemond ,

I'm seeing below error during puppet apply. The first puppet run goes fine since that is when the domain is first created.  
`Debug: wls:/J2EE_domain/serverConfig/> execfile('/tmp/wlstScript20170608-11552-o43ets.py')

Debug:

Debug: Starting an edit session ...

Debug: Started edit session, be sure to save and activate your changes once you are done.

Debug: Unexpected error: weblogic.descriptor.BeanAlreadyExistsException

Debug: Discarded all your changes successfully.

Debug: Edit session has been stopped successfully.

Debug: ~~~~COMMAND FAILED~~~~

Error: Could not set 'present' on ensure: command in deamon failed.
Error: Could not set 'present' on ensure: command in deamon failed.
Wrapped exception:
command in deamon failed.
Error: /Stage[main]/Mdw::Profile::Wls::Wlsconfig/Wls_server[managed]/ensure: change from absent to present failed: Could not set 'present' on ensure: command in deamon failed.
`
where managed is the jvm name. why is it that its giving an error  for a 2nd run ?

**Comment by biemond** [comment]
Hi,

I guess the index wlst script before the create goes wrong and it thinks it needs to create it. So the question is why did it failed.

you can check
puppet resource wls_server --debug

and see where it goes wrong.

**Comment by CharanBR** [comment]
sorry. I might have overlooked due to too many puppet runs.

> **Correction: the error occurs irrespective of first or nth run.**


For each of the server listed in yaml (under server_instances), I see below error

For adminserver,
`
Debug: Started edit session, be sure to save and activate your changes once you are done.

Debug: Unexpected error: Cannot create a new AdminServer, its not allowed

Debug: Discarded all your changes successfully.

Debug: Edit session has been stopped successfully.

Debug: ~~~~COMMAND FAILED~~~~

Error: Could not set 'present' on ensure: command in deamon failed.
Error: Could not set 'present' on ensure: command in deamon failed.
Wrapped exception:
command in deamon failed.
Error: /Stage[main]/Mdw_weblogicconf::Profile::Wls::Wlsconfig/Wls_server[AdminServer]/ensure: change from absent to present failed: Could not set 'present' on ensure: command in deamon failed.
`

For managed server
`Debug: Unexpected error: main.WLSTException

Debug: Discarded all your changes successfully.

Debug: Edit session has been stopped successfully.

Debug: ~~~~COMMAND FAILED~~~~

Error: Could not set 'present' on ensure: command in deamon failed.
Error: Could not set 'present' on ensure: command in deamon failed.
Wrapped exception:
command in deamon failed.
Error: /Stage[main]/Mdw_weblogicconf::Profile::Wls::Wlsconfig/Wls_server[managed]/ensure: change from absent to present failed: Could not set 'present' on ensure: command in deamon failed.`

**Comment by biemond** [comment]
this is the create and the result of a failing index, can you check the index phase why it is doing this

puppet resource wls_server --debug

this is correct Cannot create a new AdminServer, its not allowed
it should not be in this code ever for the AdminServer.

also maybe it because there are some pending changes and you didn't auto restart the adminserver

**Comment by CharanBR** [comment]
puppet resource wls_server --debug is successful and it gave me this result.
`wls_server { 'base_domain/AdminServer':
  ensure                           => 'present',
  arguments                        => ['-XX:PermSize=256m', '-XX:MaxPermSize=512m', '-Xms1024m', '-Xmx1024m', '-Dweblogic.Stdout=/logs/base_domain/AdminServer/AdminServer.out', '-Dweblogic.Stderr=/logs/base_domain/AdminServer/AdminServer_err.out'],
  auto_restart                     => '1',
  autokillwfail                    => '0',
  client_certificate_enforced      => '0',
  custom_identity                  => '0',
  frontendhttpport                 => '0',
  frontendhttpsport                => '0',
  jsseenabled                      => '0',
  listenaddress                    => 'centos',
  listenport                       => '7001',
  listenportenabled                => '1',
  log_datasource_filename          => 'logs/datasource.log',
  log_date_pattern                 => 'MMM d, yyyy, h:mm:ss,S a z',
  log_file_min_size                => '5000',
  log_filecount                    => '10',
  log_http_file_count              => '100',
  log_http_filename                => 'logs/access.log',
  log_http_format                  => 'date time cs-method cs-uri sc-status',
  log_http_format_type             => 'common',
  log_http_number_of_files_limited => '1',
  log_log_file_severity            => 'Trace',
  log_number_of_files_limited      => '1',
  log_redirect_stderr_to_server    => '0',
  log_redirect_stdout_to_server    => '0',
  log_rotate_logon_startup         => '0',
  log_rotationtype                 => 'byTime',
  log_stdout_severity              => 'Notice',
  logfilename                      => '/logs/base_domain/AdminServer/AdminServer.log',
  logintimeout                     => '5000',
  machine                          => 'LocalMachine',
  max_message_size                 => '10000000',
  restart_max                      => '2',
  server_parameters                => 'None',
  sslenabled                       => '0',
  sslhostnameverificationignored   => '1',
  ssllistenport                    => '7002',
  tunnelingenabled                 => '0',
  two_way_ssl                      => '0',
  useservercerts                   => '0',
  weblogic_plugin_enabled          => '0',
}
Debug: Quiting daemon wls-J2EE_domain...
`

**Comment by biemond** [comment]
So are you using this as reference base_domain/AdminServer

because you use base_domain as wls_setting and not default so you need to use  this base_domain/AdminServer  as title if you want to change something

**Comment by CharanBR** [comment]
I see. it looks like there is something I'm missing in my hiera or it is not correct. Now it complains about not able to create a domain. I will research on this.

Thank you!
