### ISSUE TITLE
issue when switching user

### ISSUE THREAD

**Issue by CharanBR** [biemond/biemond-orawls#453]
Hi,

I'm not sure if you want to fix this or not but here is an issue we face. We have created service accounts and they are locked down to so that they cannot be used to login. (shell set to : /sbin/nologin). So, for us the following command doesnt work when ran as root.

```
# su - weblogic
Last login: Mon Jun 12 13:58:25 EDT 2017
This account is currently not available.
```

But when -s is set, we can login. I'm wondering if you can fix this issue ?

```
# su -s /bin/bash - weblogic
Last login: Mon Jun 12 14:02:53 EDT 2017 on pts/0
```

**Comment by biemond** [comment]
Hi,

interesting, where did you get these errors

I see I am already doing this here

https://github.com/biemond/biemond-orawls/blob/puppet4/lib/puppet/provider/wls_adminserver/wls_adminserver.rb#L65

thanks

**Comment by CharanBR** [comment]
I believe its still su - <user> in nodemanager.pp. I'm attaching the stdout log.
[](https://pastebin.com/HTbRWDm0)

**Comment by biemond** [comment]
I see this

https://github.com/biemond/biemond-orawls/blob/puppet4/manifests/nodemanager.pp#L126

can you change this and see if it only goes wrong here

**Comment by CharanBR** [comment]
yup, that fixed the issue when I used su -s /bin/bash -l weblogic

**Comment by biemond** [comment]
perfect , the rest also goes fine like custom types

**Comment by biemond** [comment]
pushed a new version with this fix

**Comment by CharanBR** [comment]
thank you.
