### ISSUE TITLE
alias already declared error

### ISSUE THREAD

**Issue by CharanBR** [biemond/biemond-orawls#457]
@biemond ,

I'm seeing this error on the managed server node.

`Error: Cannot alias Yaml_setting[domain wlsDomain] to ["/etc/wls_domains.yaml:domains/base_domain"] at /etc/puppetlabs/code/environments/test/modules/orawls/manifests/copydomain.pp:233; resource ["Yaml_setting", "/etc/wls_domains.yaml:domains/base_domain"] already declared at /etc/puppetlabs/code/environments/test/modules/orawls/manifests/domain.pp:765
`

**Comment by biemond** [comment]
on the nodes you should only call copydomain and nodemanager. that's it

**Comment by CharanBR** [comment]
ah. got it (my issue was due to some inadvertent include statements in the managed nodes) . thank you.
