### ISSUE TITLE
map ldap group to weblogic role

### ISSUE THREAD

**Issue by CharanBR** [biemond/biemond-orawls#458]
Is it possible to map an ldap role using orawls module ?

My requirement is to add ldap group by going to Security Realms --> myrealm --> Roles and Policies tab --> Gobal Roles --> Roles --> View Role Conditions for Monitor --> Add Conditions --> select group from predicate list --> Enter group argument name.

I couldnt find it even through wlst. I worry if its even possible without manually entering from console.

Thank you for all your work. really appreciate it.

Charan

**Comment by biemond** [comment]
Hi,

I guess this can be done from some mbean or you need to call some mbean operation, probably it is not an attribute.
If you record this change in the console do you some output.

**Comment by CharanBR** [comment]
yup just found out. The weird part is console didnt record these mbeans.

```
wls:/J2EE_domain/serverConfig/> dr = cmo.getSecurityConfiguration().getDefaultRealm();
wls:/J2EE_domain/serverConfig/> print sr
[MBeanServerInvocationHandler]Security:Name=myrealm
wls:/J2EE_domain/serverConfig/> rm = sr.lookupRoleMapper('XACMLRoleMapper');
wls:/J2EE_domain/serverConfig/> print rm
[MBeanServerInvocationHandler]Security:Name=myrealmXACMLRoleMapper
wls:/J2EE_domain/serverConfig/> output = rm.getRoleExpression(None,'Admin');
wls:/J2EE_domain/serverConfig/> print output
?weblogic.entitlement.rules.AdministrativeGroup(Administrators)
wls:/J2EE_domain/serverConfig/> output = rm.getRoleExpression(None,'Monitor');
wls:/J2EE_domain/serverConfig/> print output
?weblogic.entitlement.rules.AdministrativeGroup(Monitors)
wls:/J2EE_domain/serverConfig/> rm.setRoleExpression(None,'Monitor','Grp(WLMonitors)');
wls:/J2EE_domain/serverConfig/>  output = rm.getRoleExpression(None,'Monitor');
wls:/J2EE_domain/serverConfig/> print output
Grp(WLMonitors)
```
and when I setRoleExpression, it removes the previously existing default group. Anyways, I will save it to a var and add it.

my question is, I'm not sure if I can use wls_role for this but can I use wls_exec resource correct ?

Thanks again,
Charan

**Comment by biemond** [comment]
yeah console/wlst cannot handle this

you need to try this out if it works with wls_role and else you can indeed use wls_exec ( which is secret type )  :-)

**Comment by CharanBR** [comment]
awesome !! wls_role worked flawlessly

Just had to create new data and create_resources function in my pp file and it is idempotent.
```
rolemapping_instances:
  'Monitor':
          expression:  'Grp(WLMonitors)|?weblogic.entitlement.rules.AdministrativeGroup(Monitors)'
```
Only problem I see is for validating LDAPauthenticator settings, the puppet run itself is taking around 10 mins. It doesnt take this much time when creating it though.

It creates this file for each key value of LDAPAuthenticator and probably trying to validate them. So connect to adminserver, validate (this continues through all the values)

```
real_domain='default'

try:
    puppet = open(tmp_script, "w")
    print >>puppet, 'value'

    key   = 'SecurityConfiguration/J2EE_domain/Realms/myrealm/AuthenticationProviders/LDAPAuthenticator/UserNameAttribute'
    value = get(key)


    print >>puppet, value
    puppet.close()
    print "~~~~COMMAND SUCCESFULL~~~~"

except:
    print "Unexpected error:", sys.exc_info()[0]
    print "~~~~COMMAND FAILED~~~~"
    raise
```

Thank you,
Charan

**Comment by biemond** [comment]
yeah , that's why I skip it when it is a ldap in group and users
https://github.com/biemond/biemond-orawls/blob/puppet4/files/providers/wls_group/index.py.erb#L9

maybe we should ignored it when it is external ldap

**Comment by CharanBR** [comment]
OK. I have moved AuthenticationProvider creation to wlst script and using your secret type :) . Didnt want my puppet to add another 10 mins of run for just 1 time setup. One odd behavior I observed is somehow refreshonly and notify are working for me in wls_exec. I removed both of them but doing a subscribe to domain change to restart the admin server.

Thank you and have a good weekend.
