### ISSUE TITLE
Problems with running Puppet every 30minutes

### ISSUE THREAD

**Issue by userMar2017** [biemond/biemond-orawls#459]
Hi Ed,

Based on a couple of tests that we have performed, we noticed that if we modify certain settings (example the heap size of the managed server), the next Puppet run wipes out these changes. Certain other changes are not wiped out by Puppet. Say deployments or datasource creation.

How do we know which settings will be affected by orawls module ? And what can we do about it ?

A related question is, do other companies run Puppet every 30minutes or do they simply use it to run once (perform the install/configuration) and then stop.

**Comment by biemond** [comment]
The thing is , you do it all with puppet or not. Not something in between else you cannot do promotion to other envs and have configuration drift which is hard to support. So put all config in git and do pull request for changes.

If you don't add those datasources to the config it will skip it to check for the current state. So the things which are not default should be added to puppet plus the ones you changed . The rest is default and won't matter much
