### ISSUE TITLE
cannot use passwords with $ sign

### ISSUE THREAD

**Issue by CharanBR** [biemond/biemond-orawls#462]
The module is breaking if I use password where there is $ sign in them. I haven't checked if this works on database passwords but the first step itself fails connecting to nodemanager.

**Comment by biemond** [comment]
ok, any clue how to solve this. 
how do you do this on the cmd line and an inside wlst script.

thanks

**Comment by CharanBR** [comment]
using single quotes would solve this on command line. I'm thinking the problem with template files could be with not using parameter expansion although I haven't tested this yet.

**Comment by biemond** [comment]
thanks

indeed $ inside "" is treated as a variable, let me know what you find.

thanks again

**Comment by CharanBR** [comment]
I think I know the issue but still trying to figure out how I could solve it. It is to do with nodemanager.pp file.

```
/u01/app/oracle/product/fmw/wlserver/common/bin/wlst.sh -skipWLSModuleScanning <<'EOF'
nmConnect("weblogic", "weblo$_gic1","centos.vm",5556,"base_domain","/u01/app/oracle/product/domains/base_domain","plain")
nmDisconnect()
EOF
```

if I use heredoc with single quotes this command works just fine but when this gets appended to the "su - #{user}" command that's when I couldnt disable string interpolation and python gives me NameError for weblo as $_gic1 is treated as an empty variable when executing in su - #{user} -c "".

**Comment by CharanBR** [comment]
just submitted pull request. That should fix it. I tested on nmConnect and storeUserConfig. I hope its the same fix for other .pp files

**Comment by biemond** [comment]
awesome

**Comment by seidls** [comment]
It looks like this same issue is occurring with the RCU System password has a $ in it.  Can you check for a similar issue within there?

**Comment by biemond** [comment]
rcu picks up a text file generated by puppet see
https://github.com/biemond/biemond-orawls/blob/puppet4/manifests/utils/rcu.pp#L91

and 
https://github.com/biemond/biemond-orawls/blob/puppet4/templates/utils/rcu_passwords.txt.erb

is the $ removed or replaced by something else. it is not bash.
