### ISSUE TITLE
JDBC parameter setting

### ISSUE THREAD

**Issue by manuelmolinaparadigma** [biemond/biemond-orawls#476]
As we are able to set parameters like connectioncreationretryfrequency or shrinkfrequencyseconds, we'd like to set LoginDelaySeconds and StatementTimeout as well.
Please, can you add it to wls_datasource ?

**Comment by biemond** [comment]
ok, it is on the todo list.

**Comment by biemond** [comment]
done, pushed a new version

**Comment by manuelmolinaparadigma** [comment]
Thanks!
