### ISSUE TITLE
Nodemanager.properties gets updated for every puppet run

### ISSUE THREAD

**Issue by CharanBR** [biemond/biemond-orawls#493]
hi @biemond,

Why is that for every puppet agent -t run the nodemanager.properties is getting updated. This shows up as a change in our puppet reports.

Notice: /Stage[main]/Mdw_weblogic::Nodemanager/Orawls::Nodemanager[nodemanager]/File[nodemanager.properties ux 1221 nodemanager]/content:
--- /u01/app/oracle/product/domains/base_domain/nodemanager/nodemanager.properties      2017-09-25 10:14:40.098138234 -0400
+++ /tmp/puppet-file20170925-62149-3wqh0s       2017-09-25 10:29:26.030602773 -0400
@@ -1,8 +1,7 @@
-#Mon Sep 25 10:14:40 EDT 2017
 #Node manager properties
 DomainsFile=/u01/app/oracle/product/domains/base_domain/nodemanager/nodemanager.domains
 LogLimit=0
-PropertiesVersion=12.2.1.1.0
+PropertiesVersion=12.2.1
 AuthenticationEnabled=true
 NodeManagerHome=/u01/app/oracle/product/domains/base_domain/nodemanager
 JavaHome=/u01/app/java/jdk8

Is there a way to avoid this ?

Thanks,
Charan

**Comment by biemond** [comment]
Hi,

provide the right value to the nodemanager manifest because wls will correct it when you start it and updates the nodemanager properties and puppet tries to correct it.

**Comment by CharanBR** [comment]
Yup, that resolved my issue. Thank you :)
