### ISSUE TITLE
Starting admin server without node manager

### ISSUE THREAD

**Issue by d3ag0s** [biemond/biemond-orawls#499]
Hello,

What I am trying to accomplish is to get the AdminServer started (via control_instances), as described at:

https://docs.oracle.com/cd/E15586_01/web.1111/e13715/manage_servers.htm#i1011528

The domain get's created correctly:

Notice: /Stage[main]/my_module::Wls_adminserver/Orawls::Domain[name]/File[domain.py name]/ensure: created, but when I'm trying to start the admin server, is trying to connect to the node manager every time:

Info: adminserver action: start with command /opt/weblogic/Oracle/Middleware/wlserver_12.2.1/wlserver/common/bin/wlst.sh -skipWLSModuleScanning <<-EOF
nmConnect("weblogic","xxxxx","192.168.100.10",5556,"name","/opt/weblogic/Oracle/Middleware/wlserver_12.2.1/user_projects/domains/name","plain")
nmStart("NameAdminServer")
nmDisconnect()
EOF and CONFIG_JVM_ARGS=-Dweblogic.ssl.JSSEEnabled=false -Dweblogic.security.SSL.enableJSSE=false
Traceback (innermost last):
  File "<console>", line 1, in ?
  File "<iostream>", line 111, in nmConnect
  File "<iostream>", line 553, in raiseWLSTException
WLSTException: Error occurred while performing nmConnect : Cannot connect to Node Manager. : Connection refused (Connection refused). Could not connect to NodeManager. Check that it is running at /192.168.100.10:5556.
Use dumpStack() to view the full stacktrace :

, and this is even if there's no node manager definition on my hiera, for the admin server.

**Comment by biemond** [comment]
Hi,

Did you configure the nodemanager and start it up.  You can take a look at 1 of the vagrant boxes.
Also NameAdminServer as name is a bit strange.

Thanks Edwin

**Comment by d3ag0s** [comment]
Hey Edwin, 

Oracle doesn't recommend to run Node Manager on a machine that runs an Administration Server, unless that machine also runs Managed Servers. So what I'm trying to accomplish is to have the admin server started, without a node manager running on the same machine. 

* NameAdminServer - obfuscated the actual name.

**Comment by biemond** [comment]
Hi,

Who is saying this?  The nodemanager is a perfect tool and it guards it & keeps the wls servers running.  There is no need to not use the nodemanager. At least there are not facts what supports this for the adminserver.

**Comment by d3ag0s** [comment]
Hi Edwin,

Even since version 7.0, Oracle doesn't recommend this: https://docs.oracle.com/cd/E13222_01/wls/docs70/admin_domain/nodemgr.html

"In a production environment, there is no need run Node Manager on a machine that runs an Administration Server, unless that machine also runs Managed Servers."

**Comment by biemond** [comment]
ok, that explains 

we always put admin server on 1 of the nodes, adminserver does not do much and better for licensing.
Plus it doesn't hurt and have no drawbacks except extra used OS memory . I don't think they say this for 12.2 because they are adding more stuff to it.

anyway for me no need to change this. you can start it with an exec, check the process and continue. Be aware it won't pick up your server arguments like the nodemanager does.
