### ISSUE TITLE
Could not retrieve local facts: wrong number of arguments (3 for 2)

### ISSUE THREAD

**Issue by ghost** [biemond/biemond-orawls#50]
I don't have the code yet but a customer (I'm a Puppet Labs employee) has reported the following:
After installing the weblogic server binaries all subsequent runs fail with an error below:

Debug: orawls.rb weblogic user is oracle
Debug: orawls.rb oraInstPath /app/oracle/oraInventory
Debug: orawls.rb oraProducts NotFound
Debug: orawls.rb mdw11gHomes ["/app/oracle/fmw"]
Debug: orawls.rb mdw12cHomes []
Debug: /etc/wls_domains.yaml not found
Debug: orawls.rb ora_mdw_homes /app/oracle/fmw;
Debug: orawls.rb ora_mdw_cnt 1
Error: Could not retrieve local facts: wrong number of arguments (3 for 2)
Error: Failed to apply catalog: Could not retrieve local facts: wrong number of arguments (3 for 2)

I checked orawls.rb but it isn't clear which fact is causing a problem or why.  Any thoughts?

**Comment by aevers1967** [comment]
i get the following error when running only the installations of weblogic server 12.1.3 for the second time (weblogic server is already installed then):

 Debug: orawls.rb weblogic user is oracle
Debug: orawls.rb oraInstPath /opt/ahold/Oracle/oraInventory
Debug: orawls.rb oraProducts /opt/ahold/Oracle/Middleware;
Debug: orawls.rb mdw11gHomes
Debug: orawls.rb mdw12cHomes /opt/ahold/Oracle/Middleware
Debug: /etc/wls_domains.yaml not found
Debug: orawls.rb ora_mdw_homes /opt/ahold/Oracle/Middleware;
Debug: orawls.rb ora_mdw_cnt 1
Error: Could not retrieve local facts: wrong number of arguments (3 for 2)
Error: Failed to apply catalog: Could not retrieve local facts: wrong number of arguments (3 for 2)

**Comment by biemond** [comment]
Can you check if you have the latest version of orawls, remove the older ones or the wls one ( they cannot co-exists of each other ) and with a puppet master restart everything.

and can you add the trace option to the puppet command so we know the code line number

thanks.

**Comment by aevers1967** [comment]
thanks for the quick reply.  I removed an older version of wls in the puppet modules and now the problem is solved!
