### ISSUE TITLE
wls_server_instances arguments

### ISSUE THREAD

**Issue by d3ag0s** [biemond/biemond-orawls#502]
Good day,

I'm having problem passing Min/Max heap as arguments for the managed servers. Even though I specify different values for both:
wls_server_instances:
  'hostname':
    ensure:             'present'
    arguments:          '-Xms2G -Xmx2G -XX..'

,  the actual processes are running with default values for min/max heap - 256/512. Is there a way to enforce the actual values to be used?

**Comment by biemond** [comment]
Hi,

I don't look at ps -ef , what you see there are the default one in the beginning and should be overriden by later entries.

So when you start them up by the nodemanager it should pickup the new arguments.
