### ISSUE TITLE
Managed Server on a separate server

### ISSUE THREAD

**Issue by userMar2017** [biemond/biemond-orawls#506]
Hi Ed,

If I have the Admin server on say sever1 and I want to build a managed server on say server2, can I achieve this via Puppet ?

I understand there will be some orchestration required but keeping that apart, does the orawls module provide a way for the managed server to connect to the admin server and prepare the domain ?

The other way is pack/unpack, but that makes it manual.

**Comment by biemond** [comment]
Hi,

basically orawls is also doing this for you with pack & unpack. Take a look at the vagrant examples.
in short create 2 machines , adminserver on 1st and server on the 2nd machine. pack domain.
start provision on 2nd node , install software , unpack and just start it up.

**Comment by userMar2017** [comment]
Thanks the quick response. I want to avoid the pack/unpack, I was hoping there was an alternative.
There is one for 12.2.1 but dont know if this works in 12.1.x
https://docs.oracle.com/middleware/1221/wls/WLSTG/domains.htm#WLSTG406

**Comment by biemond** [comment]
ok if pack works and does not require and manually interaction, what is your main concern?
of course this is cool hehehe

**Comment by userMar2017** [comment]
The challenge with pack is, how do I transfer that file to the managed server ? Note that all of this has to be achieved via automation/orchestration. I dont have a common NFS share or any ability to communicate with the managed server (not even ssh) !

**Comment by biemond** [comment]
ah ok.

I support on copydomain nfs or scp but if that is not allowed I don't know how it can work.
