### ISSUE TITLE
Oracle Fusion : soa b2b install

### ISSUE THREAD

**Issue by userMar2017** [biemond/biemond-orawls#508]
Hi Ed,

When I install these packages manually I install :
1. JDK
2. FMW Infrastructure
3. SOA
4. B2B

When I perform this install via orawls, I am able to install jdk just fine.
However, I am unclear on how to install "FMW Infrastructure". The steps outline how to install "soa" but shouldn't the "FMW Infrastructure" precede it ?

**Comment by biemond** [comment]
Hi,

fmw infra is just like wls only provide the right zip and set the infra option.
and soa + others can be installed  fmw manifest.

but just check 1 of the soa example vagrant boxes. they have a lot of code snippets

**Comment by userMar2017** [comment]
Hi Ed,

They all point to SOA ; does the following include the Infra piece as well ?

fmw_installations:
  'soa1221':
    fmw_product:               "soa"
    fmw_file1:                 "fmw_12.2.1.2.0_soa_Disk1_1of1.zip"
    oracle_base_home_dir:      *wls_oracle_base_home_dir
bpm: true

**Comment by biemond** [comment]
infra is on the wls side.  only difference you need to download a different weblogic installer and set this param

@param fmw_infra should install the WebLogic 12c infrastructure edition, you cannot use the normal wls install jar


hope this helps

**Comment by userMar2017** [comment]
ok, I think this is the one you were referring to. Thanks Ed !

12.1.3 infra

orawls::weblogic::version:                   *wls_version
orawls::weblogic::filename:                  'fmw_12.2.1.2.0_infrastructure.jar'
orawls::weblogic::fmw_infra:                 true
orawls::weblogic::log_output:                true
orawls::weblogic::jdk_home_dir:              *wls_jdk_home_dir
orawls::weblogic::oracle_base_home_dir:      *wls_oracle_base_home_dir
orawls::weblogic::puppet_download_mnt_point: *wls_source
orawls::weblogic::remote_file:               false
orawls::weblogic::weblogic_home_dir:         *wls_weblogic_home_dir
orawls::weblogic::middleware_home_dir:       *wls_middleware_home_dir
