### ISSUE TITLE
Install SOA 12.2.1.3

### ISSUE THREAD

**Issue by userMar2017** [biemond/biemond-orawls#509]
Hi Ed,

When I attempt to install 12.2.1.3 it seems to think I am trying to install 12.2.1.2.
Is this because of something that I am doing wrong or does orawls only support until 12.2.1.2 ?

Error

Notice: /Stage[main]/Main/Orawls::Fmw[soa]/Exec[extract V886440-01.zip for soa]/returns: executed successfully
Notice: /Stage[main]/Main/Orawls::Fmw[soa]/Exec[install soa]/returns: Error: Unable to access jarfile <tmp_folder>/fmw_12.2.1.2.0_soa.jar

My manifest

orawls::fmw{'soa':
  version                   => 12213,
  fmw_product               => "soa",
  fmw_file1                 => "V886440-01.zip",
..
..

**Comment by biemond** [comment]
strange, it should work

```
  } elsif ( $fmw_product == 'soa' ) {

    if $version >= 1221 {
      $total_files = 1
      $fmw_silent_response_file = 'orawls/fmw_silent_soa_1221.rsp.epp'
      if $version == 1221 {
        $binFile1                 = 'fmw_12.2.1.0.0_soa.jar'
      } elsif $version == 12211 {
        $binFile1                 = 'fmw_12.2.1.1.0_soa.jar'
      } elsif $version == 12212 {
        $binFile1                 = 'fmw_12.2.1.2.0_soa.jar'
      } else {
        $binFile1                 = 'fmw_12.2.1.3.0_soa.jar'
      }
```

**Comment by userMar2017** [comment]
Hi Ed,

Is it because of the version of orawls ? The metadata.json has version 2.0.0

Which version do you have and which file are you looking at manifests/fmw.pp ?

**Comment by biemond** [comment]
https://github.com/biemond/biemond-orawls/releases
you are 10 months behind. 12.2.1.3 did not exists then

**Comment by userMar2017** [comment]
ouch... but thanks again for the quick response.

Its surely going to be a challenge now as we have quite a large environment. Definitely makes me extremely nervous pushing this out to all the servers :(

**Comment by biemond** [comment]
look at the changes , you are already on 2.0 , so well done. that was the hardest part. only small changes and bug fixes.

**Comment by userMar2017** [comment]
Thanks again Ed for your swift responses. Closing this request.
