### ISSUE TITLE
Question: Is it possible to use orawls to start Domain Partitions?

### ISSUE THREAD

**Issue by danielmenezesbr** [biemond/biemond-orawls#511]
Is it possible to use orawls to start Domain Partitions?

**Comment by biemond** [comment]
yep , you mean this

https://github.com/biemond/biemond-orawls-vagrant-12.2.1-puppet4/blob/master/puppet/hieradata/admin.example.com.yaml#L1137

**Comment by danielmenezesbr** [comment]
Thanks!
