### ISSUE TITLE
OHS : 12.2.1.3

### ISSUE THREAD

**Issue by userMar2017** [biemond/biemond-orawls#515]
Hi Ed,

I am using orawls module version 2.0.13
Installing OHS 12.2.1.3 goes through fine.
While creating a domain (in standalone mode), I receive the following error :

Notice: /Stage[main]/Ohs12213::Create_ohs_domain/Orawls::Domain[ohs_domain]/Exec[execwlst some_name oh_domain]/returns: 60708: Found no templates with Oracle HTTP Server (Standalone) name and 12.2.1.2 version

My code

orawls::domain {"ohs_domain":
  version                               => 12213,
  ..
  ..

**Comment by biemond** [comment]
Hi,

indeed it is a bug. 
see https://github.com/biemond/biemond-orawls/blob/puppet4/templates/ohs/domain.py.epp#L55

for now only 12.2.1.2 is supported. I need to check the version and load the right version

**Comment by userMar2017** [comment]
Thanks for the super quick response Ed. Do you think it will be ready in a few days or will it take longer (a few months) ?

**Comment by biemond** [comment]
days, it should be an easy fix

**Comment by userMar2017** [comment]
Thanks Ed. In that case, I will wait to hear back from you.
We have release going in a few weeks and hence the question.

**Comment by biemond** [comment]
can you check the latest https://github.com/biemond/biemond-orawls

it got your fix see  d1d527cbebc01ac3e3168f7a495ed17485d956a6

**Comment by userMar2017** [comment]
Hi Ed,

When I try to use 2.0.14, I receive the following error :

The module release biemond-orawls-2.0.14 does not exist on https://forgeapi.puppetlabs.com

Am I doing something wrong ?

**Comment by biemond** [comment]
download the zip from github and extract it. that should work

**Comment by userMar2017** [comment]
Ah, I cant do that manually as this is controlled by our enterprise system.

To do it manually, I will need to setup a local environment and it will take me quite some time.

**Comment by userMar2017** [comment]
<Forgot to mention, I dont have access to the enterprise system that stores the module. Its tightly controlled now>

**Comment by userMar2017** [comment]
Hi Ed,

There is some syntax error. Cannot tell whether it does not like "=" and expects "==" or something else.

Notice: /Stage[main]/Main/Orawls::Domain[oh_test]/Exec[execwlst oh_abcd_learning oh_test]/returns: Problem invoking WLST
 - Traceback (innermost last):
Notice: /Stage[main]/Main/Orawls::Domain[oh_test]/Exec[execwlst oh_abcd_learning oh_test]/returns:   (no code object) at
 line 0
Notice: /Stage[main]/Main/Orawls::Domain[oh_test]/Exec[execwlst oh_abcd_learning oh_test]/returns:   File "/tmp/puppet_binary/domain_oh_abcd_learning.py", line 18
Notice: /Stage[main]/Main/Orawls::Domain[oh_test]/Exec[execwlst oh_abcd_learning oh_test]/returns:          if OHS_VERSION = 12211:
Notice: /Stage[main]/Main/Orawls::Domain[oh_test]/Exec[execwlst oh_abcd_learning oh_test]/returns:
   ^
Notice: /Stage[main]/Main/Orawls::Domain[oh_test]/Exec[execwlst oh_abcd_learning oh_test]/returns: SyntaxError: invalid
syntax
Error: '/opt/Middleware/Oracle_Home/ohs/common/bin/wlst.sh domain_oh_abcd_learning.py' returned 1 instead
 of one of [0]
Error: /Stage[main]/Main/Orawls::Domain[oh_test]/Exec[execwlst oh_abcd_learning oh_test]/returns: change from 'notrun' t
o ['0'] failed: '/opt//Oracle/Middleware/Oracle_Home/ohs/common/bin/wlst.sh domain_oh_abcd_learning.py' returned
1 instead of one of [0]

**Comment by biemond** [comment]
hehe stupid mistake, will fix it now

**Comment by userMar2017** [comment]
:)

**Comment by userMar2017** [comment]
Hi Ed,

Not sure whether you are still working on it but the one that you updated has an error too.

I would think the final line needs to change from

        templateVersion == '12.2.1.3'

to

        templateVersion = '12.2.1.3'


Notice: /Stage[main]/Main/Orawls::Domain[oh_test]/Exec[execwlst oh_abcd_learning oh_test]/returns: NameError: templateVersion

**Comment by biemond** [comment]
done again. it is crazy how many mistakes you can make in a few lines

**Comment by userMar2017** [comment]
ha ha. Stuff happens. Its Friday !!

**Comment by userMar2017** [comment]
It worked now Ed, thanks !

I will test a few things now.

**Comment by userMar2017** [comment]
Hi Ed,

Performed some basic testing and it looks good. Can you promote this to forgeapi so that I can pull it down to the target servers ?

**Comment by biemond** [comment]
thanks , yeah will do this in the weekend

**Comment by userMar2017** [comment]
Thanks for all your help Ed. This can wait till Monday.

**Comment by userMar2017** [comment]
Hi Ed,

I pulled down the latest version and its looking good. But I still have a lot of testing to do. I will get to you once its complete.

**Comment by userMar2017** [comment]
Hi Ed,

We encountered an odd issue. While I have been focusing on OHS, others are reporting that existing weblogic builds are failing. These manifests have been working for over 6 months at least. Providing details below. Running a debug clearly shows that its able to connect to the admin server but then it just fails. 

wls_domain { "domain_name":
  ensure                                            => 'present',
  log_file_min_size                                 => '5000',
  log_filecount                                     => '20',
..
..


wls_server { "admin_server":
  ensure                                => 'present',
  sslenabled                            => '1',
..
..

<Puppet debug>

Debug: Getting boolean property ShowArchivedRealPathEnabled

Debug: Storing state
Debug: Stored state in 0.35 seconds
Error: Failed to apply catalog: timeout on reading expected output from daemon process.

**Comment by biemond** [comment]
Hi,

try to execute these wlst scripts manually and see where it fails or run it with --debug to see it.  
Timeout means it crashed.

**Comment by userMar2017** [comment]
The first entry in the wlst script is open file. Where can I find tmp_script ?

f = open_file("name;domain;jta_transaction_timeout;jta_max_transactions;jpa_default_provider;security_crossdomain;log_file_min_size;
log_filecount;log_rotate_logon_startup;log_filename;log_rotationtype;log_number_of_files_limited;jmx_platform_mbean_server_enabled;j
mx_platform_mbean_server_used;web_app_container_show_archived_real_path_enabled;setinternalappdeploymentondemandenable;setarchivecon
figurationcount;setconfigbackupenabled;setconfigurationaudittype;exalogicoptimizationsenabled;log_date_pattern;log_domain_log_broadc
ast_severity;cdi_implicit_bean_discovery_enabled", tmp_script)

**Comment by biemond** [comment]
you can define them on wls_setting and it will store them to  /tmp for example
or run puppet in debug mode

**Comment by userMar2017** [comment]
Is it the output of /etc/wls_settings.yaml ?

**Comment by userMar2017** [comment]
The output I sent above is from Puppet in debug mode

**Comment by biemond** [comment]
no, send me all the output, with all the wlst output

**Comment by userMar2017** [comment]
[Puppet orawls issue.docx](https://github.com/biemond/biemond-orawls/files/1795008/Puppet.orawls.issue.docx)

Details are attached.

**Comment by biemond** [comment]
perfect,

can you try this

```
cd('/')
domain_name = get_attribute_value('Name')


cd('/WebAppContainer/'+domain_name)
ls()
web_app_container_show_archived_real_path_enabled = get('ShowArchivedRealPathEnabled')
print(str(web_app_container_show_archived_real_path_enabled))


cd('/CdiContainer/'+domain_name)
ls()
cdi_implicit_bean_discovery_enabled = get('ImplicitBeanDiscoveryEnabled')
print(str(cdi_implicit_bean_discovery_enabled))


```

**Comment by userMar2017** [comment]
Failed at obtaining the domain name

wls:/offline> connect('CONNECTION DETAILS')
wls:/WL_SERVER_NAME/serverConfig> cd('/')
wls:/WL_SERVER_NAME/serverConfig> domain_name = get_attribute_value('Name')
Traceback (innermost last):
  File "<console>", line 1, in ?
NameError: get_attribute_value
wls:/WL_SERVER_NAME/serverConfig>

**Comment by biemond** [comment]
also check the wls console and see if a restart is required

**Comment by biemond** [comment]
do 

domain_name = get('Name')

**Comment by userMar2017** [comment]
First set of commands worked. Output of

print(str(web_app_container_show_archived_real_path_enabled))

is 0

Next command failed as that folder does not exist
cd('/CdiContainer/'+domain_name)

Traceback (innermost last):
  File "<console>", line 1, in ?
  File "<iostream>", line 164, in cd
  File "<iostream>", line 552, in raiseWLSTException
WLSTException: Error cding to the MBean

**Comment by userMar2017** [comment]
Let me restart the entire domain

**Comment by userMar2017** [comment]
The managed server is not coming up. Let me engage the requester and get back to you.

**Comment by biemond** [comment]
what is the wls version?

**Comment by userMar2017** [comment]
12.1.3

Its up now

**Comment by biemond** [comment]
ok maybe it is an 12.2 option and I need to include a try except block

**Comment by userMar2017** [comment]
Managed Server is up ; still receiving the following error 

WLSTException: Error cding to the MBean

**Comment by biemond** [comment]
ok good I will make a fix

**Comment by biemond** [comment]
fixed , can you try it out.

**Comment by userMar2017** [comment]
It does not seem to work.

Is it fixed and placed on forgeapi ? That's the only way I can test in this environment.

**Comment by biemond** [comment]
no, you need to test it before I do a push

**Comment by userMar2017** [comment]
hmm, can you provide that file (and the contents) that changed ? I will try to see if I can get someone in that team to assist.

**Comment by biemond** [comment]
see 2b0a8108912da145880eb2a7b52d9d316169dda4 not much changed

**Comment by userMar2017** [comment]
I got those two files changed on the master but the agent is still pulling the old code. Deleting the cache on the agent did not help either. Not sure how to test this out.

**Comment by biemond** [comment]
restart master and do a dummy run on the master that should detect the changes

**Comment by userMar2017** [comment]
I dont have the option of restarting the master as all environments (including prod) run on it. Instead I am trying to setup my local environment but have spent the entire day and have not been able to get to that point. I will try for maybe another day and might just have to give up after that.

**Comment by userMar2017** [comment]
Verified that it fails with 2.0.14 and works with 2.0.15


Debug: Getting boolean property ShowArchivedRealPathEnabled

Debug: Storing state
Debug: Stored state in 0.34 seconds
Error: Failed to apply catalog: timeout on reading expected output from daemon process.

**Comment by userMar2017** [comment]
Updated the module in Puppet and so far its looking good. Continuing my testing ....
