### ISSUE TITLE
Puppet run causing a 100% cpu spike

### ISSUE THREAD

**Issue by userMar2017** [biemond/biemond-orawls#519]
Hi Ed,

It has been noticed that a puppet run (which in turn triggers orawls module), causes a 100% cpu spike. Since Puppet runs every 30 minutes, this spike is noticed every 30 minutes.
After analysing a few puppet runs, I found the following processes that are causing the spike

CPU 180% -> java ... oracle/opatch/OPatch lsinventory ...
CPU 160% ->  java .. wlst ...
CPU 160% ->  java .. wlst ...

The first one is where it does a opatch lsinventory to list the packages
The second and third one is where it invokes wlst to compare the settings against the ones dictated by orawls

Checking to see if you have any suggestions on how to avoid these spikes.

**Comment by biemond** [comment]
Hi,

is this really 100% cpu? or some sleeping cpu cycles just  put it on 2 hour   interval

**Comment by userMar2017** [comment]
It is 100% cpu and it stays that way only for a couple of seconds. But it registers as a spike in the monitoring tool and now everyone knows !

**Comment by userMar2017** [comment]
I turned off puppet and it seems to have gone away. Waiting for developers to confirm.

**Comment by userMar2017** [comment]
Yes, its coming from Puppet. Has anyone else reported this issue ?

**Comment by biemond** [comment]
raise a bug on oracle, still it can be sleep cpu cycle and waiting for the result or processing

**Comment by userMar2017** [comment]
Bug for both wlst and opatch lsinventory ?

I can ask the question about "sleep cpu cycle" to our Unix admins, though I wont receive any response unless I am very specific about what I am asking.

**Comment by biemond** [comment]
yep, I guess there are cpu intensive
