### ISSUE TITLE
Rename Admin Host "LocalMachine" to HOSTNAME

### ISSUE THREAD

**Issue by wijetnga** [biemond/biemond-orawls#523]
Any idea how I can change Admin machine name to HOSTNAME easily?

I did try below and didn't work..
  wls_server {'AdminServer':
    ensure                                => 'present',
    listenaddress                      => $admin_server_address,
    listenport                            => '7001',
    machine                              => $::hostname,

thanks in advance.

**Comment by biemond** [comment]
Hi,

first you need to create a wls_machine and use that name as reference

**Comment by wijetnga** [comment]
Thanks !!
