### ISSUE TITLE
Java Vendor other than Sun

### ISSUE THREAD

**Issue by adamjk-dev** [biemond/biemond-orawls#526]
https://github.com/biemond/biemond-orawls/blob/e8f2e750000d50c2563cfc57b7b6075c01545368/manifests/weblogic_type.pp#L215

Do we have a way to update who the Java vendor is other than Sun? We can point to any installed JDK directory, so perhaps we installed with an Oracle JDK or something, right?

Maybe I am missing something here. Thanks!

**Comment by biemond** [comment]
sun is hotspot and is the oracle one. besides this you have the ibm one or openjdk. but with wls you have a right to use the hotspot jvm

**Comment by adamjk-dev** [comment]
Gotcha, and makes sense. I just didn't see a way that we could overwrite that value if we so desired. It looks hardcoded in the module and no parameter. Just checking is all, I don't think it is a big deal. Also, as you said, Sun and Oracle for the JDK should mean the same thing. 

As always, thanks for your time.
