### ISSUE TITLE
How to prevent wls_group from wiping out existing users ?

### ISSUE THREAD

**Issue by userMar2017** [biemond/biemond-orawls#551]
Hi Ed,

I am using orawls 2.0.17. When I create a new user (using orawls) and add it to a group ( say admin), it wipes out the users that currently exist in that group.

Based on the following thread, I attempted "manage_group" but it did not appear to take it.
https://github.com/biemond/biemond-orawls/issues/329

Is there anyway I can avoid orawls from wiping out the existing group membership ?

**Comment by biemond** [comment]
hi
no this is how puppet works , your config is the truth. so you also need to add the other users to your group.

**Comment by userMar2017** [comment]
:(

Thanks Ed !
