### ISSUE TITLE
fmwclusterjrf

### ISSUE THREAD

**Issue by Joris29** [biemond/biemond-orawls#554]
@biemond Can you help me with the following error:

Warning: Unknown variable: '::orawls::weblogic::middleware_home_dir'. (file: /opt/puppetlabs/puppet/modules/orawls/manifests/control.pp, line: 72, column: 61)
Error: Evaluation Error: Error while evaluating a Resource Statement, Orawls::Control[ShutdownAdminServerForJRFTrisMaster_Live]: parameter 'middleware_home_dir' expects a String value, got Undef (file: /opt/puppetlabs/puppet/modules/orawls/manifests/utils/fmwclusterjrf.pp, line: 70) on node

Setup:

orawls::utils::fmwclusterjrf { $source:
      version              => 12213,
      weblogic_home_dir    => '/sysprogs/oracle/wls/122130/wlserver',
      middleware_home_dir  => '/sysprogs/oracle/wls/122130',
      ...
    }

**Comment by Joris29** [comment]
@biemond any update for this? I found a temporary workaround: Edit orawls/manifests/control.pp
$middleware_home_dir -> Optional[String] $middleware_home_dir

**Comment by biemond** [comment]
the solution is to pass on this param from clusterjrf to control , not to make it optional also you can set the global $::orawls::weblogic::middleware_home_dir .

you can send a pull request

**Comment by Joris29** [comment]
@biemond The thing is that it is set on orawls::utils::fmwclusterjrf resource see above but in your fmwclusterjrf.pp it is not present in your call to control resource:

orawls::control{"ShutdownAdminServerForJRF${title}":
      weblogic_home_dir   => $weblogic_home_dir,
      jdk_home_dir        => $jdk_home_dir,
      domain_name         => $domain_name,
      wls_domains_dir     => $domains_dir,
      server_type         => 'admin',
      target              => 'Server',
      server              => $adminserver_name,
      adminserver_address => $adminserver_address,
      adminserver_port    => $adminserver_port,
      nodemanager_port    => $nodemanager_port,
      action              => 'stop',
      weblogic_user       => $weblogic_user,
      weblogic_password   => $weblogic_password,
      os_user             => $os_user,
      os_group            => $os_group,
      download_dir        => $download_dir,
      log_output          => $log_output,
    }

So should I either change control.pp or fmwclusterjrf.pp for the pull request?

**Comment by biemond** [comment]
just pass on the param from here https://github.com/biemond/biemond-orawls/blob/puppet4/manifests/utils/fmwclusterjrf.pp#L28 and add it to here orawls::control{"ShutdownAdminServerForJRF${title}":

thanks

**Comment by Joris29** [comment]
@biemond I did this because this is my setup:

orawls::utils::fmwclusterjrf { $source:
version => 12213,
weblogic_home_dir => '/sysprogs/oracle/wls/122130/wlserver',
middleware_home_dir => '/sysprogs/oracle/wls/122130',
...
}

this is your fmwclusterjrf.pp file:
...
if ($continue) {
    #shutdown adminserver for offline WLST scripts
    orawls::control{"ShutdownAdminServerForJRF${title}":
      weblogic_home_dir   => $weblogic_home_dir,
      jdk_home_dir        => $jdk_home_dir,
      domain_name         => $domain_name,
      wls_domains_dir     => $domains_dir,
      server_type         => 'admin',
      target              => 'Server',
      server              => $adminserver_name,
      adminserver_address => $adminserver_address,
      adminserver_port    => $adminserver_port,
      nodemanager_port    => $nodemanager_port,
      action              => 'stop',
      weblogic_user       => $weblogic_user,
      weblogic_password   => $weblogic_password,
      os_user             => $os_user,
      os_group            => $os_group,
      download_dir        => $download_dir,
      log_output          => $log_output,
    }
...


So it is missing in your code but i will add that param and send a pr
