### ISSUE TITLE
OHS 12.2.1.4

### ISSUE THREAD

**Issue by userMar2017** [biemond/biemond-orawls#580]
We have OHS 12.2.1.3 working in our environment for a while using Ed's orawls module. We are now trying to get OHS 12.2.1.4 setup.

When I call the orawls::fmw  function for 12214, for some reason it still tries to look for the 12.2.1.3 binary file (details below ).

Does anyone know how orawls constructs this file ( fmw_12.2.1.3.0_ohs_linux64.bin ) internally as I am not specifying it anywhere ? And how to force it to use the binary for 12.2.1.4  ( fmw_12.2.1.**4**.0_ohs_linux64.bin )  ?

Error: Could not find command '/tmp/webtier12214/fmw_12.2.1.3.0_ohs_linux64.bin'
Error: Exec[install webtier12214]/returns: change from 'notrun' to ['0'] failed: Could not find command '/tmp/webtier12214/fmw_12.2.1.3.0_ohs_linux64.bin'

**Comment by biemond** [comment]
yep you need to change this https://github.com/biemond/biemond-orawls/blob/puppet4/manifests/fmw.pp#L517

**Comment by userMar2017** [comment]
Hi Ed,

Long time ! Thank you so much for your quick response.

I added binFile1 to the orawls:fmw function but it did not like it. Do I need to modify "fmw.pp" on my side ?

Orawls::Fmw[webtier12214]: has no parameter named 'binFile1'

I am using the following version

mod 'biemond-orawls', '2.0.17'

**Comment by biemond** [comment]
yep , add another elsif for 12213 and current else should handle 12214

**Comment by userMar2017** [comment]
Thanks Ed. Let me try that.

**Comment by userMar2017** [comment]
I will try this out but a code push appears to overwrite these files.

**Comment by userMar2017** [comment]
That worked but the files get overwritten with a code push

**Comment by userMar2017** [comment]
Closing this request. Thanks for your help Ed !
