### ISSUE TITLE
Could not autoload puppet/type/wls_setting no such file to load  -- easy_type

### ISSUE THREAD

**Issue by robh007** [biemond/biemond-orawls#59]
Hi, we are encountering an issue when running a puppet agent run against an open source master using the orawls module. It doesn't appear to be version specific. I've ran multiple different versions including the latest. We get the following error appearing on the master and agent. 

Sep 24 17:30:46 localhost puppet-master[3041]: Could not autoload puppet/type/wls_setting: no such file to load -- easy_type
Sep 24 17:30:46 localhost puppet-master[3041]: Could not autoload puppet/type/wls_setting: no such file to load -- easy_type on node rhtest
Sep 24 17:30:46 localhost puppet-master[3041]: Could not autoload puppet/type/wls_setting: no such file to load -- easy_type on node rhtest
Sep 24 17:30:46 localhost puppet-master[3041]: Could not autoload puppet/type/wls_setting: no such file to load -- easy_type on node rhtest
Sep 24 17:32:59 localhost puppet-master[3072]: Could not autoload puppet/type/wls_setting: no such file to load -- easy_type

We have the easy_type module installed and available to the puppet master. This doesn't appear to effect local puppet apply scenarios. I was wondering if you've seen this before?

All the types & provider files used within the module appear to be pluginsynced across to the agent, I can see the relevant files in /var/lib/puppet/lib/puppet/type

Currently we are running Puppet version 3.6.2. I've built another master using a vagrant setup and run into the same problem. It also occurs when attempting the puppet agent run from other hosts.

We are currently running all our nodes on Centos version 6.5. 

Some more detailed output from the puppet agent -t --trace command

Sep 23 15:57:51 rh-test01 puppet-agent[5193]: Loading facts in /var/lib/puppet/lib/facter/user_home_path.rb
Sep 23 15:57:51 rh-test01 puppet-agent[5193]: Loading facts in /var/lib/puppet/lib/facter/facter_dot_d.rb
Sep 23 15:57:51 rh-test01 puppet-agent[5193]: Loading facts in /var/lib/puppet/lib/facter/pe_version.rb
Sep 23 15:57:51 rh-test01 puppet-agent[5193]: Loading facts in /var/lib/puppet/lib/facter/gemhome.rb
Sep 23 15:57:51 rh-test01 puppet-agent[5193]: Loading facts in /var/lib/puppet/lib/facter/root_home.rb
Sep 23 15:57:51 rh-test01 puppet-agent[5193]: Loading facts in /var/lib/puppet/lib/facter/systemroot.rb
Sep 23 15:57:51 rh-test01 puppet-agent[5193]: Loading facts in /var/lib/puppet/lib/facter/puppet_vardir.rb
Sep 23 15:57:51 rh-test01 puppet-agent[5193]: Loading facts in /var/lib/puppet/lib/facter/orawls.rb
Sep 23 15:57:53 rh-test01 puppet-agent[5193]: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not autoload puppet/type/wls_setting: no such file to load -- easy_type on node rh-test01
Sep 23 15:57:53 rh-test01 puppet-agent[5193]: /usr/lib/ruby/site_ruby/1.8/puppet/indirector/rest.rb:207:in `is_http_200?'
Sep 23 15:57:53 rh-test01 puppet-agent[5193]: /usr/lib/ruby/site_ruby/1.8/puppet/indirector/rest.rb:100:in `find'
Sep 23 15:57:53 rh-test01 puppet-agent[5193]: /usr/lib/ruby/site_ruby/1.8/puppet/indirector/indirection.rb:201:in `find'
Sep 23 15:57:53 rh-test01 puppet-agent[5193]: /usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:256:in `retrieve_new_catalog'
Sep 23 15:57:53 rh-test01 puppet-agent[5193]: /usr/lib/ruby/site_ruby/1.8/puppet/util.rb:327:in `thinmark'
Sep 23 15:57:53 rh-test01 puppet-agent[5193]: /usr/lib/ruby/1.8/benchmark.rb:308:in `realtime'
Sep 23 15:57:53 rh-test01 puppet-agent[5193]: /usr/lib/ruby/site_ruby/1.8/puppet/util.rb:326:in `thinmark'
Sep 23 15:57:53 rh-test01 puppet-agent[5193]: /usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:255:in `retrieve_new_catalog'
Sep 23 15:57:53 rh-test01 puppet-agent[5193]: /usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:60:in `retrieve_catalog'
Sep 23 15:57:53 rh-test01 puppet-agent[5193]: /usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:103:in `prepare_and_retrieve_catalog'
Sep 23 15:57:53 rh-test01 puppet-agent[5193]: /usr/lib/ruby/site_ruby/1.8/puppet/configurer.rb:170:in `run'
Sep 23 15:57:53 rh-test01 puppet-agent[5193]: /usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:47:in `run'
Sep 23 15:57:53 rh-test01 puppet-agent[5193]: /usr/lib/ruby/site_ruby/1.8/puppet/agent/locker.rb:20:in `lock'
Sep 23 15:57:53 rh-test01 puppet-agent[5193]: /usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:47:in `run'
Sep 23 15:57:53 rh-test01 puppet-agent[5193]: /usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:117:in `with_client'
Sep 23 15:57:53 rh-test01 puppet-agent[5193]: /usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:44:in `run'
Sep 23 15:57:53 rh-test01 puppet-agent[5193]: /usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:82:in `run_in_fork'
Sep 23 15:57:53 rh-test01 puppet-agent[5193]: /usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:43:in `run'
Sep 23 15:57:53 rh-test01 puppet-agent[5193]: /usr/lib/ruby/site_ruby/1.8/puppet/application.rb:179:in `call'
Sep 23 15:57:53 rh-test01 puppet-agent[5193]: /usr/lib/ruby/site_ruby/1.8/puppet/application.rb:179:in `controlled_run'
Sep 23 15:57:53 rh-test01 puppet-agent[5193]: /usr/lib/ruby/site_ruby/1.8/puppet/agent.rb:41:in `run'
Sep 23 15:57:53 rh-test01 puppet-agent[5193]: /usr/lib/ruby/site_ruby/1.8/puppet/application/agent.rb:355:in `onetime'
Sep 23 15:57:53 rh-test01 puppet-agent[5193]: /usr/lib/ruby/site_ruby/1.8/puppet/application/agent.rb:321:in `run_command'
Sep 23 15:57:53 rh-test01 puppet-agent[5193]: /usr/lib/ruby/site_ruby/1.8/puppet/application.rb:371:in `run'
Sep 23 15:57:53 rh-test01 puppet-agent[5193]: /usr/lib/ruby/site_ruby/1.8/puppet/application.rb:477:in `plugin_hook'
Sep 23 15:57:53 rh-test01 puppet-agent[5193]: /usr/lib/ruby/site_ruby/1.8/puppet/application.rb:371:in `run'
Sep 23 15:57:53 rh-test01 puppet-agent[5193]: /usr/lib/ruby/site_ruby/1.8/puppet/util.rb:479:in `exit_on_fail'
Sep 23 15:57:53 rh-test01 puppet-agent[5193]: /usr/lib/ruby/site_ruby/1.8/puppet/application.rb:371:in `run'
Sep 23 15:57:53 rh-test01 puppet-agent[5193]: /usr/lib/ruby/site_ruby/1.8/puppet/util/command_line.rb:137:in `run'

**Comment by yanivpaz** [comment]
Hi
we are also experiencing the
"Could not autoload puppet/type/wls_setting: no such file to load -- easy_type" error when we installed the puppetmaster on separate VM .we solved it as suggested in above and also in the  README.markdown  by running puppet agent on the master machine

**Comment by robh007** [comment]
Running a puppet agent -t on the master does resolve the issue.
