### ISSUE TITLE
server logs explanation

### ISSUE THREAD

**Issue by adamjk-dev** [biemond/biemond-orawls#98]
Hello sir,

So, there are many ways to set the log files in a server_instances block:

 arguments:
           - *server_vm_args_permsize
           - *server_vm_args_max_permsize
           - *server_vm_args_memory
           - *server_vm_args_max_memory
           - "-Dweblogic.Stdout=/logs/%{::domain}/weblogic/%{::appname}-s1.out"
           - "-Dweblogic.Stderr=/logs/%{::domain}/weblogic/%{::appname}-s1_err.out"

 logfilename: "/logs/%{::domain}/weblogic/%{::appname}-s1.log"

Through arguments and the logfilename are the ways I see. So, if we set all 3 above, we end up with 3 log files per server (s1.out, s1_err.out, and s1.log). So, obviously s1.out is for STDOUT, s1_err.out is for STDERR, and s1.log is for what, everything combined or what?

I know we just want a log filename for STDOUT (s1.log), and one for STDERR (s1.out), for instance. That would be the ideal output we want. Do you know what I would set to get this kind of log file naming and output?

So, the arguments are the arguments sent to the JVM for the servers, correct? The logFilename is used in your types and providers (used in the WLST scripts). So, should I just set the STDOUT and STDERR to the filenames I want in the JVM arguments and not set the logFilename parameter?

**Comment by adamjk-dev** [comment]
I ended up using the following (to get two output files):

arguments:
- "-Dweblogic.Stdout=/logs/%{::domain}/weblogic/%{::appname}-s1.log"
- "-Dweblogic.Stderr=/logs/%{::domain}/weblogic/%{::appname}-s1.out"

logfilename: "/logs/%{::domain}/weblogic/%{::appname}-s1.log"


For instance, the logfilename parameter and the stdout JVM define both point to the same log file.

**Comment by biemond** [comment]
The 2 server java arguments are used by the nodemanager when it startups up the managed server, re-direct outlog and how the nodemanager starts the server. 

The other are for the managed server, domain, http ,datasource log etc. with rotation and size
Don't think you used re-use the log files because of locking or performance.

**Comment by adamjk-dev** [comment]
Interesting, I know my customer has specifically requested two output log files (one for stdout and one for stderr) as described above. But, I see your point on the performance...

**Comment by adamjk-dev** [comment]
Yeah, I just tested this, and I don't see some of my applications output that is being sent to STDOUT, maybe this is due to what you were saying?

**Comment by biemond** [comment]
In the weblogic console you can try on the advanced log options of a managed server to enable  redirect stdout to server log

**Comment by adamjk-dev** [comment]
My coworker says this option:
http://docs.oracle.com/cd/E17904_01/web.1111/e13739/config_logs.htm#WLLOG163

-Dweblogic.log.RedirectStdoutToServerLogEnabled=true

**Comment by biemond** [comment]
indeed that does the same.

is the application using a Logger or doing System.out

**Comment by adamjk-dev** [comment]
We just wrote a quick test app to write to stdout and stderr, so I am not sure. I am asking who wrote it. I imagine he just used a System.out, but will know soon. Does it make a difference?

**Comment by biemond** [comment]
I think with a logger, default every under warning is ignored . So when you log a warning or an error you should see it.  system out only when you set weblogic.log.RedirectStdoutToServerLogEnabled=true you can see this output in the normal log but It should be there in the nodemanager log, off course when you use the nodemanager to start the managed server.

**Comment by adamjk-dev** [comment]
So, I added the RedirectStdoutToServerLogEnabled for both my WL 10 and 12 offerings. This seems to have allowed the output to route to where it should go.
